import type { Translation } from '@mdxeditor/editor'

const MDXEDITOR_ZH_CN_MESSAGES: Record<string, string> = {
  'admonitions.caution': '注意',
  'admonitions.changeType': '选择提示类型',
  'admonitions.danger': '危险',
  'admonitions.info': '信息',
  'admonitions.note': '备注',
  'admonitions.placeholder': '提示类型',
  'admonitions.tip': '提示',
  'codeBlock.inlineLanguage': '语言',
  'codeBlock.language': '代码块语言',
  'codeBlock.selectLanguage': '选择代码块语言',
  'codeblock.delete': '删除代码块',
  'contentArea.editableMarkdown': '可编辑 Markdown',
  'createLink.cancelTooltip': '取消修改',
  'createLink.saveTooltip': '设置 URL',
  'createLink.text': '链接文字',
  'createLink.textTooltip': '链接显示的文字',
  'createLink.title': '链接标题',
  'createLink.titleTooltip': '鼠标悬停时显示的链接标题',
  'createLink.url': 'URL',
  'createLink.urlPlaceholder': '选择或粘贴 URL',
  'dialog.close': '关闭弹窗',
  'dialogControls.cancel': '取消',
  'dialogControls.save': '保存',
  'frontmatterEditor.addEntry': '添加条目',
  'frontmatterEditor.key': '键',
  'frontmatterEditor.title': '编辑文档 Frontmatter',
  'frontmatterEditor.value': '值',
  'imageEditor.deleteImage': '删除图片',
  'imageEditor.editImage': '编辑图片',
  'linkPreview.copied': '已复制',
  'linkPreview.copyToClipboard': '复制到剪贴板',
  'linkPreview.edit': '编辑链接 URL',
  'linkPreview.remove': '移除链接',
  'table.alignCenter': '居中对齐',
  'table.alignLeft': '左对齐',
  'table.alignRight': '右对齐',
  'table.columnMenu': '列菜单',
  'table.deleteColumn': '删除此列',
  'table.deleteRow': '删除此行',
  'table.deleteTable': '删除表格',
  'table.insertColumnLeft': '在左侧插入列',
  'table.insertColumnRight': '在右侧插入列',
  'table.insertRowAbove': '在上方插入行',
  'table.insertRowBelow': '在下方插入行',
  'table.rowMenu': '行菜单',
  'table.textAlignment': '文本对齐',
  'toolbar.admonition': '插入提示块',
  'toolbar.blockTypeSelect.placeholder': '块类型',
  'toolbar.blockTypeSelect.selectBlockTypeTooltip': '选择块类型',
  'toolbar.blockTypes.heading': '标题 {{level}}',
  'toolbar.blockTypes.paragraph': '正文',
  'toolbar.blockTypes.quote': '引用',
  'toolbar.bold': '加粗',
  'toolbar.bulletedList': '无序列表',
  'toolbar.checkList': '任务列表',
  'toolbar.codeBlock': '插入代码块',
  'toolbar.diffMode': '差异模式',
  'toolbar.editFrontmatter': '编辑 Frontmatter',
  'toolbar.highlight': '高亮',
  'toolbar.image': '插入图片',
  'toolbar.inlineCode': '行内代码',
  'toolbar.insertFrontmatter': '插入 Frontmatter',
  'toolbar.italic': '斜体',
  'toolbar.link': '创建链接',
  'toolbar.numberedList': '有序列表',
  'toolbar.redo': '重做 {{shortcut}}',
  'toolbar.removeBold': '取消加粗',
  'toolbar.removeHighlight': '取消高亮',
  'toolbar.removeInlineCode': '取消行内代码',
  'toolbar.removeItalic': '取消斜体',
  'toolbar.removeStrikethrough': '取消删除线',
  'toolbar.removeSubscript': '取消下标',
  'toolbar.removeSuperscript': '取消上标',
  'toolbar.removeUnderline': '取消下划线',
  'toolbar.richText': '富文本',
  'toolbar.source': '源码模式',
  'toolbar.strikethrough': '删除线',
  'toolbar.subscript': '下标',
  'toolbar.superscript': '上标',
  'toolbar.table': '插入表格',
  'toolbar.thematicBreak': '插入分割线',
  'toolbar.toggleGroup': '切换组',
  'toolbar.underline': '下划线',
  'toolbar.undo': '撤销 {{shortcut}}',
  'uploadImage.addViaUrlInstructions': '或通过 URL 添加图片：',
  'uploadImage.addViaUrlInstructionsNoUpload': '通过 URL 添加图片：',
  'uploadImage.alt': '替代文本：',
  'uploadImage.autoCompletePlaceholder': '选择或粘贴图片地址',
  'uploadImage.dialogTitle': '上传图片',
  'uploadImage.height': '高度：',
  'uploadImage.title': '标题：',
  'uploadImage.uploadInstructions': '从设备上传图片：',
  'uploadImage.width': '宽度：',
}

export const mdxEditorZhCnTranslation: Translation = (key, defaultValue, interpolations = {}) => {
  return interpolateMdxEditorTranslation(MDXEDITOR_ZH_CN_MESSAGES[key] ?? defaultValue, interpolations)
}

function interpolateMdxEditorTranslation(value: string, interpolations: Record<string, unknown>): string {
  return Object.entries(interpolations).reduce(
    (current, [key, interpolation]) => current.replaceAll(`{{${key}}}`, String(interpolation)),
    value
  )
}
