const DATABASE_ROW_LIST_DEFAULT_LIMIT = 100
const DATABASE_ROW_LIST_MAX_LIMIT = 500
const DATABASE_OPERATION_LOG_LIST_DEFAULT_LIMIT = 50
const DATABASE_OPERATION_LOG_LIST_MAX_LIMIT = 500

export {
  DATABASE_OPERATION_LOG_LIST_DEFAULT_LIMIT,
  DATABASE_OPERATION_LOG_LIST_MAX_LIMIT,
  DATABASE_ROW_LIST_DEFAULT_LIMIT,
  DATABASE_ROW_LIST_MAX_LIMIT,
}
