import { createHash } from "node:crypto"
import { EventEmitter } from "node:events"
import { createMainLogger } from "./log-store"

export const CLIPBOARD_SYNC_SERVICE_ID = "core.clipboard-sync"

/**
 * 内存环的长度。
 *
 * 手机本地另有 50 条，这一份只用来回答「这台电脑最近复制过什么」——手机刚连上、
 * 刚切到这台电脑、或者重装过 App 时，靠它把列表立刻填上。
 *
 * 只在内存里，**不落盘**。落盘会落进 ADR 0211 想避免的那一类（剪切板正文长期
 * 留存）；不写快照，那条规则就没有适用对象。
 */
export const CLIPBOARD_SYNC_MAX_ENTRIES = 20

/** 单条上限。剪切板能力本身允许 1 MiB，但走 WS 帧不值得为超长文本破例。 */
export const CLIPBOARD_SYNC_MAX_TEXT_BYTES = 128 * 1024

/**
 * 轮询间隔，毫秒。
 *
 * 定在 1 秒有两个理由，都不是随手取的：
 *
 * 1. Electron 没有剪切板变更事件，也没有 `NSPasteboard.changeCount` 那样廉价的
 *    探针（`electron.d.ts` 的 `Clipboard` 接口里只有 availableFormats / has /
 *    readBuffer / readText），检测只能靠定时读 + 比对。
 * 2. 装了其它剪切板管理器的机器上，密码管理器打的 concealed 标记可能在约 1 秒内
 *    被第三方抹掉（2026-09-21 用 PastePal 实测）。间隔越长，越容易落在抹除之后
 *    才读到，那一秒就是漏掉一个密码的窗口。
 *
 * 代价实测过，不要凭直觉以为它贵：一次比对（readText + sha256）空剪切板 2.8µs、
 * 1KB 23µs、50KB 116µs、5MB 10.8ms。按单条 128KB 的上限算，稳态在 0.3ms/秒以下。
 */
export const CLIPBOARD_SYNC_POLL_INTERVAL_MS = 1_000

/**
 * macOS 上「不要把这段内容记进历史」的粘贴板类型。
 *
 * 密码管理器复制密码时会打第一个；Qt 系的工具在 macOS 上看到的是第二个名字，
 * 两种都真实存在过（CopyQ 与 KDE Connect 的缺陷报告里各出现一个），所以两个都查。
 *
 * 判断只能用 `readBuffer(type).length > 0`：`availableFormats()` 和 `has()` 对
 * 自定义 UTI 一律说谎（前者只回 `["text/plain"]`，后者回 false），只有 readBuffer
 * 会把格式名原样透传给 NSPasteboard。这是实测结论，不要"顺手改成更直白的写法"。
 *
 * nspasteboard.org 还定义了 TransientType 与 AutoGeneratedType，本服务刻意不查：
 * 要拦的是密码，多拦一类在界面上的表现是「我明明复制了却什么都没发生」，比漏拦
 * 更难向用户解释。
 */
const CONCEALED_PASTEBOARD_TYPES = [
  "org.nspasteboard.ConcealedType",
  "application/x-nspasteboard-concealed-type",
] as const

export type ClipboardSyncEntry = {
  readonly id: string
  readonly text: string
  readonly copiedAt: string
}

/**
 * 只用到两个方法的窄端口。
 *
 * 刻意不复用 `app-capabilities/clipboard` 的 `ClipboardAdapter`：那是 Workflow
 * 节点的能力契约（`CONTEXT.md` 明文声明它只做纯文本、不碰其它格式），而这里需要
 * 读粘贴板类型。窄端口同时让单测不必起 Electron。
 */
export type ClipboardSyncReader = {
  readText(): string
  readBuffer(format: string): Buffer
}

type ClipboardSyncServiceEvents = {
  changed: [payload: { entries: ClipboardSyncEntry[] }]
}

class TypedClipboardSyncEventEmitter extends EventEmitter {
  override on<K extends keyof ClipboardSyncServiceEvents>(
    eventName: K,
    listener: (...args: ClipboardSyncServiceEvents[K]) => void,
  ): this {
    return super.on(eventName, listener)
  }

  override emit<K extends keyof ClipboardSyncServiceEvents>(
    eventName: K,
    ...args: ClipboardSyncServiceEvents[K]
  ): boolean {
    return super.emit(eventName, ...args)
  }
}

export type ClipboardSyncServiceDeps = {
  readonly clipboard: ClipboardSyncReader
  readonly now?: () => Date
  /** 注入以便单测用手动定时器驱动，照 mobile-gateway-service 的既有约定。 */
  readonly setTimeout?: (callback: () => void, delayMs: number) => NodeJS.Timeout
  readonly clearTimeout?: (handle: NodeJS.Timeout) => void
}

const logger = createMainLogger("service.clipboard-sync")

function hashText(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex")
}

/**
 * 盯着系统剪切板，把用户复制过的文本攒在内存里，变更时发一次 `changed`。
 *
 * 它不知道自己有没有观众，也不该知道：有没有手机连着是推送那一层的事，而这一层
 * 必须一直跑——只在有手机连着时才采集的话，手机刚连上时电脑手里一条历史都没有，
 * 「补 20 条」这个承诺就不成立。
 */
export class ClipboardSyncService {
  readonly events = new TypedClipboardSyncEventEmitter()

  private readonly clipboard: ClipboardSyncReader
  private readonly now: () => Date
  private readonly setTimer: (callback: () => void, delayMs: number) => NodeJS.Timeout
  private readonly clearTimer: (handle: NodeJS.Timeout) => void

  private entries: ClipboardSyncEntry[] = []
  private lastHash = ""
  private timer: NodeJS.Timeout | null = null
  private started = false

  constructor(deps: ClipboardSyncServiceDeps) {
    this.clipboard = deps.clipboard
    this.now = deps.now ?? (() => new Date())
    this.setTimer = deps.setTimeout ?? ((callback, delayMs) => setTimeout(callback, delayMs))
    this.clearTimer = deps.clearTimeout ?? ((handle) => clearTimeout(handle))
  }

  start(): void {
    if (this.started) return
    this.started = true
    logger.info("clipboard sync watching")
    this.schedule()
  }

  stop(): void {
    this.started = false
    if (this.timer) {
      this.clearTimer(this.timer)
      this.timer = null
    }
  }

  /** 最近复制过的条目，最新在前。返回副本，调用方改不动这里的状态。 */
  snapshot(): ClipboardSyncEntry[] {
    return [...this.entries]
  }

  /**
   * 自递归的 setTimeout，而不是 setInterval：回调第一句先清 handle、最后重排，
   * 这样 stop() 一定拦得住下一次，单测也能用手动定时器一步步推进。
   */
  private schedule(): void {
    if (!this.started || this.timer) return
    this.timer = this.setTimer(() => {
      this.timer = null
      try {
        this.poll()
      } catch (error) {
        // 一次读失败不能把定时器链条断掉，否则后面再复制什么都没人看了。
        logger.warn("clipboard poll failed", { error })
      }
      this.schedule()
    }, CLIPBOARD_SYNC_POLL_INTERVAL_MS)
  }

  private poll(): void {
    const text = this.clipboard.readText()

    // 空剪切板是一个独立状态，指纹要跟着清掉：否则「清空后再复制同一段文字」
    // 会被当成没变过而不记录。
    //
    // 只由空白组成的内容按同样方式处理，两个理由：它在手机的列表里就是一行空白，
    // 看起来像坏了；而协议那边的校验器也不接受它（`boundedString` 会先 trim 再判空）。
    // 判据只放在这一处，两端就只有一个口径 —— 否则复制一段纯缩进会让手机整包拒收
    // 那 20 条。
    if (!text || !text.trim()) {
      this.lastHash = ""
      return
    }

    if (this.isConcealed()) {
      // 刻意不更新指纹。这段内容可能是密码：既不为它算哈希，也别让它进任何变量
      // 停留。代价是它留在剪切板期间每秒重跑一次格式探测（微秒级），换来的是
      // 正文一次都不落内存。
      return
    }

    const bytes = Buffer.byteLength(text, "utf8")
    if (bytes > CLIPBOARD_SYNC_MAX_TEXT_BYTES) {
      // 指纹照更新，否则每秒都要重新哈希一遍这个大字符串。
      this.lastHash = hashText(text)
      logger.info("clipboard entry skipped: over budget", { bytes })
      return
    }

    const hash = hashText(text)
    if (hash === this.lastHash) return
    this.lastHash = hash

    const entry: ClipboardSyncEntry = {
      id: hash,
      text,
      copiedAt: this.now().toISOString(),
    }
    // 同一段内容再复制一次不新增条目，把它提到最前——这同时解决了「重新连上时
    // 电脑补推当前剪切板」造成的重复。
    this.entries = [entry, ...this.entries.filter((existing) => existing.id !== hash)].slice(
      0,
      CLIPBOARD_SYNC_MAX_ENTRIES,
    )
    this.events.emit("changed", { entries: this.snapshot() })
  }

  private isConcealed(): boolean {
    for (const format of CONCEALED_PASTEBOARD_TYPES) {
      try {
        if (this.clipboard.readBuffer(format).length > 0) return true
      } catch (error) {
        // 非 macOS 平台上读这个类型会抛。抛就等于「没有这个标记」，但别把它
        // 当成"不敏感"以外的东西——这里记一条 debug，继续看下一个名字。
        logger.debug("clipboard concealed probe unavailable", { format, error })
      }
    }
    return false
  }
}
