const CONTENT_SKILL_ATTACHMENT_MAX_SIZE = 10 * 1024 * 1024
const CONTENT_SKILL_ATTACHMENT_TOTAL_MAX_SIZE = 50 * 1024 * 1024
const CONTENT_SKILL_ATTACHMENT_MAX_COUNT = 100

export {
  CONTENT_SKILL_ATTACHMENT_MAX_COUNT,
  CONTENT_SKILL_ATTACHMENT_MAX_SIZE,
  CONTENT_SKILL_ATTACHMENT_TOTAL_MAX_SIZE,
}
