const CONTENT_SKILL_ATTACHMENT_MAX_SIZE = 10 * 1024 * 1024
const CONTENT_SKILL_ATTACHMENT_TOTAL_MAX_SIZE = 50 * 1024 * 1024
const CONTENT_SKILL_ATTACHMENT_MAX_COUNT = 100
const CONTENT_SKILL_SOURCE_MAX_ENTRIES_PER_DIRECTORY = 1_000
const CONTENT_SKILL_SOURCE_MAX_DIRECTORY_COUNT = 200
const CONTENT_SKILL_SOURCE_MAX_DEPTH = 8

export {
  CONTENT_SKILL_ATTACHMENT_MAX_COUNT,
  CONTENT_SKILL_ATTACHMENT_MAX_SIZE,
  CONTENT_SKILL_ATTACHMENT_TOTAL_MAX_SIZE,
  CONTENT_SKILL_SOURCE_MAX_DEPTH,
  CONTENT_SKILL_SOURCE_MAX_DIRECTORY_COUNT,
  CONTENT_SKILL_SOURCE_MAX_ENTRIES_PER_DIRECTORY,
}
