/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ShareShareIdRouteImport } from './routes/share/$shareId'
import { Route as authTeamInviteRouteImport } from './routes/(auth)/team-invite'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWebhooksIndexRouteImport } from './routes/_authenticated/webhooks/index'
import { Route as AuthenticatedWebhookDeliveriesIndexRouteImport } from './routes/_authenticated/webhook-deliveries/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams/index'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system/index'
import { Route as AuthenticatedSkillRepositoriesIndexRouteImport } from './routes/_authenticated/skill-repositories/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedMyDevicesIndexRouteImport } from './routes/_authenticated/my-devices/index'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs/index'
import { Route as AuthenticatedInvitationsIndexRouteImport } from './routes/_authenticated/invitations/index'
import { Route as AuthenticatedDriveIndexRouteImport } from './routes/_authenticated/drive/index'
import { Route as AuthenticatedDevicesIndexRouteImport } from './routes/_authenticated/devices/index'
import { Route as AuthenticatedBackupIndexRouteImport } from './routes/_authenticated/backup/index'
import { Route as AuthenticatedAuditLogsIndexRouteImport } from './routes/_authenticated/audit-logs/index'
import { Route as AuthenticatedAdminDriveIndexRouteImport } from './routes/_authenticated/admin-drive/index'
import { Route as AuthenticatedWebhooksWebhookIdRouteImport } from './routes/_authenticated/webhooks/$webhookId'
import { Route as AuthenticatedSkillRepositoriesExploreRouteImport } from './routes/_authenticated/skill-repositories/explore'
import { Route as AuthenticatedSkillRepositoriesAdminRouteImport } from './routes/_authenticated/skill-repositories/admin'
import { Route as AuthenticatedSkillRepositoriesRepositoryIdRouteImport } from './routes/_authenticated/skill-repositories/$repositoryId'
import { Route as authAuthDesktopRouteImport } from './routes/(auth)/auth/desktop'
import { Route as ShareShareIdItemsBrowserItemIdRouteImport } from './routes/share/$shareId_/items/$browserItemId'
import { Route as AuthenticatedSkillsOwnerHandleRepositoryNameRouteImport } from './routes/_authenticated/skills/$ownerHandle/$repositoryName'
import { Route as AuthenticatedDriveItemsBrowserItemIdRouteImport } from './routes/_authenticated/drive/items/$browserItemId'
import { Route as AuthenticatedDriveFoldersFolderIdRouteImport } from './routes/_authenticated/drive/folders/$folderId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const authTeamInviteRoute = authTeamInviteRouteImport.update({
  id: '/(auth)/team-invite',
  path: '/team-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebhooksIndexRoute =
  AuthenticatedWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebhookDeliveriesIndexRoute =
  AuthenticatedWebhookDeliveriesIndexRouteImport.update({
    id: '/webhook-deliveries/',
    path: '/webhook-deliveries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkillRepositoriesIndexRoute =
  AuthenticatedSkillRepositoriesIndexRouteImport.update({
    id: '/skill-repositories/',
    path: '/skill-repositories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedMyDevicesIndexRoute =
  AuthenticatedMyDevicesIndexRouteImport.update({
    id: '/my-devices/',
    path: '/my-devices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsIndexRoute =
  AuthenticatedInvitationsIndexRouteImport.update({
    id: '/invitations/',
    path: '/invitations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriveIndexRoute = AuthenticatedDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesIndexRoute =
  AuthenticatedDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBackupIndexRoute =
  AuthenticatedBackupIndexRouteImport.update({
    id: '/backup/',
    path: '/backup/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogsIndexRoute =
  AuthenticatedAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDriveIndexRoute =
  AuthenticatedAdminDriveIndexRouteImport.update({
    id: '/admin-drive/',
    path: '/admin-drive/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebhooksWebhookIdRoute =
  AuthenticatedWebhooksWebhookIdRouteImport.update({
    id: '/webhooks/$webhookId',
    path: '/webhooks/$webhookId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkillRepositoriesExploreRoute =
  AuthenticatedSkillRepositoriesExploreRouteImport.update({
    id: '/skill-repositories/explore',
    path: '/skill-repositories/explore',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkillRepositoriesAdminRoute =
  AuthenticatedSkillRepositoriesAdminRouteImport.update({
    id: '/skill-repositories/admin',
    path: '/skill-repositories/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkillRepositoriesRepositoryIdRoute =
  AuthenticatedSkillRepositoriesRepositoryIdRouteImport.update({
    id: '/skill-repositories/$repositoryId',
    path: '/skill-repositories/$repositoryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authAuthDesktopRoute = authAuthDesktopRouteImport.update({
  id: '/(auth)/auth/desktop',
  path: '/auth/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdItemsBrowserItemIdRoute =
  ShareShareIdItemsBrowserItemIdRouteImport.update({
    id: '/share/$shareId_/items/$browserItemId',
    path: '/share/$shareId/items/$browserItemId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSkillsOwnerHandleRepositoryNameRoute =
  AuthenticatedSkillsOwnerHandleRepositoryNameRouteImport.update({
    id: '/skills/$ownerHandle/$repositoryName',
    path: '/skills/$ownerHandle/$repositoryName',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriveItemsBrowserItemIdRoute =
  AuthenticatedDriveItemsBrowserItemIdRouteImport.update({
    id: '/drive/items/$browserItemId',
    path: '/drive/items/$browserItemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriveFoldersFolderIdRoute =
  AuthenticatedDriveFoldersFolderIdRouteImport.update({
    id: '/drive/folders/$folderId',
    path: '/drive/folders/$folderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/team-invite': typeof authTeamInviteRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/auth/desktop': typeof authAuthDesktopRoute
  '/skill-repositories/$repositoryId': typeof AuthenticatedSkillRepositoriesRepositoryIdRoute
  '/skill-repositories/admin': typeof AuthenticatedSkillRepositoriesAdminRoute
  '/skill-repositories/explore': typeof AuthenticatedSkillRepositoriesExploreRoute
  '/webhooks/$webhookId': typeof AuthenticatedWebhooksWebhookIdRoute
  '/admin-drive/': typeof AuthenticatedAdminDriveIndexRoute
  '/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/backup/': typeof AuthenticatedBackupIndexRoute
  '/devices/': typeof AuthenticatedDevicesIndexRoute
  '/drive/': typeof AuthenticatedDriveIndexRoute
  '/invitations/': typeof AuthenticatedInvitationsIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/my-devices/': typeof AuthenticatedMyDevicesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/skill-repositories/': typeof AuthenticatedSkillRepositoriesIndexRoute
  '/system/': typeof AuthenticatedSystemIndexRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/webhook-deliveries/': typeof AuthenticatedWebhookDeliveriesIndexRoute
  '/webhooks/': typeof AuthenticatedWebhooksIndexRoute
  '/drive/folders/$folderId': typeof AuthenticatedDriveFoldersFolderIdRoute
  '/drive/items/$browserItemId': typeof AuthenticatedDriveItemsBrowserItemIdRoute
  '/skills/$ownerHandle/$repositoryName': typeof AuthenticatedSkillsOwnerHandleRepositoryNameRoute
  '/share/$shareId/items/$browserItemId': typeof ShareShareIdItemsBrowserItemIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/team-invite': typeof authTeamInviteRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth/desktop': typeof authAuthDesktopRoute
  '/skill-repositories/$repositoryId': typeof AuthenticatedSkillRepositoriesRepositoryIdRoute
  '/skill-repositories/admin': typeof AuthenticatedSkillRepositoriesAdminRoute
  '/skill-repositories/explore': typeof AuthenticatedSkillRepositoriesExploreRoute
  '/webhooks/$webhookId': typeof AuthenticatedWebhooksWebhookIdRoute
  '/admin-drive': typeof AuthenticatedAdminDriveIndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/backup': typeof AuthenticatedBackupIndexRoute
  '/devices': typeof AuthenticatedDevicesIndexRoute
  '/drive': typeof AuthenticatedDriveIndexRoute
  '/invitations': typeof AuthenticatedInvitationsIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/my-devices': typeof AuthenticatedMyDevicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/skill-repositories': typeof AuthenticatedSkillRepositoriesIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/webhook-deliveries': typeof AuthenticatedWebhookDeliveriesIndexRoute
  '/webhooks': typeof AuthenticatedWebhooksIndexRoute
  '/drive/folders/$folderId': typeof AuthenticatedDriveFoldersFolderIdRoute
  '/drive/items/$browserItemId': typeof AuthenticatedDriveItemsBrowserItemIdRoute
  '/skills/$ownerHandle/$repositoryName': typeof AuthenticatedSkillsOwnerHandleRepositoryNameRoute
  '/share/$shareId/items/$browserItemId': typeof ShareShareIdItemsBrowserItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/team-invite': typeof authTeamInviteRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/(auth)/auth/desktop': typeof authAuthDesktopRoute
  '/_authenticated/skill-repositories/$repositoryId': typeof AuthenticatedSkillRepositoriesRepositoryIdRoute
  '/_authenticated/skill-repositories/admin': typeof AuthenticatedSkillRepositoriesAdminRoute
  '/_authenticated/skill-repositories/explore': typeof AuthenticatedSkillRepositoriesExploreRoute
  '/_authenticated/webhooks/$webhookId': typeof AuthenticatedWebhooksWebhookIdRoute
  '/_authenticated/admin-drive/': typeof AuthenticatedAdminDriveIndexRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/_authenticated/backup/': typeof AuthenticatedBackupIndexRoute
  '/_authenticated/devices/': typeof AuthenticatedDevicesIndexRoute
  '/_authenticated/drive/': typeof AuthenticatedDriveIndexRoute
  '/_authenticated/invitations/': typeof AuthenticatedInvitationsIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/my-devices/': typeof AuthenticatedMyDevicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/skill-repositories/': typeof AuthenticatedSkillRepositoriesIndexRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/webhook-deliveries/': typeof AuthenticatedWebhookDeliveriesIndexRoute
  '/_authenticated/webhooks/': typeof AuthenticatedWebhooksIndexRoute
  '/_authenticated/drive/folders/$folderId': typeof AuthenticatedDriveFoldersFolderIdRoute
  '/_authenticated/drive/items/$browserItemId': typeof AuthenticatedDriveItemsBrowserItemIdRoute
  '/_authenticated/skills/$ownerHandle/$repositoryName': typeof AuthenticatedSkillsOwnerHandleRepositoryNameRoute
  '/share/$shareId_/items/$browserItemId': typeof ShareShareIdItemsBrowserItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/team-invite'
    | '/share/$shareId'
    | '/auth/desktop'
    | '/skill-repositories/$repositoryId'
    | '/skill-repositories/admin'
    | '/skill-repositories/explore'
    | '/webhooks/$webhookId'
    | '/admin-drive/'
    | '/audit-logs/'
    | '/backup/'
    | '/devices/'
    | '/drive/'
    | '/invitations/'
    | '/logs/'
    | '/my-devices/'
    | '/settings/'
    | '/skill-repositories/'
    | '/system/'
    | '/teams/'
    | '/users/'
    | '/webhook-deliveries/'
    | '/webhooks/'
    | '/drive/folders/$folderId'
    | '/drive/items/$browserItemId'
    | '/skills/$ownerHandle/$repositoryName'
    | '/share/$shareId/items/$browserItemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/team-invite'
    | '/share/$shareId'
    | '/'
    | '/auth/desktop'
    | '/skill-repositories/$repositoryId'
    | '/skill-repositories/admin'
    | '/skill-repositories/explore'
    | '/webhooks/$webhookId'
    | '/admin-drive'
    | '/audit-logs'
    | '/backup'
    | '/devices'
    | '/drive'
    | '/invitations'
    | '/logs'
    | '/my-devices'
    | '/settings'
    | '/skill-repositories'
    | '/system'
    | '/teams'
    | '/users'
    | '/webhook-deliveries'
    | '/webhooks'
    | '/drive/folders/$folderId'
    | '/drive/items/$browserItemId'
    | '/skills/$ownerHandle/$repositoryName'
    | '/share/$shareId/items/$browserItemId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/team-invite'
    | '/share/$shareId'
    | '/_authenticated/'
    | '/(auth)/auth/desktop'
    | '/_authenticated/skill-repositories/$repositoryId'
    | '/_authenticated/skill-repositories/admin'
    | '/_authenticated/skill-repositories/explore'
    | '/_authenticated/webhooks/$webhookId'
    | '/_authenticated/admin-drive/'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/backup/'
    | '/_authenticated/devices/'
    | '/_authenticated/drive/'
    | '/_authenticated/invitations/'
    | '/_authenticated/logs/'
    | '/_authenticated/my-devices/'
    | '/_authenticated/settings/'
    | '/_authenticated/skill-repositories/'
    | '/_authenticated/system/'
    | '/_authenticated/teams/'
    | '/_authenticated/users/'
    | '/_authenticated/webhook-deliveries/'
    | '/_authenticated/webhooks/'
    | '/_authenticated/drive/folders/$folderId'
    | '/_authenticated/drive/items/$browserItemId'
    | '/_authenticated/skills/$ownerHandle/$repositoryName'
    | '/share/$shareId_/items/$browserItemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authTeamInviteRoute: typeof authTeamInviteRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  authAuthDesktopRoute: typeof authAuthDesktopRoute
  ShareShareIdItemsBrowserItemIdRoute: typeof ShareShareIdItemsBrowserItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/team-invite': {
      id: '/(auth)/team-invite'
      path: '/team-invite'
      fullPath: '/team-invite'
      preLoaderRoute: typeof authTeamInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks/': {
      id: '/_authenticated/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AuthenticatedWebhooksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhook-deliveries/': {
      id: '/_authenticated/webhook-deliveries/'
      path: '/webhook-deliveries'
      fullPath: '/webhook-deliveries/'
      preLoaderRoute: typeof AuthenticatedWebhookDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skill-repositories/': {
      id: '/_authenticated/skill-repositories/'
      path: '/skill-repositories'
      fullPath: '/skill-repositories/'
      preLoaderRoute: typeof AuthenticatedSkillRepositoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/my-devices/': {
      id: '/_authenticated/my-devices/'
      path: '/my-devices'
      fullPath: '/my-devices/'
      preLoaderRoute: typeof AuthenticatedMyDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations/': {
      id: '/_authenticated/invitations/'
      path: '/invitations'
      fullPath: '/invitations/'
      preLoaderRoute: typeof AuthenticatedInvitationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/': {
      id: '/_authenticated/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof AuthenticatedDriveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices/': {
      id: '/_authenticated/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthenticatedDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup/': {
      id: '/_authenticated/backup/'
      path: '/backup'
      fullPath: '/backup/'
      preLoaderRoute: typeof AuthenticatedBackupIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-drive/': {
      id: '/_authenticated/admin-drive/'
      path: '/admin-drive'
      fullPath: '/admin-drive/'
      preLoaderRoute: typeof AuthenticatedAdminDriveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks/$webhookId': {
      id: '/_authenticated/webhooks/$webhookId'
      path: '/webhooks/$webhookId'
      fullPath: '/webhooks/$webhookId'
      preLoaderRoute: typeof AuthenticatedWebhooksWebhookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skill-repositories/explore': {
      id: '/_authenticated/skill-repositories/explore'
      path: '/skill-repositories/explore'
      fullPath: '/skill-repositories/explore'
      preLoaderRoute: typeof AuthenticatedSkillRepositoriesExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skill-repositories/admin': {
      id: '/_authenticated/skill-repositories/admin'
      path: '/skill-repositories/admin'
      fullPath: '/skill-repositories/admin'
      preLoaderRoute: typeof AuthenticatedSkillRepositoriesAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skill-repositories/$repositoryId': {
      id: '/_authenticated/skill-repositories/$repositoryId'
      path: '/skill-repositories/$repositoryId'
      fullPath: '/skill-repositories/$repositoryId'
      preLoaderRoute: typeof AuthenticatedSkillRepositoriesRepositoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/auth/desktop': {
      id: '/(auth)/auth/desktop'
      path: '/auth/desktop'
      fullPath: '/auth/desktop'
      preLoaderRoute: typeof authAuthDesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId_/items/$browserItemId': {
      id: '/share/$shareId_/items/$browserItemId'
      path: '/share/$shareId/items/$browserItemId'
      fullPath: '/share/$shareId/items/$browserItemId'
      preLoaderRoute: typeof ShareShareIdItemsBrowserItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skills/$ownerHandle/$repositoryName': {
      id: '/_authenticated/skills/$ownerHandle/$repositoryName'
      path: '/skills/$ownerHandle/$repositoryName'
      fullPath: '/skills/$ownerHandle/$repositoryName'
      preLoaderRoute: typeof AuthenticatedSkillsOwnerHandleRepositoryNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/items/$browserItemId': {
      id: '/_authenticated/drive/items/$browserItemId'
      path: '/drive/items/$browserItemId'
      fullPath: '/drive/items/$browserItemId'
      preLoaderRoute: typeof AuthenticatedDriveItemsBrowserItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/folders/$folderId': {
      id: '/_authenticated/drive/folders/$folderId'
      path: '/drive/folders/$folderId'
      fullPath: '/drive/folders/$folderId'
      preLoaderRoute: typeof AuthenticatedDriveFoldersFolderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSkillRepositoriesRepositoryIdRoute: typeof AuthenticatedSkillRepositoriesRepositoryIdRoute
  AuthenticatedSkillRepositoriesAdminRoute: typeof AuthenticatedSkillRepositoriesAdminRoute
  AuthenticatedSkillRepositoriesExploreRoute: typeof AuthenticatedSkillRepositoriesExploreRoute
  AuthenticatedWebhooksWebhookIdRoute: typeof AuthenticatedWebhooksWebhookIdRoute
  AuthenticatedAdminDriveIndexRoute: typeof AuthenticatedAdminDriveIndexRoute
  AuthenticatedAuditLogsIndexRoute: typeof AuthenticatedAuditLogsIndexRoute
  AuthenticatedBackupIndexRoute: typeof AuthenticatedBackupIndexRoute
  AuthenticatedDevicesIndexRoute: typeof AuthenticatedDevicesIndexRoute
  AuthenticatedDriveIndexRoute: typeof AuthenticatedDriveIndexRoute
  AuthenticatedInvitationsIndexRoute: typeof AuthenticatedInvitationsIndexRoute
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
  AuthenticatedMyDevicesIndexRoute: typeof AuthenticatedMyDevicesIndexRoute
  AuthenticatedSkillRepositoriesIndexRoute: typeof AuthenticatedSkillRepositoriesIndexRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWebhookDeliveriesIndexRoute: typeof AuthenticatedWebhookDeliveriesIndexRoute
  AuthenticatedWebhooksIndexRoute: typeof AuthenticatedWebhooksIndexRoute
  AuthenticatedDriveFoldersFolderIdRoute: typeof AuthenticatedDriveFoldersFolderIdRoute
  AuthenticatedDriveItemsBrowserItemIdRoute: typeof AuthenticatedDriveItemsBrowserItemIdRoute
  AuthenticatedSkillsOwnerHandleRepositoryNameRoute: typeof AuthenticatedSkillsOwnerHandleRepositoryNameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSkillRepositoriesRepositoryIdRoute:
    AuthenticatedSkillRepositoriesRepositoryIdRoute,
  AuthenticatedSkillRepositoriesAdminRoute:
    AuthenticatedSkillRepositoriesAdminRoute,
  AuthenticatedSkillRepositoriesExploreRoute:
    AuthenticatedSkillRepositoriesExploreRoute,
  AuthenticatedWebhooksWebhookIdRoute: AuthenticatedWebhooksWebhookIdRoute,
  AuthenticatedAdminDriveIndexRoute: AuthenticatedAdminDriveIndexRoute,
  AuthenticatedAuditLogsIndexRoute: AuthenticatedAuditLogsIndexRoute,
  AuthenticatedBackupIndexRoute: AuthenticatedBackupIndexRoute,
  AuthenticatedDevicesIndexRoute: AuthenticatedDevicesIndexRoute,
  AuthenticatedDriveIndexRoute: AuthenticatedDriveIndexRoute,
  AuthenticatedInvitationsIndexRoute: AuthenticatedInvitationsIndexRoute,
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
  AuthenticatedMyDevicesIndexRoute: AuthenticatedMyDevicesIndexRoute,
  AuthenticatedSkillRepositoriesIndexRoute:
    AuthenticatedSkillRepositoriesIndexRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWebhookDeliveriesIndexRoute:
    AuthenticatedWebhookDeliveriesIndexRoute,
  AuthenticatedWebhooksIndexRoute: AuthenticatedWebhooksIndexRoute,
  AuthenticatedDriveFoldersFolderIdRoute:
    AuthenticatedDriveFoldersFolderIdRoute,
  AuthenticatedDriveItemsBrowserItemIdRoute:
    AuthenticatedDriveItemsBrowserItemIdRoute,
  AuthenticatedSkillsOwnerHandleRepositoryNameRoute:
    AuthenticatedSkillsOwnerHandleRepositoryNameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authTeamInviteRoute: authTeamInviteRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  authAuthDesktopRoute: authAuthDesktopRoute,
  ShareShareIdItemsBrowserItemIdRoute: ShareShareIdItemsBrowserItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
