const DATA_TABLE_ID_COLUMN_CLASS = "w-10"
const DATA_TABLE_VALUE_COLUMN_CLASS = "w-36 max-w-36"
const DATA_TABLE_ACTION_COLUMN_CLASS = "w-16"

export {
  DATA_TABLE_ACTION_COLUMN_CLASS,
  DATA_TABLE_ID_COLUMN_CLASS,
  DATA_TABLE_VALUE_COLUMN_CLASS,
}
