export const TOKEN_USAGE_CHANNELS = {
  scan: "synapse:token-usage:scan",
  getGraphResult: "synapse:token-usage:graph-result",
  getModelReport: "synapse:token-usage:model-report",
  getDailyReport: "synapse:token-usage:daily-report",
  getHourlyReport: "synapse:token-usage:hourly-report",
  getHourlyProfile: "synapse:token-usage:hourly-profile",
  getAgentReport: "synapse:token-usage:agent-report",
  getDetectedAgents: "synapse:token-usage:detected-agents",
  clearData: "synapse:token-usage:clear-data",
  cursorAddAccount: "synapse:token-usage:cursor:add-account",
  cursorRemoveAccount: "synapse:token-usage:cursor:remove-account",
  cursorListAccounts: "synapse:token-usage:cursor:list-accounts",
  cursorSetActive: "synapse:token-usage:cursor:set-active",
  cursorSync: "synapse:token-usage:cursor:sync",
  cursorValidate: "synapse:token-usage:cursor:validate",
  cursorLogin: "synapse:token-usage:cursor:login",
} as const
