export const USAGE_ANALYSIS_CHANNELS = {
  ccRefresh: "synapse:app:usage_analysis:cc:refresh",
  ccOverview: "synapse:app:usage_analysis:cc:overview",
  ccTime: "synapse:app:usage_analysis:cc:time",
  ccModels: "synapse:app:usage_analysis:cc:models",
  ccProjects: "synapse:app:usage_analysis:cc:projects",
  ccTools: "synapse:app:usage_analysis:cc:tools",
  ccDetails: "synapse:app:usage_analysis:cc:details",
  ccRecordsList: "synapse:app:usage_analysis:cc:records:list",
  ccRecordDetailsList: "synapse:app:usage_analysis:cc:record_details:list",
  ccRecordsSearchText: "synapse:app:usage_analysis:cc:records:search_text",
  ccConversationsList: "synapse:app:usage_analysis:cc:conversations:list",
  ccConversationGet: "synapse:app:usage_analysis:cc:conversation:get",
  ccConversationChunkGet: "synapse:app:usage_analysis:cc:conversation:chunk:get",
  ccConversationSearchText: "synapse:app:usage_analysis:cc:conversation:search_text",
  ccConversationWindowOpen: "synapse:app:usage_analysis:cc:conversation_window:open",
  codexRefresh: "synapse:app:usage_analysis:codex:refresh",
  codexOverview: "synapse:app:usage_analysis:codex:overview",
  codexTime: "synapse:app:usage_analysis:codex:time",
  codexModels: "synapse:app:usage_analysis:codex:models",
  codexProjects: "synapse:app:usage_analysis:codex:projects",
  codexTools: "synapse:app:usage_analysis:codex:tools",
  codexDetails: "synapse:app:usage_analysis:codex:details",
} as const
