export const USAGE_ANALYSIS_CHANNELS = {
  ccRefresh: "synapse:usage-analysis:cc:refresh",
  ccOverview: "synapse:usage-analysis:cc:overview",
  ccTime: "synapse:usage-analysis:cc:time",
  ccModels: "synapse:usage-analysis:cc:models",
  ccProjects: "synapse:usage-analysis:cc:projects",
  ccTools: "synapse:usage-analysis:cc:tools",
  ccDetails: "synapse:usage-analysis:cc:details",
  ccConversationsList: "synapse:usage-analysis:cc:conversations:list",
  ccConversationGet: "synapse:usage-analysis:cc:conversation:get",
  ccConversationSearchText: "synapse:usage-analysis:cc:conversation:search-text",
  ccConversationWindowOpen: "synapse:usage-analysis:cc:conversation-window:open",
  codexRefresh: "synapse:usage-analysis:codex:refresh",
  codexOverview: "synapse:usage-analysis:codex:overview",
  codexTime: "synapse:usage-analysis:codex:time",
  codexModels: "synapse:usage-analysis:codex:models",
  codexProjects: "synapse:usage-analysis:codex:projects",
  codexTools: "synapse:usage-analysis:codex:tools",
  codexDetails: "synapse:usage-analysis:codex:details",
  pricingRulesGet: "synapse:usage-analysis:pricing-rules:get",
  pricingRulesSave: "synapse:usage-analysis:pricing-rules:save",
} as const
