import { PORTAL_DEVICE_CONTRACTS } from './contracts-portal-device.js'
import { HR_POST_TYPE_AI_CONTRACTS, HR_POST_TYPE_METHOD_CONTRACTS } from './contracts-hr-post-type.js'
import { ATTENDANCE_SHEET_CONTRACTS, ATTENDANCE_SHEET_METHOD_CONTRACTS } from './contracts-attendance-sheet.js'
import { HR_ORGANIZATION_TYPE_AI_CONTRACTS, HR_ORGANIZATION_TYPE_METHOD_CONTRACTS } from './contracts-hr-organization-type.js'
import { HR_ORGANIZATION_PROPERTY_AI_CONTRACTS, HR_ORGANIZATION_PROPERTY_METHOD_CONTRACTS } from './contracts-hr-organization-property.js'
import { TECHNOLOGY_PROJECT_TYPE_CONTRACTS, TECHNOLOGY_PROJECT_TYPE_METHOD_CONTRACTS } from './contracts-technology-project-type.js'
import { TECHNOLOGY_TYPE_TEMPLATE_MAPPING_CONTRACTS, TECHNOLOGY_TYPE_TEMPLATE_MAPPING_METHOD_CONTRACTS } from './contracts-technology-type-template-mapping.js'
import { SETTING_ENTERPRISE_USAGE_AI_CONTRACTS, SETTING_ENTERPRISE_USAGE_METHOD_CONTRACTS } from './contracts-setting-enterprise-usage.js'
import { SETTING_SENSITIVE_ACTION_AI_CONTRACTS, SETTING_SENSITIVE_ACTION_METHOD_CONTRACTS } from './contracts-setting-sensitive-action.js'
import { SETTING_TOKEN_ALLOCATION_AI_CONTRACTS, SETTING_TOKEN_ALLOCATION_METHOD_CONTRACTS } from './contracts-setting-token-allocation.js'
import { TECHNOLOGY_SETTING_TEMPLATE_BASE_CONTRACTS, TECHNOLOGY_SETTING_TEMPLATE_BASE_METHOD_CONTRACTS } from './contracts-technology-setting-template-base.js'
import { TECHNOLOGY_SETTING_TEMPLATE_AI_CONTRACTS, TECHNOLOGY_SETTING_TEMPLATE_METHOD_CONTRACTS } from './contracts-technology-setting-template.js'
import { FINANCE_ACCOUNTING_PERIOD_AI_CONTRACTS, FINANCE_ACCOUNTING_PERIOD_METHOD_CONTRACTS } from './contracts-finance-accounting-period.js'
import { FINANCE_ACCOUNTING_MANAGE_AI_CONTRACTS, FINANCE_ACCOUNTING_MANAGE_METHOD_CONTRACTS } from './contracts-finance-accounting-manage.js'
import { FINANCE_LEDGER_ACCOUNTS_AI_CONTRACTS, FINANCE_LEDGER_ACCOUNTS_METHOD_CONTRACTS } from './contracts-finance-ledger-accounts.js'
import { FINANCE_SETTING_ACCURACY_AI_CONTRACTS, FINANCE_SETTING_ACCURACY_METHOD_CONTRACTS } from './contracts-finance-setting-accuracy.js'
import { FINANCE_ALLOCATION_INDICATOR_AI_CONTRACTS, FINANCE_ALLOCATION_INDICATOR_METHOD_CONTRACTS } from './contracts-finance-setting-allocation-indicator.js'
import { FINANCE_SETTING_ANNUAL_CARRYFORWARD_AI_CONTRACTS, FINANCE_SETTING_ANNUAL_CARRYFORWARD_METHOD_CONTRACTS } from './contracts-finance-setting-annual-carryforward.js'
import { FINANCE_SETTING_CAT_CONFIG_AI_CONTRACTS, FINANCE_SETTING_CAT_CONFIG_METHOD_CONTRACTS } from './contracts-finance-setting-cat-config.js'
import { FINANCE_SETTING_CAT_MAP_AI_CONTRACTS, FINANCE_SETTING_CAT_MAP_METHOD_CONTRACTS } from './contracts-finance-setting-cat-map.js'
import { FINANCE_SETTING_DATE_CONFIG_AI_CONTRACTS, FINANCE_SETTING_DATE_CONFIG_METHOD_CONTRACTS } from './contracts-finance-setting-date-config.js'
import { FINANCE_SETTING_MONTHLY_INCOME_TIME_CONFIG_AI_CONTRACTS, FINANCE_SETTING_MONTHLY_INCOME_TIME_CONFIG_METHOD_CONTRACTS } from './contracts-finance-setting-monthly-income-time-config.js'
import { FINANCE_SETTING_PROJECT_CONTRACTS, FINANCE_SETTING_PROJECT_METHOD_CONTRACTS } from './contracts-finance-setting-project.js'
import { FINANCE_SETTING_RECEIVING_ACCOUNT_AI_CONTRACTS, FINANCE_SETTING_RECEIVING_ACCOUNT_METHOD_CONTRACTS } from './contracts-finance-setting-receiving-account.js'
import { FINANCE_SETTING_RELATED_PARTY_SETTLEMENT_ACCOUNT_AI_CONTRACTS, FINANCE_SETTING_RELATED_PARTY_SETTLEMENT_ACCOUNT_METHOD_CONTRACTS } from './contracts-finance-setting-related-party-settlement-account.js'
import { FINANCE_SETTING_SALE_ALLOCATION_COEFFICIENT_AI_CONTRACTS, FINANCE_SETTING_SALE_ALLOCATION_COEFFICIENT_METHOD_CONTRACTS } from './contracts-finance-setting-sale-allocation-coefficient.js'
import { FINANCE_SETTING_ALLOCATION_RULES_AI_CONTRACTS, FINANCE_SETTING_ALLOCATION_RULES_METHOD_CONTRACTS } from './contracts-finance-setting-allocation-rules.js'
import { FINANCE_SETTING_COST_CENTER_AI_CONTRACTS, FINANCE_SETTING_COST_CENTER_METHOD_CONTRACTS } from './contracts-finance-setting-cost-center.js'
import { FINANCE_SETTING_EMPLOYEE_LOAN_AMOUNT_AI_CONTRACTS, FINANCE_SETTING_EMPLOYEE_LOAN_AMOUNT_METHOD_CONTRACTS } from './contracts-finance-setting-employee-loan-amount.js'
import { FINANCE_SETTING_INITIAL_MANAGE_AI_CONTRACTS, FINANCE_SETTING_INITIAL_MANAGE_METHOD_CONTRACTS } from './contracts-finance-setting-initial-manage.js'
import { FINANCE_SETTING_OPENING_SUPPLIER_AI_CONTRACTS, FINANCE_SETTING_OPENING_SUPPLIER_METHOD_CONTRACTS } from './contracts-finance-setting-opening-supplier.js'
import { FINANCE_SETTING_FEE_PURPOSE_AI_CONTRACTS, FINANCE_SETTING_FEE_PURPOSE_METHOD_CONTRACTS } from './contracts-finance-setting-fee-purpose.js'
import { FINANCE_SETTING_INVENTORY_ACCOUNT_AI_CONTRACTS, FINANCE_SETTING_INVENTORY_ACCOUNT_METHOD_CONTRACTS } from './contracts-finance-setting-inventory-account.js'
import { FINANCE_SETTING_LIVESTOCK_AMORTIZATION_AI_CONTRACTS, FINANCE_SETTING_LIVESTOCK_AMORTIZATION_METHOD_CONTRACTS } from './contracts-finance-setting-livestock-amortization.js'
import { FINANCE_SETTING_SETTLEMENT_SETTING_AI_CONTRACTS, FINANCE_SETTING_SETTLEMENT_SETTING_METHOD_CONTRACTS } from './contracts-finance-setting-settlement-setting.js'
import { FINANCE_SETTING_VOUCHER_TEMPLATES_AI_CONTRACTS, FINANCE_SETTING_VOUCHER_TEMPLATES_METHOD_CONTRACTS } from './contracts-finance-setting-voucher-templates.js'
import { FUND_SALARY_FUND_COST_AI_CONTRACTS, FUND_SALARY_FUND_COST_METHOD_CONTRACTS } from './contracts-fund-salary-fund-costs.js'
import { FUND_SALARY_FUND_PROCESS_AI_CONTRACTS, FUND_SALARY_FUND_PROCESS_METHOD_CONTRACTS } from './contracts-fund-salary-fund-process.js'
import { INSURANCE_SALARY_INSURANCE_COST_AI_CONTRACTS, INSURANCE_SALARY_INSURANCE_COST_METHOD_CONTRACTS } from './contracts-insurance-salary-insurance-costs.js'
import { INSURANCE_SALARY_INSURANCE_PROCESS_AI_CONTRACTS, INSURANCE_SALARY_INSURANCE_PROCESS_METHOD_CONTRACTS } from './contracts-insurance-salary-insurance-process.js'
import { MANAGE_COST_CENTER_AI_CONTRACTS, MANAGE_COST_CENTER_METHOD_CONTRACTS } from './contracts-manage-cost-center.js'
import { SALARY_ITEM_AI_CONTRACTS, SALARY_ITEM_METHOD_CONTRACTS } from './contracts-salary-item.js'
import { INVENTORY_ORGANIZATION_CONFIG_AI_CONTRACTS, INVENTORY_ORGANIZATION_CONFIG_METHOD_CONTRACTS } from './contracts-inventory-organization-config.js'
import { INVENTORY_ASSET_DEPRECIATION_CONFIG_AI_CONTRACTS, INVENTORY_ASSET_DEPRECIATION_CONFIG_METHOD_CONTRACTS } from './contracts-inventory-asset-depreciation-config.js'
import { INVENTORY_STOCK_RULE_AI_CONTRACTS, INVENTORY_STOCK_RULE_METHOD_CONTRACTS } from './contracts-inventory-stock-rule.js'
import { INVENTORY_STOCK_LOCATION_AI_CONTRACTS, INVENTORY_STOCK_LOCATION_METHOD_CONTRACTS } from './contracts-inventory-stock-location.js'
import { CONTRACT_SUPPORT_CONTRACTS } from './contracts-support.js'
import { AI_MODEL_CONTRACTS, AI_MODEL_METHOD_CONTRACTS } from './contracts-ai-model.js'
import { MODEL_USAGE_CONTRACTS, MODEL_USAGE_METHOD_CONTRACTS } from './contracts-model-usage.js'
import { CHAT_CONTRACTS, CHAT_METHOD_CONTRACTS } from './contracts-chat.js'
import { CONTRACT_CODE_RULE_AI_CONTRACTS, CONTRACT_CODE_RULE_METHOD_CONTRACTS } from './contracts-contract-code-rule.js'
import { CONTRACT_CREATE_AI_CONTRACTS, CONTRACT_CREATE_METHOD_CONTRACTS } from './contracts-contract-create.js'
import type { AiContract } from './ai-contract.js'
import { AI_CORE_CONTRACTS, AI_CORE_METHOD_CONTRACTS } from './contracts-ai-core.js'
import { BASE_AI_CONTRACTS, BASE_METHOD_CONTRACTS } from './contracts-base.js'
import { WORKFLOW_AI_CONTRACTS, WORKFLOW_METHOD_CONTRACTS } from './contracts-workflow.js'
import { AI_PROMPT_CONTRACTS, AI_PROMPT_METHOD_CONTRACTS } from './contracts-ai-prompt.js'
import { BUSINESS_AI_CONTRACTS, BUSINESS_METHOD_CONTRACTS } from './contracts-business.js'
import { COMPANY_POLICY_AI_CONTRACTS, COMPANY_POLICY_METHOD_CONTRACTS } from './contracts-company-policy.js'
import { INSTITUTION_TYPE_AI_CONTRACTS, INSTITUTION_TYPE_METHOD_CONTRACTS } from './contracts-institution-type.js'
import { SALARY_PACKAGE_AI_CONTRACTS, SALARY_PACKAGE_METHOD_CONTRACTS } from './contracts-salary-package.js'
import { INVENTORY_APPROVAL_CONFIG_AI_CONTRACTS, INVENTORY_APPROVAL_CONFIG_METHOD_CONTRACTS } from './contracts-inventory-approval-config.js'
import { INVENTORY_ASSET_STOCKTAKING_CONFIG_AI_CONTRACTS, INVENTORY_ASSET_STOCKTAKING_CONFIG_METHOD_CONTRACTS } from './contracts-inventory-asset-stocktaking-config.js'
import { INVENTORY_ASSET_BATCH_CONFIG_AI_CONTRACTS, INVENTORY_ASSET_BATCH_CONFIG_METHOD_CONTRACTS } from './contracts-inventory-asset-batch-config.js'
import { INVENTORY_VALUATION_AI_CONTRACTS, INVENTORY_VALUATION_METHOD_CONTRACTS } from './contracts-inventory-valuation.js'
import { PLATFORM_RULE_MANAGEMENT_AI_CONTRACTS, PLATFORM_RULE_MANAGEMENT_METHOD_CONTRACTS } from './contracts-platform-rule-management.js'
import { HR_POST_SETTING_AI_CONTRACTS, HR_POST_SETTING_METHOD_CONTRACTS } from './contracts-hr-post-setting.js'
import { PRODUCT_HIGH_PRODUCTION_USAGE_AI_CONTRACTS, PRODUCT_HIGH_PRODUCTION_USAGE_METHOD_CONTRACTS } from './contracts-product-high-production-usage.js'
import { PRODUCT_STABLE_PRODUCTION_USAGE_AI_CONTRACTS, PRODUCT_STABLE_PRODUCTION_USAGE_METHOD_CONTRACTS } from './contracts-product-stable-production-usage.js'
import { PRODUCT_PREVENTION_USAGE_ANALYSIS_AI_CONTRACTS, PRODUCT_PREVENTION_USAGE_ANALYSIS_METHOD_CONTRACTS } from './contracts-product-prevention-usage-analysis.js'
import { PRODUCT_USER_ANALYSIS_AI_CONTRACTS, PRODUCT_USER_ANALYSIS_METHOD_CONTRACTS } from './contracts-product-user-analysis.js'
import { PRODUCT_NOTICE_CONFIG_AI_CONTRACTS, PRODUCT_NOTICE_CONFIG_METHOD_CONTRACTS } from './contracts-product-notice-config.js'
import { PRODUCT_PROGRAM_LIBRARY_AI_CONTRACTS, PRODUCT_PROGRAM_LIBRARY_METHOD_CONTRACTS } from './contracts-product-program-library.js'
import { PRODUCT_SETTING_MATERIAL_AI_CONTRACTS, PRODUCT_SETTING_MATERIAL_METHOD_CONTRACTS } from './contracts-product-setting-material.js'
import { PRODUCT_SETTING_MEDICINE_AI_CONTRACTS, PRODUCT_SETTING_MEDICINE_METHOD_CONTRACTS } from './contracts-product-setting-medicine.js'
import { PRODUCT_SETTING_USER_DICT_AI_CONTRACTS, PRODUCT_SETTING_USER_DICT_METHOD_CONTRACTS } from './contracts-product-setting-user-dict.js'
import { PRODUCT_SETTING_VACCINE_AI_CONTRACTS, PRODUCT_SETTING_VACCINE_METHOD_CONTRACTS } from './contracts-product-setting-vaccine.js'
import { PRODUCT_SETTING_ANTIBODY_AI_CONTRACTS, PRODUCT_SETTING_ANTIBODY_METHOD_CONTRACTS } from './contracts-product-setting-antibody.js'
import { PRODUCT_SETTING_CHICKEN_PRODUCTION_AI_CONTRACTS, PRODUCT_SETTING_CHICKEN_PRODUCTION_METHOD_CONTRACTS } from './contracts-product-setting-chicken-production.js'
import { PRODUCT_SETTING_EGG_STANDARD_AGE_STAGE_AI_CONTRACTS, PRODUCT_SETTING_EGG_STANDARD_AGE_STAGE_METHOD_CONTRACTS } from './contracts-product-setting-egg-standard-age-stage.js'
import { PRODUCT_SETTING_EPIDEMIC_PREVENTION_COST_AI_CONTRACTS, PRODUCT_SETTING_EPIDEMIC_PREVENTION_COST_METHOD_CONTRACTS } from './contracts-product-setting-epidemic-prevention-cost.js'
import { PRODUCT_SETTING_HATCH_ANNUAL_MONTHLY_AI_CONTRACTS, PRODUCT_SETTING_HATCH_ANNUAL_MONTHLY_METHOD_CONTRACTS } from './contracts-product-setting-hatch-annual-monthly.js'
import { PRODUCT_SETTING_STANDARD_BROILER_AI_CONTRACTS, PRODUCT_SETTING_STANDARD_BROILER_METHOD_CONTRACTS } from './contracts-product-setting-standard-broiler.js'
import { PRODUCT_SETTING_STANDARD_FLOCK_WEEK_AI_CONTRACTS, PRODUCT_SETTING_STANDARD_FLOCK_WEEK_METHOD_CONTRACTS } from './contracts-product-setting-standard-flock-week.js'
import { PRODUCT_SETTING_STANDARD_FLOCK_AI_CONTRACTS, PRODUCT_SETTING_STANDARD_FLOCK_METHOD_CONTRACTS } from './contracts-product-setting-standard-flock.js'
import { PRODUCT_SETTING_STANDARD_HATCH_AI_CONTRACTS, PRODUCT_SETTING_STANDARD_HATCH_METHOD_CONTRACTS } from './contracts-product-setting-standard-hatch.js'
import { PRODUCT_SETTING_BATCH_STATUS_AI_CONTRACTS, PRODUCT_SETTING_BATCH_STATUS_METHOD_CONTRACTS } from './contracts-product-setting-batch-status.js'
import { PRODUCT_SETTING_CONFIGURE_AI_CONTRACTS, PRODUCT_SETTING_CONFIGURE_METHOD_CONTRACTS } from './contracts-product-setting-configure.js'
import { PRODUCT_SETTING_DAY_LIQUIDATION_AI_CONTRACTS, PRODUCT_SETTING_DAY_LIQUIDATION_METHOD_CONTRACTS } from './contracts-product-setting-day-liquidation.js'
import { PRODUCT_SETTING_FUNCTION_USE_AI_CONTRACTS, PRODUCT_SETTING_FUNCTION_USE_METHOD_CONTRACTS } from './contracts-product-setting-function-use.js'
import { PRODUCT_SETTING_MATERIAL_MASTER_AI_CONTRACTS, PRODUCT_SETTING_MATERIAL_MASTER_METHOD_CONTRACTS } from './contracts-product-setting-material-master.js'
import { PRODUCT_SETTING_TENANT_LOG_AI_CONTRACTS, PRODUCT_SETTING_TENANT_LOG_METHOD_CONTRACTS } from './contracts-product-setting-tenant-log.js'
import { PRODUCT_SETTING_HATCH_MANAGE_LIB_AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_LIB_METHOD_CONTRACTS } from './contracts-product-setting-hatch-manage-lib.js'
import { PRODUCT_BUSINESS_AGE_DIVISION_AI_CONTRACTS, PRODUCT_BUSINESS_AGE_DIVISION_METHOD_CONTRACTS } from './contracts-product-business-age-division.js'
import { PRODUCT_BUSINESS_DATA_RETRANSMIT_AI_CONTRACTS, PRODUCT_BUSINESS_DATA_RETRANSMIT_METHOD_CONTRACTS } from './contracts-product-business-data-retransmit.js'
import { PRODUCT_BUSINESS_SETUP_MATERIAL_CODE_AI_CONTRACTS, PRODUCT_BUSINESS_SETUP_MATERIAL_CODE_METHOD_CONTRACTS } from './contracts-product-business-setup-material-code.js'
import { PRODUCT_HATCHERY_LIB_AI_CONTRACTS, PRODUCT_HATCHERY_LIB_METHOD_CONTRACTS } from './contracts-product-hatchery-lib.js'
import { PRODUCT_HATCHERY_METHOD_AI_CONTRACTS, PRODUCT_HATCHERY_METHOD_METHOD_CONTRACTS } from './contracts-product-hatchery-method.js'
import { PRODUCT_HATCHERY_METHOD_LIB_AI_CONTRACTS, PRODUCT_HATCHERY_METHOD_LIB_METHOD_CONTRACTS } from './contracts-product-hatchery-method-lib.js'
import { PRODUCT_HATCHERY_METHOD_LIB_INDICATOR_AI_CONTRACTS, PRODUCT_HATCHERY_METHOD_LIB_INDICATOR_METHOD_CONTRACTS } from './contracts-product-hatchery-method-lib-indicator.js'
import { PRODUCT_HATCHERY_STANDARD_INDICATOR_AI_CONTRACTS, PRODUCT_HATCHERY_STANDARD_INDICATOR_METHOD_CONTRACTS } from './contracts-product-hatchery-standard-indicator.js'
import { PRODUCT_HATCHERY_UNIT_AI_CONTRACTS, PRODUCT_HATCHERY_UNIT_METHOD_CONTRACTS } from './contracts-product-hatchery-unit.js'
import { PRODUCT_PLAN_PREVIEW_AI_CONTRACTS, PRODUCT_PLAN_PREVIEW_METHOD_CONTRACTS } from './contracts-product-plan-preview.js'
import { SALE_CUSTOM_QR_AI_CONTRACTS, SALE_CUSTOM_QR_METHOD_CONTRACTS } from './contracts-sale-custom-qr.js'
import { SETTING_DICT_PLATFORM_FINANCE_AI_CONTRACTS, SETTING_DICT_PLATFORM_FINANCE_METHOD_CONTRACTS } from './contracts-setting-dict-platform-finance.js'
import { SETTING_DICT_PLATFORM_COMMON_AI_CONTRACTS, SETTING_DICT_PLATFORM_COMMON_METHOD_CONTRACTS } from './contracts-setting-dict-platform-common.js'
import { SETTING_DICT_PLATFORM_HR_AI_CONTRACTS, SETTING_DICT_PLATFORM_HR_METHOD_CONTRACTS } from './contracts-setting-dict-platform-hr.js'
import { SETTING_DICT_PLATFORM_MATERIAL_AI_CONTRACTS, SETTING_DICT_PLATFORM_MATERIAL_METHOD_CONTRACTS } from './contracts-setting-dict-platform-material.js'
import { SETTING_DICT_PLATFORM_PRODUCT_AI_CONTRACTS, SETTING_DICT_PLATFORM_PRODUCT_METHOD_CONTRACTS } from './contracts-setting-dict-platform-product.js'
import { SETTING_DICT_PLATFORM_SUPPLY_AI_CONTRACTS, SETTING_DICT_PLATFORM_SUPPLY_METHOD_CONTRACTS } from './contracts-setting-dict-platform-supply.js'
import { SETTING_DICT_PLATFORM_SALE_AI_CONTRACTS, SETTING_DICT_PLATFORM_SALE_METHOD_CONTRACTS } from './contracts-setting-dict-platform-sale.js'
import { SALE_VISIT_RECOMMEND_SETTING_AI_CONTRACTS, SALE_VISIT_RECOMMEND_SETTING_METHOD_CONTRACTS } from './contracts-sale-visit-recommend-setting.js'
import { PRODUCT_SETTING_HATCH_MANAGE_METHOD_LIB_AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_METHOD_LIB_METHOD_CONTRACTS } from './contracts-product-setting-hatch-manage-method-lib.js'
import { PRODUCT_SETTING_HATCH_METHOD_LIB_INDICATOR_AI_CONTRACTS, PRODUCT_SETTING_HATCH_METHOD_LIB_INDICATOR_METHOD_CONTRACTS } from './contracts-product-setting-hatch-method-lib-indicator.js'
import { PRODUCT_SETTING_HATCH_MANAGE_METHOD_AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_METHOD_METHOD_CONTRACTS } from './contracts-product-setting-hatch-manage-method.js'
import { PRODUCT_SETTING_HATCH_MANAGE_SEASON_AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_SEASON_METHOD_CONTRACTS } from './contracts-product-setting-hatch-manage-season.js'
import { PRODUCT_SETTING_HATCH_MANAGE_UNIT_AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_UNIT_METHOD_CONTRACTS } from './contracts-product-setting-hatch-manage-unit.js'
import { PRODUCT_SETTING_HATCH_MANAGE_VARIETY_AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_VARIETY_METHOD_CONTRACTS } from './contracts-product-setting-hatch-manage-variety.js'
import { PRODUCT_SETTING_INDICATOR_LIB_AI_CONTRACTS, PRODUCT_SETTING_INDICATOR_LIB_METHOD_CONTRACTS } from './contracts-product-setting-indicator-lib.js'
import { PRODUCT_SETTING_METHOD_LIB_AI_CONTRACTS, PRODUCT_SETTING_METHOD_LIB_METHOD_CONTRACTS } from './contracts-product-setting-method-lib.js'
import { PRODUCT_SETTING_SEASON_AI_CONTRACTS, PRODUCT_SETTING_SEASON_METHOD_CONTRACTS } from './contracts-product-setting-season.js'
import { HISTORY_ARCHIVE_AI_CONTRACTS, HISTORY_ARCHIVE_METHOD_CONTRACTS } from './contracts-history-archive.js'
import { ME_ORGANIZATION_AI_CONTRACTS, ME_ORGANIZATION_METHOD_CONTRACTS } from './contracts-me-organization.js'
import { ME_PERSONAL_AI_CONTRACTS, ME_PERSONAL_METHOD_CONTRACTS } from './contracts-me-personal.js'
import { BATCH_AI_CONTRACTS, BATCH_METHOD_CONTRACTS } from './contracts-batch.js'

/** Explicit registry: never guess output shapes from pagination inputs. */
export const AI_CONTRACTS: Record<string, AiContract> = { ...PORTAL_DEVICE_CONTRACTS, ...HR_POST_TYPE_AI_CONTRACTS, ...ATTENDANCE_SHEET_CONTRACTS, ...HR_ORGANIZATION_TYPE_AI_CONTRACTS, ...HR_ORGANIZATION_PROPERTY_AI_CONTRACTS, ...TECHNOLOGY_PROJECT_TYPE_CONTRACTS, ...FINANCE_ACCOUNTING_PERIOD_AI_CONTRACTS, ...FINANCE_ACCOUNTING_MANAGE_AI_CONTRACTS, ...FINANCE_LEDGER_ACCOUNTS_AI_CONTRACTS, ...FINANCE_SETTING_ACCURACY_AI_CONTRACTS, ...FINANCE_ALLOCATION_INDICATOR_AI_CONTRACTS, ...FINANCE_SETTING_ANNUAL_CARRYFORWARD_AI_CONTRACTS, ...FINANCE_SETTING_CAT_CONFIG_AI_CONTRACTS, ...FINANCE_SETTING_CAT_MAP_AI_CONTRACTS, ...FINANCE_SETTING_DATE_CONFIG_AI_CONTRACTS, ...FINANCE_SETTING_MONTHLY_INCOME_TIME_CONFIG_AI_CONTRACTS, ...FINANCE_SETTING_PROJECT_CONTRACTS, ...FINANCE_SETTING_RECEIVING_ACCOUNT_AI_CONTRACTS, ...FINANCE_SETTING_RELATED_PARTY_SETTLEMENT_ACCOUNT_AI_CONTRACTS, ...FINANCE_SETTING_SALE_ALLOCATION_COEFFICIENT_AI_CONTRACTS, ...FINANCE_SETTING_ALLOCATION_RULES_AI_CONTRACTS, ...FINANCE_SETTING_COST_CENTER_AI_CONTRACTS, ...FINANCE_SETTING_EMPLOYEE_LOAN_AMOUNT_AI_CONTRACTS, ...FINANCE_SETTING_FEE_PURPOSE_AI_CONTRACTS, ...FINANCE_SETTING_INVENTORY_ACCOUNT_AI_CONTRACTS, ...FINANCE_SETTING_LIVESTOCK_AMORTIZATION_AI_CONTRACTS, ...FINANCE_SETTING_SETTLEMENT_SETTING_AI_CONTRACTS, ...FINANCE_SETTING_VOUCHER_TEMPLATES_AI_CONTRACTS, ...FUND_SALARY_FUND_COST_AI_CONTRACTS, ...FUND_SALARY_FUND_PROCESS_AI_CONTRACTS, ...INSURANCE_SALARY_INSURANCE_COST_AI_CONTRACTS, ...INSURANCE_SALARY_INSURANCE_PROCESS_AI_CONTRACTS, ...MANAGE_COST_CENTER_AI_CONTRACTS, ...SALARY_ITEM_AI_CONTRACTS, ...SALARY_PACKAGE_AI_CONTRACTS, ...INVENTORY_APPROVAL_CONFIG_AI_CONTRACTS, ...INVENTORY_ASSET_STOCKTAKING_CONFIG_AI_CONTRACTS, ...INVENTORY_ASSET_BATCH_CONFIG_AI_CONTRACTS, ...INVENTORY_VALUATION_AI_CONTRACTS, ...PLATFORM_RULE_MANAGEMENT_AI_CONTRACTS, ...HR_POST_SETTING_AI_CONTRACTS, ...PRODUCT_HIGH_PRODUCTION_USAGE_AI_CONTRACTS, ...PRODUCT_STABLE_PRODUCTION_USAGE_AI_CONTRACTS, ...PRODUCT_PREVENTION_USAGE_ANALYSIS_AI_CONTRACTS, ...PRODUCT_USER_ANALYSIS_AI_CONTRACTS, ...PRODUCT_NOTICE_CONFIG_AI_CONTRACTS, ...PRODUCT_PROGRAM_LIBRARY_AI_CONTRACTS, ...PRODUCT_SETTING_MATERIAL_AI_CONTRACTS, ...PRODUCT_SETTING_MEDICINE_AI_CONTRACTS, ...PRODUCT_SETTING_USER_DICT_AI_CONTRACTS, ...PRODUCT_SETTING_VACCINE_AI_CONTRACTS, ...PRODUCT_SETTING_BATCH_STATUS_AI_CONTRACTS, ...PRODUCT_SETTING_CONFIGURE_AI_CONTRACTS, ...PRODUCT_SETTING_DAY_LIQUIDATION_AI_CONTRACTS, ...PRODUCT_SETTING_FUNCTION_USE_AI_CONTRACTS, ...PRODUCT_SETTING_MATERIAL_MASTER_AI_CONTRACTS, ...PRODUCT_SETTING_TENANT_LOG_AI_CONTRACTS, ...PRODUCT_SETTING_HATCH_MANAGE_LIB_AI_CONTRACTS, ...INVENTORY_ORGANIZATION_CONFIG_AI_CONTRACTS, ...INVENTORY_ASSET_DEPRECIATION_CONFIG_AI_CONTRACTS, ...INVENTORY_STOCK_RULE_AI_CONTRACTS, ...INVENTORY_STOCK_LOCATION_AI_CONTRACTS, ...CONTRACT_SUPPORT_CONTRACTS, ...AI_MODEL_CONTRACTS, ...MODEL_USAGE_CONTRACTS, ...AI_CORE_CONTRACTS, ...BASE_AI_CONTRACTS, ...WORKFLOW_AI_CONTRACTS, ...AI_PROMPT_CONTRACTS, ...CHAT_CONTRACTS, ...CONTRACT_CODE_RULE_AI_CONTRACTS, ...CONTRACT_CREATE_AI_CONTRACTS, ...BUSINESS_AI_CONTRACTS, ...COMPANY_POLICY_AI_CONTRACTS, ...INSTITUTION_TYPE_AI_CONTRACTS }
export const METHOD_CONTRACTS: Record<string, AiContract> = { ...HR_POST_TYPE_METHOD_CONTRACTS, ...ATTENDANCE_SHEET_METHOD_CONTRACTS, ...HR_ORGANIZATION_TYPE_METHOD_CONTRACTS, ...HR_ORGANIZATION_PROPERTY_METHOD_CONTRACTS, ...TECHNOLOGY_PROJECT_TYPE_METHOD_CONTRACTS, ...FINANCE_ACCOUNTING_PERIOD_METHOD_CONTRACTS, ...FINANCE_ACCOUNTING_MANAGE_METHOD_CONTRACTS, ...FINANCE_LEDGER_ACCOUNTS_METHOD_CONTRACTS, ...FINANCE_SETTING_ACCURACY_METHOD_CONTRACTS, ...FINANCE_ALLOCATION_INDICATOR_METHOD_CONTRACTS, ...FINANCE_SETTING_ANNUAL_CARRYFORWARD_METHOD_CONTRACTS, ...FINANCE_SETTING_CAT_CONFIG_METHOD_CONTRACTS, ...FINANCE_SETTING_CAT_MAP_METHOD_CONTRACTS, ...FINANCE_SETTING_DATE_CONFIG_METHOD_CONTRACTS, ...FINANCE_SETTING_MONTHLY_INCOME_TIME_CONFIG_METHOD_CONTRACTS, ...FINANCE_SETTING_PROJECT_METHOD_CONTRACTS, ...FINANCE_SETTING_RECEIVING_ACCOUNT_METHOD_CONTRACTS, ...FINANCE_SETTING_RELATED_PARTY_SETTLEMENT_ACCOUNT_METHOD_CONTRACTS, ...FINANCE_SETTING_SALE_ALLOCATION_COEFFICIENT_METHOD_CONTRACTS, ...FINANCE_SETTING_ALLOCATION_RULES_METHOD_CONTRACTS, ...FINANCE_SETTING_COST_CENTER_METHOD_CONTRACTS, ...FINANCE_SETTING_EMPLOYEE_LOAN_AMOUNT_METHOD_CONTRACTS, ...FINANCE_SETTING_FEE_PURPOSE_METHOD_CONTRACTS, ...FINANCE_SETTING_INVENTORY_ACCOUNT_METHOD_CONTRACTS, ...FINANCE_SETTING_LIVESTOCK_AMORTIZATION_METHOD_CONTRACTS, ...FINANCE_SETTING_SETTLEMENT_SETTING_METHOD_CONTRACTS, ...FINANCE_SETTING_VOUCHER_TEMPLATES_METHOD_CONTRACTS, ...FUND_SALARY_FUND_COST_METHOD_CONTRACTS, ...FUND_SALARY_FUND_PROCESS_METHOD_CONTRACTS, ...INSURANCE_SALARY_INSURANCE_COST_METHOD_CONTRACTS, ...INSURANCE_SALARY_INSURANCE_PROCESS_METHOD_CONTRACTS, ...MANAGE_COST_CENTER_METHOD_CONTRACTS, ...SALARY_ITEM_METHOD_CONTRACTS, ...SALARY_PACKAGE_METHOD_CONTRACTS, ...INVENTORY_APPROVAL_CONFIG_METHOD_CONTRACTS, ...INVENTORY_ASSET_STOCKTAKING_CONFIG_METHOD_CONTRACTS, ...INVENTORY_ASSET_BATCH_CONFIG_METHOD_CONTRACTS, ...INVENTORY_VALUATION_METHOD_CONTRACTS, ...PLATFORM_RULE_MANAGEMENT_METHOD_CONTRACTS, ...HR_POST_SETTING_METHOD_CONTRACTS, ...PRODUCT_HIGH_PRODUCTION_USAGE_METHOD_CONTRACTS, ...PRODUCT_STABLE_PRODUCTION_USAGE_METHOD_CONTRACTS, ...PRODUCT_PREVENTION_USAGE_ANALYSIS_METHOD_CONTRACTS, ...PRODUCT_USER_ANALYSIS_METHOD_CONTRACTS, ...PRODUCT_NOTICE_CONFIG_METHOD_CONTRACTS, ...PRODUCT_PROGRAM_LIBRARY_METHOD_CONTRACTS, ...PRODUCT_SETTING_MATERIAL_METHOD_CONTRACTS, ...PRODUCT_SETTING_MEDICINE_METHOD_CONTRACTS, ...PRODUCT_SETTING_USER_DICT_METHOD_CONTRACTS, ...PRODUCT_SETTING_VACCINE_METHOD_CONTRACTS, ...PRODUCT_SETTING_BATCH_STATUS_METHOD_CONTRACTS, ...PRODUCT_SETTING_CONFIGURE_METHOD_CONTRACTS, ...PRODUCT_SETTING_DAY_LIQUIDATION_METHOD_CONTRACTS, ...PRODUCT_SETTING_FUNCTION_USE_METHOD_CONTRACTS, ...PRODUCT_SETTING_MATERIAL_MASTER_METHOD_CONTRACTS, ...PRODUCT_SETTING_TENANT_LOG_METHOD_CONTRACTS, ...PRODUCT_SETTING_HATCH_MANAGE_LIB_METHOD_CONTRACTS, ...INVENTORY_ORGANIZATION_CONFIG_METHOD_CONTRACTS, ...INVENTORY_ASSET_DEPRECIATION_CONFIG_METHOD_CONTRACTS, ...INVENTORY_STOCK_RULE_METHOD_CONTRACTS, ...INVENTORY_STOCK_LOCATION_METHOD_CONTRACTS, ...AI_MODEL_METHOD_CONTRACTS, ...MODEL_USAGE_METHOD_CONTRACTS, ...BASE_METHOD_CONTRACTS, ...AI_CORE_METHOD_CONTRACTS, ...WORKFLOW_METHOD_CONTRACTS, ...AI_PROMPT_METHOD_CONTRACTS, ...CHAT_METHOD_CONTRACTS, ...CONTRACT_CODE_RULE_METHOD_CONTRACTS, ...CONTRACT_CREATE_METHOD_CONTRACTS, ...BUSINESS_METHOD_CONTRACTS, ...COMPANY_POLICY_METHOD_CONTRACTS, ...INSTITUTION_TYPE_METHOD_CONTRACTS }

Object.assign(AI_CONTRACTS, PRODUCT_BUSINESS_AGE_DIVISION_AI_CONTRACTS, PRODUCT_BUSINESS_DATA_RETRANSMIT_AI_CONTRACTS, PRODUCT_BUSINESS_SETUP_MATERIAL_CODE_AI_CONTRACTS, PRODUCT_HATCHERY_LIB_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_BUSINESS_AGE_DIVISION_METHOD_CONTRACTS, PRODUCT_BUSINESS_DATA_RETRANSMIT_METHOD_CONTRACTS, PRODUCT_BUSINESS_SETUP_MATERIAL_CODE_METHOD_CONTRACTS, PRODUCT_HATCHERY_LIB_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, TECHNOLOGY_TYPE_TEMPLATE_MAPPING_CONTRACTS)
Object.assign(METHOD_CONTRACTS, TECHNOLOGY_TYPE_TEMPLATE_MAPPING_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, SETTING_ENTERPRISE_USAGE_AI_CONTRACTS, SETTING_SENSITIVE_ACTION_AI_CONTRACTS, SETTING_TOKEN_ALLOCATION_AI_CONTRACTS, TECHNOLOGY_SETTING_TEMPLATE_BASE_CONTRACTS, TECHNOLOGY_SETTING_TEMPLATE_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, SETTING_ENTERPRISE_USAGE_METHOD_CONTRACTS, SETTING_SENSITIVE_ACTION_METHOD_CONTRACTS, SETTING_TOKEN_ALLOCATION_METHOD_CONTRACTS, TECHNOLOGY_SETTING_TEMPLATE_BASE_METHOD_CONTRACTS, TECHNOLOGY_SETTING_TEMPLATE_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_HATCHERY_METHOD_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_HATCHERY_METHOD_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_HATCHERY_METHOD_LIB_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_HATCHERY_METHOD_LIB_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_HATCHERY_METHOD_LIB_INDICATOR_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_HATCHERY_METHOD_LIB_INDICATOR_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_HATCHERY_STANDARD_INDICATOR_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_HATCHERY_STANDARD_INDICATOR_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_HATCHERY_UNIT_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_HATCHERY_UNIT_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_PLAN_PREVIEW_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_PLAN_PREVIEW_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, SALE_CUSTOM_QR_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, SALE_CUSTOM_QR_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, SETTING_DICT_PLATFORM_FINANCE_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, SETTING_DICT_PLATFORM_FINANCE_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, SETTING_DICT_PLATFORM_COMMON_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, SETTING_DICT_PLATFORM_COMMON_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, SETTING_DICT_PLATFORM_HR_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, SETTING_DICT_PLATFORM_HR_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, SETTING_DICT_PLATFORM_MATERIAL_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, SETTING_DICT_PLATFORM_MATERIAL_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, SETTING_DICT_PLATFORM_PRODUCT_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, SETTING_DICT_PLATFORM_PRODUCT_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, SETTING_DICT_PLATFORM_SUPPLY_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, SETTING_DICT_PLATFORM_SUPPLY_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, SETTING_DICT_PLATFORM_SALE_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, SETTING_DICT_PLATFORM_SALE_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, SALE_VISIT_RECOMMEND_SETTING_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, SALE_VISIT_RECOMMEND_SETTING_METHOD_CONTRACTS)

Object.assign(AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_METHOD_LIB_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_METHOD_LIB_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_HATCH_METHOD_LIB_INDICATOR_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_HATCH_METHOD_LIB_INDICATOR_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, FINANCE_SETTING_INITIAL_MANAGE_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, FINANCE_SETTING_INITIAL_MANAGE_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, FINANCE_SETTING_OPENING_SUPPLIER_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, FINANCE_SETTING_OPENING_SUPPLIER_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_METHOD_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_METHOD_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_SEASON_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_SEASON_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_UNIT_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_UNIT_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_VARIETY_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_HATCH_MANAGE_VARIETY_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_INDICATOR_LIB_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_INDICATOR_LIB_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_METHOD_LIB_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_METHOD_LIB_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_SEASON_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_SEASON_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, ME_ORGANIZATION_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, ME_ORGANIZATION_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, ME_PERSONAL_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, ME_PERSONAL_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_ANTIBODY_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_ANTIBODY_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_CHICKEN_PRODUCTION_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_CHICKEN_PRODUCTION_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_EGG_STANDARD_AGE_STAGE_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_EGG_STANDARD_AGE_STAGE_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_EPIDEMIC_PREVENTION_COST_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_EPIDEMIC_PREVENTION_COST_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_HATCH_ANNUAL_MONTHLY_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_HATCH_ANNUAL_MONTHLY_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_STANDARD_BROILER_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_STANDARD_BROILER_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_STANDARD_FLOCK_WEEK_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_STANDARD_FLOCK_WEEK_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_STANDARD_FLOCK_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_STANDARD_FLOCK_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, PRODUCT_SETTING_STANDARD_HATCH_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, PRODUCT_SETTING_STANDARD_HATCH_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, HISTORY_ARCHIVE_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, HISTORY_ARCHIVE_METHOD_CONTRACTS)
Object.assign(AI_CONTRACTS, BATCH_AI_CONTRACTS)
Object.assign(METHOD_CONTRACTS, BATCH_METHOD_CONTRACTS)
