import { ALL_CAPABILITY_DEFINITIONS } from '../capabilities/index.js'
import type { AiContract, AiField, AiParameter } from './ai-contract.js'
import { contractSupportCapabilities, CONTRACT_SUPPORT_METHODS } from '../capabilities/contract-support.js'
const field=(path:string,type:string,meaning:string,extra:Partial<AiField>={}):AiField=>({path,type,meaning,optional:false,nullable:false,...extra})
const param=(meaning:string,source:string,extra:Partial<AiParameter>={}):AiParameter=>({meaning,source,...extra})
const evidence:AiContract['evidence']=[{source:'src/capabilities/contract-support.ts:createContractSupport',kind:'implementation',note:'请求、keyword校验、白名单归一化、限量及无写行为'},{source:'web@test/portal/main:d3cf56bdc76c73c5eb9252be84b9b39b3900b48e',kind:'reference',note:'各候选控件与下游字段映射；页面级范围由SDK回调绑定，不以合成页面猜模块'},{source:'Java@test/test:dcb3f360194e63c33cfd7ef9df4360355ff13533',kind:'reference',note:'组织/角色/岗位/职务/分类及财务Controller、DTO与SQL复核；智慧蛋鸡是外部系统，仅前端调用证据'},{source:'test/contract-support.test.ts',kind:'test',note:'离线手写夹具验证请求、归一化、拒绝空keyword及实际describe输出；未发真实网络请求'}]
const searchInputs:Record<string,AiParameter>={keyword:param('名称关键字；SDK去首尾空白、1至100字；禁止空串取全量','先从用户意图获取名称片段',{type:'string',required:true,constraints:['keyword为空或超过100字时调用前拒绝，不发请求']}),limit:param('SDK本地筛选后最多返回条数','调用方按候选歧义设置',{type:'integer',required:false,default:'20',omitted:'使用20',constraints:['1至100整数，非法值调用前拒绝']})}
const candidateFields:AiField[]=[field('$','object','名称候选切片，不是后端原始包络'),field('list','array','已匹配候选，最多limit条'),field('list[]','object','同一实体的标识与展示信息'),field('list[].id','string','真实候选实体ID，SDK只做字符串化，不能与code或其他域ID互换'),field('list[].name','string','展示名称'),field('list[].code','string','来源节点code；接口无code为null',{nullable:true,nullMeaning:'本接口未提供编码，不用name生成编码'}),field('list[].parentId','string','本树上级ID；平面清单或根无上级为null',{nullable:true,nullMeaning:'根节点或本接口不提供上级'}),field('list[].path','array','当前响应树中从根到本节点的路径；平面清单只有自身，不能推断完整组织链'),field('list[].path[]','object','路径上的一个节点'),field('list[].path[].id','string','路径节点ID，只用于消歧展示'),field('list[].path[].name','string','路径节点显示名'),field('list[].hasChildren','boolean','原始候选树是否存在子节点；平面候选恒false'),field('list[].selectable','boolean','候选是否允许选择；组织isSelected=1映射false，不能将这个标记反读'),field('total','integer','对本次完整响应做keyword过滤后的匹配数，不是全租户实体总数'),field('limit','integer','实际使用的本地返回上限'),field('truncated','boolean','匹配数大于limit，尚有匹配项未返回')]
const out=():AiContract['output']=>({shape:'{ list: Candidate[], total, limit, truncated }',fields:candidateFields.map(f=>({...f})),empty:'list=[]且total=0表示当前接口可见数据在该关键字下无匹配；网络/权限/结构错误会抛出，不能当无数据。truncated=true不代表可忽略其余匹配。'})
function step(capabilityId:string,mapping:Record<string,string>,instruction:string):AiContract['steps'][number]{return{role:'optional',when:'用户选定实际候选且要继续该业务',capabilityId,mapping,instruction}}
function contract(purpose:string,whenToUse:string,boundaries:string[],consume:string[],steps:AiContract['steps'],extra:Partial<AiContract>={}):AiContract{return{purpose,whenToUse,boundaries,effect:'read',prerequisites:['用户会话与租户已绑定；先获取关键字，不从名称猜ID。'],inputs:{...searchInputs},output:out(),consume,steps,completion:'已交付当前关键字和可见范围内候选；用户选定唯一项或已解释无匹配/截断，选择本身不改变业务数据。',failures:['keyword为空/过长或limit非法：本地抛错且不发请求，改用具体名称片段。','请求权限/会话错误：保留请求层错误，核对身份、租户及对应页面权限后才重试，不回退到不同范围的部门候选。','返回结构或关键ID/名称缺失：抛出候选形状错误，停止传递ID；不要将异常改为空数组。'],idempotency:null,evidence,...extra}}
export const CONTRACT_SUPPORT_CONTRACTS:Record<string,AiContract>={}
const C=CONTRACT_SUPPORT_CONTRACTS
C['contract-support-role-organization-search']=contract('在指定绩效或考勤模块范围内搜索当前角色可见组织，返回供组织筛选使用的ID。','绩效orgIdList/organizationCode或考勤排班组织候选；不是基础部门树，也不是智慧蛋鸡课程ID。',['调用GET org/organization/getRoleOrganizationTree；scope决定请求上下文：performance为绩效13，attendance为组织管理11。','后端返回整棵可见树，SDK只本地按名称/编码/路径过滤；keyword不会缩小网络载荷。','绩效organizationCode这一历史参数实际收所选id；不要把返回code误传给它。'],['展示name和path消歧，只选selectable=true节点；多选时收集用户所选id组成数组。','total是匹配数；truncated=true先细化keyword或适度增大limit，不能宣称已列全。'],[step('perf-salary-main-list',{orgIdList:'result.list[].id'},'仅scope=performance：将用户选中的一个或多个id组成orgIdList数组，不自动全选所有匹配。'),step('perf-year-agreement-others-list',{organizationCode:'result.list[].id'},'仅scope=performance：选单个id原样传organizationCode，名称含code不改变它的实体含义。'),step('attendance-team-schedule-save',{organizationIdList:'result.list[].id'},'仅scope=attendance：选中的id组成organizationIdList；先读现有排班并保留其余三类成员，完成其余参数后再保存。')],{inputs:{...searchInputs,scope:param('候选数据范围；performance绩效、attendance组织考勤','后续目标业务能力',{type:'string',required:false,omitted:'performance',default:'performance',options:[{value:'performance',label:'绩效'},{value:'attendance',label:'考勤'}]})}})
C['contract-support-role-organization-new-search']=contract('搜索月度他人协议使用的新角色组织树，保留不可选祖先标识。','填写perf-month-agreement-others-list.organizationCode；当前页面已使用New树。',['GET getRoleOrganizationTreeNew，绩效模块13；不传excludePost/includeFinanceAttr/includeVirtual，与该页面一致。','isSelected=1是不可选择；祖先节点可能只用于显示路径。筛选在SDK本地进行。'],['只将selectable=true的用户所选节点id传递；parentId/path仅帮助定位。'],[step('perf-month-agreement-others-list',{organizationCode:'result.list[].id'},'选定一个允许选择的组织ID传organizationCode，不传code；新树不可选择的祖先不能用于筛选。')])
C['contract-support-role-search']=contract('查询平台系统角色名称候选，为知识空间的指定角色权限取得真实角色ID。','知识权限isAllManager=2时选择角色；不是用户、岗位或部门候选。',['GET sys/role/listByUseSystem固定useSystem=10；按当前用户角色/创建人及租户权限返回，不等于全系统角色清单。','返回平面角色清单；SDK本地keyword筛选限量。'],['展示name，所选id组成authRoleIds；先读取权限底稿再构建完整权限目标。'],[step('ai-knowledge-workspace-set-permission',{authRoleIds:'result.list[].id',isAllManager:'literal:2'},'用户选定角色后将这些id组成authRoleIds数组；节点id来自知识空间列表，审核人及其它权限字段按完整目标填写；此搜索不授予权限。')])
C['contract-support-post-search']=contract('分页搜索真实岗位节点，排除岗位目录文件夹，提供排班postIdList候选。','为考勤组新增岗位范围；职务用duty-search，个人工号用人员候选。',['GET org/hrpost/searchPage固定dataType=2、selection=true；keyword由后端包含匹配，按页读取，绝不全量拉取岗位树。','组织管理模块11；id与postId在真实岗位节点相同，保存按页面使用id；文件夹dataType=1不允许混入。'],['展示name和ancestors帮助同名岗位消歧；status=0未使用/1正在使用是岗位使用状态，不是权限或可选开关。','hasMore=true时页码加1；空高页不代表总量为0。'],[step('attendance-team-schedule-save',{postIdList:'result.list[].id'},'选中的岗位id组成postIdList；先schedule-get保留原组织、职务及人员，不能因本次只选岗位就清空其他范围。')],{inputs:{keyword:searchInputs.keyword!,pageNo:param('服务端页码','调用方分页游标',{type:'integer',required:false,default:'1',omitted:'1',constraints:['1至1000000整数']}),pageSize:param('服务端每页条数','调用方',{type:'integer',required:false,default:'20',omitted:'20',constraints:['1至100整数']})},output:{shape:'{ list: PostCandidate[], total, pageNo, pageSize, hasMore }',fields:[field('$','object','岗位分页候选'),field('list','array','当前页匹配岗位'),field('list[]','object','真实岗位节点，不包含文件夹'),field('list[].id','string','岗位节点ID，用于排班postIdList'),field('list[].name','string','岗位名称'),field('list[].postId','string','当前SQL对dataType=2返回同id的岗位ID',{nullable:true,nullMeaning:'部署未返回此派生字段时仍使用id'}),field('list[].parentId','string','上级目录节点ID',{nullable:true,nullMeaning:'无上级或接口未提供'}),field('list[].status','number','岗位使用状态，不据此判断权限',{nullable:true,nullMeaning:'未提供状态',values:{'0':'未使用','1':'正在使用'}}),field('list[].ancestors','array','根到父级路径，不含本节点'),field('list[].ancestors[]','object','一个祖先节点'),field('list[].ancestors[].id','string','祖先ID，仅用于定位'),field('list[].ancestors[].name','string','祖先名称',{nullable:true,nullMeaning:'不可见祖先可能无名称'}),field('list[].ancestors[].available','boolean','祖先当前是否可见可定位，false不应猜名称'),field('total','integer','后端匹配总岗位数'),field('pageNo','integer','当前请求页码，从1开始'),field('pageSize','integer','当前页大小'),field('hasMore','boolean','pageNo*pageSize小于total，需要下一页')],empty:'list=[]为当前页无候选；total可能仍大于0，此时检查页码。权限/结构失败抛错。'}})
C['contract-support-duty-search']=contract('按名称搜索员工职务，返回排班dutyIdList所需的职务ID。','为考勤组新增职务范围；岗位与职务是不同实体。',['GET org/hrduty/all返回职务清单，SDK把dutyName归一为name并本地筛选限量；组织管理模块11。'],['选择用户指定的职务id；不要把dutyLevelId、岗位ID或人员ID作为职务ID。'],[step('attendance-team-schedule-save',{dutyIdList:'result.list[].id'},'选中职务id组成dutyIdList，先读回完整旧排班并保留未修改类别，再执行整体覆盖保存。')])
C['contract-support-contract-type-search']=contract('搜索contract_type分类树的叶子节点，为合同模板typeId提供可用分类ID。','创建/修改合同模板类型或按分类筛选模板；不是base-dict-get里同名字典的value。',['GET system/category-dict/getChildNodeTree?code=contract_type；合同模板风险防控模块15，按当前租户分类优先、没有时回退平台共享分类。','只返回children为空的叶子；keyword同时匹配叶子名称、code与祖先名称，父分类名称可用于查其下叶子。'],['展示name/path；typeId取叶子id，不取分类code、普通字典value或父分类id。'],[step('contract-template-list',{typeId:'result.list[].id'},'用户选一个叶子id后筛选现有合同模板；创建或修改时同一id填typeId，完整模板内容需独立读取或构造。')])
C['contract-support-learning-course-search']=contract('搜索智慧蛋鸡思想教育课程目录和子内容，取得学习统计lessonId。','学习行为统计需要远端课程/章节候选；不能用本SDKstudy-lesson-list的班课ID替代。',['GET /api/zhdj/studyLessonCatalogue/getChapterTree?type=2，必须使用smart-layer-app实例及其独立baseUrl配置，不能改发Portal平台接口。','按页面change-on-select语义，父课程及子目录均可选；选择路径最后一个节点id作为lessonId。','接口返回全树，SDK本地keyword+limit；没有后端本地Java实现证据，当前字段依据前端明确使用id/name/children。'],['展示完整返回路径区分课程与子内容；hasChildren=true仍可选，不强制仅选叶子。'],[step('study-statistics-learning-summary',{lessonId:'result.list[].id'},'用户选定一个节点id作为lessonId；组织用learning-organization-search另取，不能将路径全部ID传给lessonId。')])
C['contract-support-learning-organization-search']=contract('取得学习统计页面实际组织树并按名称搜索，返回organizationId候选。','与智慧蛋鸡lessonId组合查询学习行为统计。',['GET org/organization/getTree?roleId=空串，复刻该页组件；这是组织树，不能替换为学习班级组织/study-base树。','学习管理模块12；SDK按接口返回全树本地搜索，不对未返回组织作可见性推断。'],['展示name/path，所选节点id进入organizationId；code和外部课程id不是替代值。'],[step('study-statistics-learning-summary',{organizationId:'result.list[].id'},'选定一个组织id传organizationId；保持之前已选的智慧蛋鸡lessonId。')])
C['contract-support-travel-budget-search']=contract('查询费用组织和付款月份下的人员类支出预算明细，为差旅行逐行选择预算。','差旅travelEntryList需要budgetDetailId/budgetDetailNo；不是社会化预算或预算主单ID。',['差旅/simple/finance/form/003不匹配module-type规则，因此本组财务候选不发送该头；不擅自按dashboard财务页加2。','POST finance/spending-budget-person/list只读；差旅控件未设置type，实际默认1（人）。orgId和budgetMonth必须来自本单费用组织与付款日期。','后端按orgId扩展自身及祖先orgIds，返回orgName可能为上级组织；不是严格只属输入组织的预算。','keyword在完整响应上本地匹配明细单号/预算主单号/组织名/业务类型；不会收窄后端网络返回。','金额保持后端数字/十进制字符串；单位元。传applyAmount时请求后端判断并补本地余额检查；查询不占用预算，提交前仍可能变化。'],['选择selectable=true且余额足够的明细；id是明细ID，budgetId是主单ID不能混用。','budgetDetailNo归一自后端detailCode；当前前端直接读budgetDetailNo但后端字段是detailCode，SDK明确做这一转换。','可用余额为null时不宣称金额足够；保留后端disabledReason并核实该行，再准备提交。'],[step('travel-expense-prepare',{'travelEntryList[].budgetDetailId':'result.list[].id','travelEntryList[].budgetDetailNo':'result.list[].budgetDetailNo'},'每个差旅行由用户选定一个明细，将id和budgetDetailNo成对填入同一travelEntryList元素；保留其他字段并按费用单金额核对预算，之后prepare仍不是提交。')],{inputs:{...searchInputs,orgId:param('本差旅单费用承担组织ID','travel-expense-org-options候选中已选组织，与草稿orgId相同',{type:'string | number',required:true}),budgetMonth:param('预计付款日期所在月份','草稿paymentDate取年月',{type:'string',required:true,format:'YYYY-MM；不是时间戳，不涉时区换算'}),applyAmount:param('当前差旅行五项含税预算金额：trafficAmount+foodAmount+housingAmount+otherAmount+inputTaxAmount','同一travelEntryList行trafficAmount+foodAmount+housingAmount+otherAmount+inputTaxAmount五项之和；预算占用含进项税，不能漏inputTaxAmount',{type:'number',required:false,unit:'元',omitted:'不增加申请金额筛选，仍保留后端selectable及非正余额检查',constraints:['SDK要求有限且非负；不要把金额分传为元']})},output:{shape:'{ list: BudgetCandidate[], total, limit, truncated }',fields:[...candidateFields.filter(f=>['$','list','list[]','total','limit','truncated'].includes(f.path)),field('list[].id','string','预算明细ID，来自budgetDetailId，未提供时取id；不能拿budgetId代替'),...Object.entries({budgetDetailNo:'明细单号，由detailCode映射；与id成对传入差旅行',budgetId:'预算主单ID，只用于区分主单，不能填差旅budgetDetailId',budgetNo:'预算主单号',budgetType:'预算类型显示文本',budgetMonth:'预算月份YYYY-MM',orgName:'组织显示名',detail:'预算业务内容分类ID，仅用于说明预算用途',detailType:'预算业务内容类型文本',paymentDate:'预计付款日YYYY-MM-DD，保持后端日期，不跨时区转换',disabledReason:'后端或SDK余额检查导致的不可选原因'}).map(([path,meaning])=>field('list[].'+path,'string',meaning,{nullable:true,nullMeaning:'后端未返回该资料或没有不可选原因'})),...['amount','availableBalance','occupiedAmount'].map(path=>field('list[].'+path,'number | string',path==='amount'?'预算明细金额':path==='availableBalance'?'当前可用余额，优先availableAmount再availableBalance':'已占用金额',{nullable:true,nullMeaning:'本次未取得，不能按0处理',unit:'元'})),field('list[].selectable','boolean','后端非禁止且没有disabledReason/余额不足；不等于已锁定预算')],empty:'空list为该组织月份及keyword无匹配；查询无写入。truncated按本地匹配数说明遗漏。'}})
C['contract-support-revenue-subject-search']=contract('搜索主营业务收入根科目下的所有末级科目，为销售费用关联商品类型提供科目ID和名称。','差旅等费用承担组织属于销售费用时填写relatedRevenueSubjectId/Name。',['GET finance/ledger-accounts/leaf-list固定rootName=主营业务收入；末级以无子节点判定，不固定层级数字。','SDK只输出必要ID/名称/code并本地筛选，不能据候选推断费用组织是否销售费用。'],['所选id/name成对填收入科目及冗余名称；code是科目编码，不是ID。'],[step('travel-expense-prepare',{relatedRevenueSubjectId:'result.list[].id',relatedRevenueSubjectName:'result.list[].name'},'仅费用承担组织为销售费用且用户确定商品类型时，选一条科目；保留其它差旅输入后prepare。')])
C['contract-support-corporation-search']=contract('按名称查询当前租户可用法人，为内部分公司收款选择法人库ID。','差旅payeeInfo的内部收款法人；不是组织树的receivingCompanyId。',['GET org/corporation/getAllLegalPerson?name=keyword；后端SQL筛status=0且is_del=0和当前tenantId，返回可用法人。','keyword传后端名称包含查询后再次本地筛选并限量；不查询法人银行账户，不自动填开户信息。'],['所选法人id/name分别填receivingCorporationId/receivingCorporationName；不能用superOrganizationId替代法人ID。'],[{...step('contract-support-corporation-payee-get',{corporationId:'result.list[].id'},'内部收款分支选定一个法人后读取其开户资料；换法人必须清空历史receivingCompanyId、外部客商payeeId/payeeCode/payeeSourceType及旧银行字段，不能沿用另一法人的账户。只有已核实属于同一法人的账号可复用。'),role:'required',when:'用户要填写或更换内部收款法人'}])
C['contract-support-corporation-payee-get']=contract('按已选法人库ID读取内部收款开户行和账号，供差旅内部公司收款分支回填。','选择或更换内部法人后；查询成功不表示提交或付款。',['GET finance/payee-info/internal-corporation?corporationId=法人库ID，差旅form003上下文不发module-type。','后端只接受未删除且状态可用法人；从该法人用途为收款的账户列表取第一条，接口不提供账户候选列表。','SDK只投影七个已验证字段，并校验返回法人ID与查询一致；不补回历史组织或外部客商字段。'],['保持receivingAccount字符串和前导零；开户行与账号须来自本次同一个法人详情。','更换法人时先清空receivingCompanyId、payeeId、payeeCode、payeeSourceType/sourceType、receivingBankDictValue和旧开户行/账号，再填本次返回的七个字段；不能把旧银行字典值与新银行混合。'],[step('travel-expense-prepare',{'payeeInfo.payeeType':'result.payeeType','payeeInfo.companySubType':'result.companySubType','payeeInfo.receivingCorporationId':'result.receivingCorporationId','payeeInfo.receivingCorporationName':'result.receivingCorporationName','payeeInfo.receivingCompanyName':'result.receivingCompanyName','payeeInfo.receivingBankName':'result.receivingBankName','payeeInfo.receivingAccount':'result.receivingAccount'},'把同一返回对象的七个字段放入payeeInfo；先按消费说明清理旧组织/客商/银行字典字段，并保留差旅其它必填内容；prepare通过仍需真实submit。')],{inputs:{corporationId:param('可用内部收款法人库ID，不是组织ID','contract-support-corporation-search.list[].id；用户选定一个候选',{type:'string | number',required:true,lookup:{capabilityId:'contract-support-corporation-search',args:{},valueField:'list[].id',labelField:'list[].name'}})},output:{shape:'{ payeeType, companySubType, receivingCorporationId, receivingCorporationName, receivingCompanyName, receivingBankName, receivingAccount }',fields:[field('$','object','已选法人当前开户资料'),field('payeeType','integer','收款方类型，固定2',{values:{'2':'公司'}}),field('companySubType','integer','公司收款分支，固定1',{values:{'1':'内部分公司'}}),field('receivingCorporationId','string','法人库ID，与查询corporationId严格一致'),field('receivingCorporationName','string','法人名称'),field('receivingCompanyName','string','兼容显示名，后端同法人名称，不代表取得组织ID'),field('receivingBankName','string','开户行名称，来自该法人的当前收款账户'),field('receivingAccount','string','该法人收款账号，保留前导零，不转换成数字')],empty:'不存在/停用/删除法人及未配置账户由后端业务错误返回，不是空对象成功；字段缺失或空白SDK也拒绝，不沿用旧值。'},completion:'已取得并核对所选法人的当前开户信息；尚未创建差旅单或付款。',failures:['后端404未找到法人信息：回到法人候选重新核实，不切换成组织ID。','后端400该法人未配置收款账户：停止内部法人提交并报告缺配置；不得沿用上一个法人的账号。','返回法人ID不一致、字段缺失/空白或分支不是公司2/内部1：SDK拒绝，停止回填，核实响应形状。','会话/权限/网络错误保留原错误；查询可在恢复后重试，旧账户不构成本次成功结果。']})

// A parallel AI work unit may not be registered in a staged-only checkout.
if(!ALL_CAPABILITY_DEFINITIONS.some(d=>d.id==='ai-knowledge-workspace-set-permission')) C['contract-support-role-search']!.steps=[{role:'optional',when:'已选定平台角色',instruction:'交付用户所选角色id/name；当前SDK未注册知识权限写能力，不能宣称此查询已经修改知识权限。'}]
// Every definition and public method is assigned a contract; main registry owns publication and binding.
for(const d of contractSupportCapabilities){if(!C[d.id])throw new Error('Missing contract '+d.id)}
export const SUPPORT_METHOD_CONTRACTS:Record<string,AiContract>=Object.fromEntries(Object.entries(CONTRACT_SUPPORT_METHODS).map(([id,method])=>[`contractSupport.${method}`,{...C[id]!,boundaries:[...C[id]!.boundaries,'直接SDK方法签名为单个参数对象query，键名与inputs一致；注册能力invoke接受同一对象。']}]))
