import type { AiContract, AiField, AiParameter } from './ai-contract.js'
import { REPORT_DEPARTMENT_SALARY_DETAIL_METHODS, reportDepartmentSalaryDetailCapabilities } from '../capabilities/report-department-salary-detail.js'

const definitions = new Map(reportDepartmentSalaryDetailCapabilities.map(definition => [definition.id, definition]))
const field = (path: string, type: string, meaning: string): AiField => ({ path, type, meaning, optional: true, nullable: true })
const moneyFields = ['basicSalary', 'assessmentSalary', 'orgAssessmentSalary', 'orgProfitSalarySalary', 'overWorkSalary', 'educationSalary', 'workYearSalary', 'communicationSalary', 'labourSalary', 'closureSalary', 'dutySalary', 'otherSalary', 'heatstrokePreventionSalary', 'heatingSalary', 'tenancyPerkSalary', 'singleChildSalary', 'otherWelfareSalary', 'bonusSalary', 'shouldSalary', 'oldAgeSalary', 'unemploymentSalary', 'medicalSalary', 'largeMedicalSalary', 'personalSocialSecuritySalary', 'personalProvidentFundSalary', 'taxableSalary', 'personalTaxSalary', 'housePurchaseDeductionSalary', 'otherDeductionSalary', 'healthDeductionSalary', 'deductionSalary', 'actualSalary']
const pageOutput: AiContract['output'] = { shape: '{ list: object[], total: number }', fields: [field('$', 'object', '部门工资发放明细分页结果'), field('list', 'object[]', '当前页记录'), field('total', 'number', '筛选结果总数'), field('list[].name', 'string | null', '员工姓名'), field('list[].belongAccount', 'string | null', '所属账套'), field('list[].monthPay', 'string | null', '工资月份'), field('list[].staffCode', 'string | null', '员工号'), field('list[].postName', 'string | null', '岗位'), field('list[].fullPath', 'string | null', '部门路径'), field('list[].payrollUnit', 'string | null', '发薪单位'), ...moneyFields.map(name => field(`list[].${name}`, 'number | string | null', `${name}金额；服务端BigDecimal按原值返回`))], empty: 'list=[]且total=0表示当前筛选无记录。' }
const fileOutput: AiContract['output'] = { shape: '{ fileName, contentType, base64, byteLength }', fields: [field('$', 'object', '导出文件内存表示'), field('fileName', 'string', '文件名'), field('contentType', 'string | null', '响应Content-Type'), field('base64', 'string', '文件内容Base64'), field('byteLength', 'number', '文件字节数')], empty: '空文件响应会抛错。' }
const gaps = ['尚未在真实测试环境执行浏览器读请求与导出；当前证据来自Portal页面、Java DTO和离线请求断言。', '组织树、岗位树和账套候选由Portal自动加载，SDK不复制全量候选；调用方需提供已核实ID。']
const queryInputs: Record<string, AiParameter> = { belongAccount: { type: 'string | number', required: false, nullable: true, meaning: '薪资账套ID；页面单选组件的值', source: 'Portal账套候选中的已核实ID', omitted: '页面清空时发送空字符串' }, monthPay: { type: 'string', required: false, format: 'YYYY-MM', default: '当前月份', meaning: '工资月份', source: 'Portal月份选择器', omitted: '页面清空时发送空字符串' }, fullPath: { type: 'string | number', required: false, nullable: true, meaning: '角色组织树选中的部门ID；请求字段名仍为fullPath', source: 'Portal角色组织树已选节点ID', omitted: '页面清空时发送空字符串' }, payrollUnit: { type: 'string', required: false, meaning: '发薪单位模糊筛选', source: 'Portal输入框' }, postId: { type: 'string | number', required: false, nullable: true, meaning: '岗位树返回的岗位ID；只有选中岗位节点时映射为wire字段postName', source: 'Portal岗位树选中节点的postId', omitted: '未选岗位时postName发送空字符串' }, name: { type: 'string', required: false, meaning: '姓名模糊筛选', source: 'Portal输入框' }, staffCode: { type: 'string', required: false, meaning: '员工号筛选', source: 'Portal输入框' } }
function inputsOf (id: string): Record<string, AiParameter> { const definition = definitions.get(id); if (!definition) throw new Error(`部门工资明细契约缺少能力：${id}`); return Object.fromEntries(definition.params.map(parameter => [parameter.name, { type: parameter.kind === 'number' ? 'number' : parameter.kind === 'date' ? 'string' : 'string', required: parameter.required, meaning: parameter.description ?? parameter.name, source: 'Portal 部门工资发放明细页面条件或分页状态。' }])) }
function base (id: string, purpose: string, output: AiContract['output'], consume: string[]): AiContract { return { purpose, whenToUse: purpose, boundaries: ['只操作当前用户在 /dashboard/report/department-salary-detail 权限范围内的只读报表；使用platform实例并发送module-type=14。', '岗位筛选的输入postId会按Portal页面转换成请求字段postName；不要把岗位名称替代岗位ID。'], effect: 'read', prerequisites: ['已用会话token和租户创建SDK；组织、岗位和账套ID需先核实。'], inputs: { ...inputsOf(id), ...queryInputs }, output, consume, steps: [], completion: '返回分页结果或非空导出文件。', failures: ['非法ID、月份、页码或页大小在请求前失败；权限、网络和后端错误原样抛出。', '坏分页或空文件响应会抛错。'], idempotency: null, evidence: [{ source: 'src/capabilities/report-department-salary-detail.ts', kind: 'implementation', note: '锁定页面表单顺序、postId→postName映射、接口、权限和module-type。' }, { source: 'test/report-department-salary-detail.test.ts', kind: 'test', note: '离线锁定岗位映射、sort空槽、导出参数和坏响应。' }, { source: 'docs/pages/部门工资发放明细.md', kind: 'reference', note: '记录Portal页面、Java DTO与真实环境边界。' }], gaps } }
const contracts: Record<string, AiContract> = { 'report-department-salary-detail-list': base('report-department-salary-detail-list', '查询部门工资发放明细。', pageOutput, ['按list展示员工、组织、工资项目和实发工资；total只用于分页。', '工资与证件类敏感数据按原值消费，不写入日志。']), 'report-department-salary-detail-export': base('report-department-salary-detail-export', '按部门工资发放明细筛选条件导出Excel。', fileOutput, ['保存为部门工资明细表.xlsx；导出不发送排序和分页字段，岗位仍用postName映射。']) }
export const REPORT_DEPARTMENT_SALARY_DETAIL_AI_CONTRACTS: Record<string, AiContract> = Object.fromEntries(Object.keys(REPORT_DEPARTMENT_SALARY_DETAIL_METHODS).map(id => [id, contracts[id]!]))
export const REPORT_DEPARTMENT_SALARY_DETAIL_METHOD_CONTRACTS: Record<string, AiContract> = Object.fromEntries(Object.entries(REPORT_DEPARTMENT_SALARY_DETAIL_METHODS).map(([id, method]) => [`reportDepartmentSalaryDetail.${method}`, REPORT_DEPARTMENT_SALARY_DETAIL_AI_CONTRACTS[id]!]))
