import type { AiContract, AiField, AiParameter } from './ai-contract.js'
import { REPORT_COST_CENTER_SALARY_METHODS, reportCostCenterSalaryCapabilities } from '../capabilities/report-cost-center-salary.js'

const definitions = new Map(reportCostCenterSalaryCapabilities.map(definition => [definition.id, definition]))
const field = (path: string, type: string, meaning: string): AiField => ({ path, type, meaning, optional: true, nullable: true })
const amounts = ['baseSalary', 'evaluateWages', 'overtimeWages', 'educationalSubsidy', 'seniorityAllowance', 'communicationsSubsidy', 'closureFee', 'laborCosts', 'dutyPay', 'otherWages', 'bonusSalary', 'shouldSalary', 'heatFee', 'heat', 'rentalSubsidy', 'oneChildAllowance', 'otherBenefits', 'benefitsTotal']
const pageOutput: AiContract['output'] = { shape: '{ list: object[], total: number }', fields: [field('$', 'object', '成本中心薪资汇总分页结果'), field('list', 'object[]', '当前页记录'), field('total', 'number', '筛选结果总数'), field('list[].monthPay', 'string | null', '工资月份'), field('list[].orgName', 'string | null', '成本中心名称'), field('list[].staffNum', 'number | string | null', '人数'), ...amounts.map(name => field(`list[].${name}`, 'number | string | null', `${name}金额；服务端BigDecimal按原值返回`))], empty: 'list=[]且total=0表示当前筛选无记录。' }
const fileOutput: AiContract['output'] = { shape: '{ fileName, contentType, base64, byteLength }', fields: [field('$', 'object', '导出文件内存表示'), field('fileName', 'string', '文件名'), field('contentType', 'string | null', '响应Content-Type'), field('base64', 'string', '文件内容Base64'), field('byteLength', 'number', '文件字节数')], empty: '空文件响应会抛错。' }
const gaps = ['尚未在真实测试环境执行浏览器读请求与导出；当前证据来自Portal页面、Java DTO和离线请求断言。', '组织树、成本中心和账套候选由Portal自动加载，SDK不复制全量候选；调用方需提供已核实ID。']
const queryInputs: Record<string, AiParameter> = { organizationId: { type: 'string | number', required: false, nullable: true, meaning: '角色组织树选中的组织ID', source: 'Portal角色组织树已选节点ID', omitted: '页面清空时发送空字符串' }, monthPay: { type: 'string', required: false, format: 'YYYY-MM', default: '当前月份', meaning: '工资月份', source: 'Portal月份选择器', omitted: '页面清空时发送空字符串' }, costCenterId: { type: 'string | number', required: false, nullable: true, meaning: '成本中心ID', source: 'Portal成本中心下拉已选ID', omitted: '页面清空时发送空字符串' }, ledgerIds: { type: '(string | number)[]', required: false, default: '[]', meaning: '薪资账套ID数组；请求时连接为逗号字符串', source: 'Portal账套多选候选中的已核实ID', omitted: '空数组转换为空字符串' } }
function inputsOf (id: string): Record<string, AiParameter> { const definition = definitions.get(id); if (!definition) throw new Error(`成本中心薪资契约缺少能力：${id}`); return Object.fromEntries(definition.params.map(parameter => [parameter.name, { type: parameter.kind === 'number' ? 'number' : parameter.kind === 'date' ? 'string' : 'string', required: parameter.required, meaning: parameter.description ?? parameter.name, source: 'Portal 成本中心薪资汇总页面条件或分页状态。' }])) }
function base (id: string, purpose: string, output: AiContract['output'], consume: string[]): AiContract { return { purpose, whenToUse: purpose, boundaries: ['只操作当前用户在 /dashboard/report/cost-center-salary 权限范围内的只读报表；使用platform实例并发送module-type=14。', '金额和当前页合计按页面原值消费，不把当前页合计当全量合计。'], effect: 'read', prerequisites: ['已用会话token和租户创建SDK；组织、成本中心和账套ID需先核实。'], inputs: { ...inputsOf(id), ...queryInputs }, output, consume, steps: [], completion: '返回分页结果或非空导出文件。', failures: ['非法ID、月份、页码或页大小在请求前失败；权限、网络和后端错误原样抛出。', '坏分页或空文件响应会抛错。'], idempotency: null, evidence: [{ source: 'src/capabilities/report-cost-center-salary.ts', kind: 'implementation', note: '锁定列表/导出字段转换、权限、module-type和返回金额字段。' }, { source: 'test/report-cost-center-salary.test.ts', kind: 'test', note: '离线锁定请求顺序、账套投影和坏响应。' }, { source: 'docs/pages/成本中心薪资汇总.md', kind: 'reference', note: '记录Portal/Java字段和真实环境验证边界。' }], gaps } }
const contracts: Record<string, AiContract> = { 'report-cost-center-salary-list': base('report-cost-center-salary-list', '查询成本中心薪资汇总。', pageOutput, ['按list展示人数、工资和福利金额；total只用于分页。']), 'report-cost-center-salary-export': base('report-cost-center-salary-export', '按成本中心薪资汇总筛选条件导出Excel。', fileOutput, ['保存为成本中心薪资汇总.xlsx；导出不发送排序和分页字段。']) }
export const REPORT_COST_CENTER_SALARY_AI_CONTRACTS: Record<string, AiContract> = Object.fromEntries(Object.keys(REPORT_COST_CENTER_SALARY_METHODS).map(id => [id, contracts[id]!]))
export const REPORT_COST_CENTER_SALARY_METHOD_CONTRACTS: Record<string, AiContract> = Object.fromEntries(Object.entries(REPORT_COST_CENTER_SALARY_METHODS).map(([id, method]) => [`reportCostCenterSalary.${method}`, REPORT_COST_CENTER_SALARY_AI_CONTRACTS[id]!]))
