import type { AiContract, AiField, AiParameter } from './ai-contract.js'
import { HR_POST_TYPE_METHODS } from '../capabilities/hr-post-type.js'

const param = (meaning: string, source: string, extra: Partial<AiParameter> = {}): AiParameter => ({ meaning, source, ...extra })
const field = (path: string, type: string, meaning: string, extra: Partial<AiField> = {}): AiField => ({ path, type, meaning, ...extra })
const idInput = param('岗位类别主键，不是岗位 ID', 'hr-post-type-list 的 list[].id，由用户选择一条', { type: 'string | number', required: true, constraints: ['保留长 ID 字符串；数值必须是安全正整数'] })
const idsInput = param('要删除的岗位类别主键数组；单删也传一个元素的数组', 'hr-post-type-list 的 list[].id，由用户选择一条或多条', { type: 'array', required: true, constraints: ['不得为空；SDK 去重；ID 不可替换成岗位 ID'] })
const idsItem = param('数组中的一个岗位类别 ID', '所选 list[].id', { type: 'string | number', required: true })
const draftInputs: Record<string, AiParameter> = {
  name: param('类别名称，保留用户输入的首尾空格，不自动修剪', '用户输入；修改时先读取 hr-post-type-get.name', { type: 'string', required: true, constraints: ['必填、不得全为空格、最多 50 个字符；后端拒绝未删除类别中的同名记录'] }),
  sort: param('排序数值；列表后端按 sort 升序', '用户输入；修改时先读取 hr-post-type-get.sort', { type: 'integer', required: true, constraints: ['非负整数；不是优先级枚举'] }),
  remark: param('备注', '用户输入；修改时先读取 hr-post-type-get.remark', { type: 'string', required: false, omitted: 'SDK 补空字符串；修改时省略会清空已有备注', constraints: ['最多 200 个字符；允许空串，不允许非空且全为空格'] }),
}
function rowFields(prefix: string): AiField[] {
  const at = (key: string) => prefix ? `${prefix}.${key}` : key
  return [field(at('id'), 'string | number', '岗位类别主键，用于详情、修改或删除；不是岗位 ID'), field(at('name'), 'string', '类别名称'), field(at('sort'), 'integer', '排序原值，非负整数、按升序展示'), field(at('remark'), 'string', '备注；空串表示未填写，页面显示横杠', { optional: true, nullable: true, nullMeaning: '未填写备注，页面显示横杠' })]
}
const voidOutput: AiContract['output'] = { shape: 'undefined', fields: [field('$', 'undefined', 'SDK 忽略后端无业务数据的成功包络；没有返回新建 ID、删除条数或布尔成功标志')], empty: '成功为 undefined；JSON 无法编码根 undefined，调用方以 Promise 正常完成识别请求成功。失败抛错。' }
function contract(purpose: string, effect: AiContract['effect'], inputs: Record<string, AiParameter>, output: AiContract['output'], consume: string[], extra: Partial<AiContract> = {}): AiContract {
  return { purpose, whenToUse: purpose, effect, inputs, output, consume, boundaries: ['仅人力 / 岗位管理 / 岗位类别页面及其编辑、删除验证流程；不管理具体岗位。', '使用当前会话用户与租户、platform 实例及岗位类别页面上下文；普通增改删已完成测试环境 SDK 冒烟，尚无浏览器请求基准及启用短信验证链的真实记录。'], prerequisites: ['已创建带会话 token 和 tenantId 的 SDK。'], steps: [], completion: '返回当前请求的数据并交付；写操作仍须按指定查询复核业务结果。', failures: ['权限、登录、网络或后端业务错误原样抛出，不作为空结果。查询恢复后可重试；写入超时须先核实，不能自动重发。'], idempotency: effect === 'write' ? '无 SDK 或后端幂等保证；没有 requestId 参数。失败或超时先查询核实，同名校验不是幂等回执。' : null, evidence: [{ source: 'app/portal/views/dashboard/hr/post/post-type/list.vue 与 [mode]/[id].vue @ d3cf56bdc7', kind: 'reference', note: '证明列表、名称/排序/备注表单、save 路径与删除前检；没有证明测试环境部署一致。' }, { source: 'HrPostTypeController / HrPostTypeServiceImpl @ test/test dcb3f360194', kind: 'reference', note: '证明保存按 id 分支更新/新建、不返回新 ID；删除数组事务及引用占用检查。' }, { source: 'src/capabilities/hr-post-type.ts', kind: 'implementation', note: 'SDK 最终数据形状及调用顺序；测试不代替真实环境验证。' }, { source: 'smoke/pc-coverage.mjs（hr 分支，2026-09-22 测试环境执行）', kind: 'smoke', note: '通过受控会话脚本执行 SDK：创建临时类别 ID24，get 核对 sort=9999；更新后 get 核对 sort=9998；remove 后同名 list.total=0。本次敏感配置无需验证，未发送短信；未验证短信发送/收件/校验分支，也不是浏览器请求基准。' }], gaps: ['尚无本轮岗位类别浏览器请求基准，不能据 SDK 冒烟声明与页面逐字段请求一致。', '启用短信配置时的发送、收件、验证码校验及删除完整链尚未真实执行；目前仅离线测试覆盖。'], ...extra }
}
export const HR_POST_TYPE_AI_CONTRACTS: Record<string, AiContract> = {
  'hr-post-type-list': contract('分页查询当前可见的未删除岗位类别，按名称模糊筛选。', 'read', {
    name: param('类别名称包含匹配', '用户输入', { type: 'string', required: false, omitted: 'SDK 发空字符串，不限名称' }),
    pageNo: param('页码，从 1 开始', '用户分页选择', { type: 'integer', required: false, omitted: 'SDK 默认 1' }),
    pageSize: param('每页记录数', '用户分页选择', { type: 'integer', required: false, omitted: 'SDK 默认 20' }),
    order: param('renren 排序方向，保留原请求协议', '调用方分页排序状态', { type: 'string', required: false, omitted: 'SDK 发空字符串', constraints: ['页面没有启用列排序；后端固定追加 sort 升序，不承诺此参数改变最终排序'] }),
    orderField: param('renren 排序字段，保留原请求协议', '调用方分页排序状态', { type: 'string', required: false, omitted: 'SDK 发空字符串', constraints: ['页面未提供任意列排序控件，不自行猜后端字段'] }),
  }, { shape: '{ list: object[], total: number }', fields: [field('$', 'object', '岗位类别分页'), field('list', 'array', '本次当前页记录'), field('list[]', 'object', '岗位类别；页面无关扩展字段不属于展示/操作契约'), ...rowFields('list[]'), field('total', 'integer', '符合当前名称筛选且未删除的总记录数，不是当前页条数')], empty: 'list=[] 表示本页没有记录；total=0 才表示当前筛选无记录。网络/权限失败抛错。' }, ['展示 name、sort、remark；ID 仅用于动作，不能当岗位 ID。', '按 pageNo/pageSize 翻页，累计已读取数量达到 total 后停止；不要将一页视作全部。'], { completion: '交付用户要求的筛选范围；当前页或明确完成分页，不继续无目的下钻。', steps: [{ role: 'optional', when: '用户要编辑一个类别', capabilityId: 'hr-post-type-get', mapping: { id: 'result.list[].id' }, instruction: '先让用户选定一条记录，只传该类别 ID，读取现值后修改。' }] }),
  'hr-post-type-get': contract('读取岗位类别编辑表单的当前名称、排序与备注。', 'read', { id: idInput }, { shape: 'object | null', fields: [field('$', 'object | null', '岗位类别详情；后端无关扩展字段不属于本页消费契约', { nullable: true, nullMeaning: '未找到该类别，不能继续据此编辑' }), ...rowFields('')], empty: 'null 为没有详情；不要拿空对象或缓存内容代替当前详情。' }, ['只将 name、sort、remark 及本类别 id 用于修改，不回写 creator、postId 或 isDel 等扩展字段。'], { completion: '获得当前表单值；尚未保存任何修改。', steps: [{ role: 'optional', when: '用户确认了要修改的名称/排序/备注', capabilityId: 'hr-post-type-update', mapping: { id: 'result.id', name: 'result.name', sort: 'result.sort', remark: 'result.remark' }, instruction: '保留未修改字段，将用户所改字段替换为用户值；remark 为 null 时按空字符串处理，不省略需保留的旧备注。' }] }),
  'hr-post-type-create': contract('创建一个岗位类别，保存名称、排序和备注。', 'write', draftInputs, voidOutput, ['成功无新建 ID。使用相同名称查询列表，并精确核对名称/排序/备注后取得新类别 ID；不要按模糊查询第一条认领结果。'], { completion: 'Promise 完成只表示保存请求成功；查询唯一匹配记录后才能报告创建已核实。', steps: [{ role: 'required', when: '保存完成或超时需要核实是否创建', capabilityId: 'hr-post-type-list', mapping: { name: 'args.name' }, instruction: '按名称查询并逐页查找精确名称，再核对 sort/remark；多个匹配或无记录都不能猜创建成功。' }] }),
  'hr-post-type-update': contract('更新已存在岗位类别的名称、排序和备注。', 'write', { id: idInput, ...draftInputs }, voidOutput, ['先 get 取得现值，修改时完整填写 name/sort，remark 省略会清空；不要只传差异字段。'], { completion: '保存成功后 get 同一类别并核对新值才报告修改已核实。', steps: [{ role: 'required', when: '更新完成或超时后核实当前值', capabilityId: 'hr-post-type-get', mapping: { id: 'args.id' }, instruction: '核对名称、排序和备注；不要把调用未报错当成已验证。' }] }),
  'hr-post-type-prepare-remove': contract('检查所选岗位类别是否被岗位使用，并读取当前敏感删除验证配置。', 'prepare', { ids: idsInput, 'ids[]': idsItem }, { shape: '{ ids: string[], verificationRequired: boolean, phone: string | null }', fields: [field('$', 'object', '当前删除条件，不是删除回执或永久授权'), field('ids', 'array', '已去重的所选类别 ID'), field('ids[]', 'string', '一个岗位类别 ID'), field('verificationRequired', 'boolean', 'true 需要短信验证；false 仅当配置为空或 isDel 严格等于数值 1'), field('phone', 'string | null', '后端敏感操作配置 mobile；不是调用方任选的接收人', { nullable: true, nullMeaning: '没有配置接收手机号；需要验证时不能发送' })], empty: 'ids 不可为空。配置为空可返回 verificationRequired=false、phone=null；占用时抛错。' }, ['verificationRequired=true 时必须走短信验证；手机号仅展示必要掩码，不复制到日志。', '准备检查不锁定引用，remove 会重新检查，仍可能因新引用而失败。'], { completion: '已取得当前删除条件，没有发送短信或删除记录。', steps: [{ role: 'required', when: 'verificationRequired=true 且用户明确要发送删除验证码', capabilityId: 'hr-post-type-send-delete-code', mapping: { ids: 'result.ids' }, instruction: '发送至当前配置手机号；无需向调用方另索要或允许替换手机号码。' }, { role: 'optional', when: 'verificationRequired=false 且用户要继续删除', capabilityId: 'hr-post-type-remove', mapping: { ids: 'result.ids' }, instruction: '传准备结果的完整所选 ID 数组，remove 仍重新检查。' }] }),
  'hr-post-type-send-delete-code': contract('向敏感操作配置手机号发送岗位类别删除验证码。', 'write', { ids: idsInput, 'ids[]': idsItem }, { shape: '{ smsRequestId: string }', fields: [field('$', 'object', '本次短信发送结果，不是删除结果'), field('smsRequestId', 'string', '短信发送记录标识，来自服务端 requestId；不是 SDK 幂等键或岗位类别 ID')], empty: '缺少发送 requestId 会抛错；短信可能已经发送，不自动重发。' }, ['只在用户要求发送验证码时调用；验证码来自收件人，不猜测。', '后端限制一分钟一条；本方法重查占用与敏感配置，不允许传入其他手机号。'], { idempotency: '无幂等包装；后端按手机号限制一分钟一条。超时可能已发短信，先等待用户收件，不立即重发。', completion: '已得到发送记录标识；不表示收件人已收到、验证已通过或记录已删除。', steps: [{ role: 'required', when: '用户已提供本条短信收到的验证码并要删除所选类别', capabilityId: 'hr-post-type-remove', mapping: { ids: 'args.ids', smsRequestId: 'result.smsRequestId', code: 'user.code' }, instruction: 'code 来自用户收到的短信；保留同批类别 ID 与本次发送记录，不使用别人的验证码。' }] }),
  'hr-post-type-remove': contract('经占用检查与必要短信验证后，逻辑删除一条或多条岗位类别。', 'write', { ids: idsInput, 'ids[]': idsItem, smsRequestId: param('本次删除短信发送记录标识，不是幂等键', 'hr-post-type-send-delete-code.smsRequestId', { type: 'string', required: false, requiredWhen: '当前敏感配置要求短信验证', omitted: '仅不需要短信验证时可省略，否则 SDK 拒绝删除' }), code: param('收件人收到的验证码', '用户提供，不可推测', { type: 'string', required: false, requiredWhen: '当前敏感配置要求短信验证', omitted: '仅不需要短信验证时可省略，否则 SDK 拒绝删除', constraints: ['不要记录验证码到日志'] }) }, voidOutput, ['SDK 每次重新检查 checkCanDelete 和敏感配置，需要验证码时先 checkSms 成功，再发 DELETE JSON ID 数组。', '一个类别被占用会使后端整批事务失败；不要在失败后声称其它类别已经删除。'], { completion: '请求成功后需分页列表确认所选 ID 已不在未删除记录中；详情可能仍保留逻辑删除行，不能以 get 存在判失败。', steps: [{ role: 'required', when: '删除返回或超时需要核实是否已删除', capabilityId: 'hr-post-type-list', mapping: {}, instruction: '按之前记录的名称分别查询并完成分页，核对所选 ID 均不存在；不能只检查当前第一页。' }], failures: ['占用前检或删除时出现“正在被使用”：整批不能删除，核实岗位关联后再决定，不绕过前检。', '缺验证码或验证码错误：DELETE 尚未发出；取得本次有效验证码后重试，不更改敏感配置以绕过验证。', 'DELETE 超时或网络错误：结果不确定，先列表核实所选 ID；未核实前不重发。'] }),
}
export const HR_POST_TYPE_METHOD_CONTRACTS: Record<string, AiContract> = Object.fromEntries(Object.entries(HR_POST_TYPE_METHODS).map(([capabilityId, method]) => [`hrPostType.${method}`, { ...HR_POST_TYPE_AI_CONTRACTS[capabilityId]!, boundaries: [...HR_POST_TYPE_AI_CONTRACTS[capabilityId]!.boundaries, '直接方法签名为单个参数对象；键名与 inputs 一致，list 可省略对象。'] }]))
