import type { AiContract, AiField, AiParameter } from './ai-contract.js'
import { HR_INTERNAL_STAFF_METHODS, hrInternalStaffCapabilities } from '../capabilities/hr-internal-staff.js'

const definitions = new Map(hrInternalStaffCapabilities.map(definition => [definition.id, definition]))
const field = (path: string, type: string, meaning: string, extra: Partial<AiField> = {}): AiField => ({ path, type, meaning, ...extra })
const param = (meaning: string, source: string, extra: Partial<AiParameter> = {}): AiParameter => ({ meaning, source, ...extra })
const idField = (path: string, meaning: string): AiField => field(path, 'string | number', `${meaning}；Java Long 可能序列化为字符串，必须原样保留，不能转安全数字`)
const textField = (path: string, meaning: string): AiField => field(path, 'string | null', meaning, { nullable: true, nullMeaning: '服务端未填写或该字段不适用' })
const timeField = (path: string, meaning: string): AiField => field(path, 'string | number | null', `${meaning}；SDK保留Portal/服务端原值，不擅自转换时区`, { nullable: true, nullMeaning: '未填写' })

const staffFields: AiField[] = [
  idField('id', '内部员工主键，用于详情、编辑、删除和历史入口'),
  textField('name', '姓名；新建/编辑必填，最多10个字符'), idField('staffCode', '员工编号；通常由后端生成或返回'),
  field('idType', 'integer | string | null', '证件类型字典值；表单必填', { nullable: true, nullMeaning: '未选择' }),
  textField('idCard', '证件号码；表单必填，最多20个字符，只能数字和字母'), field('sex', 'integer | string | null', '性别字典值；表单必填', { nullable: true, nullMeaning: '未选择' }),
  timeField('birthday', '出生日期；表单必填，Portal格式YYYY-MM-DD HH:mm:ss'), field('age', 'integer | string | null', '按出生日期计算的年龄', { nullable: true, nullMeaning: '未计算' }),
  textField('nation', '民族；表单必填'), field('organization', 'string | number | null', '主组织ID；表单必填，属于当前用户数据权限范围', { nullable: true, nullMeaning: '未选择组织' }),
  field('otherOrganizationList', 'object[] | null', '兼职组织数组；每项包含organizationId和postIdList[]，未选择时为空数组', { nullable: true, nullMeaning: '未返回' }), field('otherOrganizationList[].organizationId', 'string | number | null', '兼职组织ID；Portal新增空行时可以暂为空，提交前需补齐', { nullable: true, nullMeaning: '尚未选择兼职组织' }), field('otherOrganizationList[].postIdList', '(string | number)[]', '该兼职组织下选择的岗位ID数组'), textField('post', '主岗位ID或值；表单必填'),
  textField('postName', '主岗位名称；列表展示值'), textField('postTypeName', '岗位类型名称'), textField('otherPosts', '其他岗位ID逗号分隔字符串；表单保存时由数组拼接'),
  textField('salaryLevel', '薪级值；表单必填'), textField('salaryStructure', '薪酬结构值；表单必填'), textField('leader', '直属负责人ID或值'),
  textField('employmentType', '用工类型字典值；表单必填'), field('status', 'integer | string | null', '员工状态；2表示离职，离职状态才允许Portal删除', { nullable: true, nullMeaning: '未返回' }),
  timeField('downtimePay', '停薪时间；status为2时表单必填，非2状态按Portal提交规则可为空'), textField('staffStatus', '在职员工状态字典值；表单必填'),
  timeField('entryTime', '入职时间；表单必填，Portal格式YYYY-MM-DD HH:mm:ss'), field('entrySeniority', 'number | string | null', '入职工龄；表单必填', { nullable: true, nullMeaning: '未返回' }),
  field('seniorityBeforeEntry', 'number | string | null', '入职前累计工龄', { nullable: true, nullMeaning: '未返回' }), field('totalSeniority', 'number | string | null', '总工龄', { nullable: true, nullMeaning: '未返回' }),
  textField('isReEmploy', '是否返聘字典值'), textField('insurancePaymentAddress', '社保缴纳地址'), textField('cardIssuingBank', '发卡银行；表单必填且不能全为空格'),
  textField('bankAccount', '银行账号；表单必填且不能全为空格'), textField('insuranceCost', '社保成本'), textField('fundCost', '公积金成本'), textField('salaryCost', '工资成本'),
  textField('insureArea', '参保地区；表单必填'), textField('isFile', '是否建档字典值'), textField('havingOnlyChildMoney', '独生子女费字典值'),
  field('mobile', 'string | number | null', '手机号/联系方式；表单必填且不能全为空格，后端可能按Long处理', { nullable: true, nullMeaning: '未填写' }), textField('email', '邮箱'),
  textField('childNumber', '子女数量'), textField('address', '现住址；表单必填且不能全为空格'), textField('residenceAddress', '户籍地址；表单必填且不能全为空格'),
  textField('emergencyContact', '紧急联系人；表单必填且不能全为空格'), textField('relationship', '紧急联系人关系'), textField('emergencyMobile', '紧急联系电话；表单必填且不能全为空格'),
  textField('remark', '备注'), textField('education', '学历字典值；表单必填'), textField('academicDegree', '学位字典值；表单必填'), textField('isFullTime', '是否全日制；表单必填'),
  textField('isUnifiedRecruitment', '是否统招'), timeField('enrollmentDate', '入学日期'), timeField('graduationTime', '毕业时间'), textField('university', '毕业院校；表单必填且不能全为空格'),
  textField('speciality', '所学专业；表单必填且不能全为空格'), textField('havingRentalSubsidies', '是否享受租房补贴'), textField('rentalFile', '租房补贴证明文件'),
]

const listFields: AiField[] = [
  field('workList', 'object[]', '工作经历数组；每项包含id、staffId、startTime、endTime、companyName、companyType、industry、department、duties、salaryRange、description、leaveReason、leaveFile、socialSecurityFile、isExternalUnit、isDel、creator、createTime、updater、updateTime'),
  field('educationalList', 'object[]', '教育经历数组；每项包含id、staffId、startTime、endTime、school、speciality、degree、academicDegree、educationalSystem、learningStyle、isFullTime、isUnifiedRecruitment、isHighestDegree、isFirstDegree、degreeFile、academicDegreeFile、isDel、creator、createTime、updater、updateTime'),
  field('familyList', 'object[]', '家庭成员数组；每项包含id、staffId、name、sex、birthday、age、duties、relationship、mobile、unit、education、remark、file、isDel、creator、createTime、updater、updateTime'),
  field('professionalList', 'object[]', '职业资格数组；每项包含id、staffId、type、name、level、code、highestLevel、unit、startTime、endTime、remark、file、isDel、creator、createTime、updater、updateTime'),
  field('positionalList', 'object[]', '职称/职务数组；每项包含id、staffId、name、level、reviewMethod、startTime、unit、code、isHighestLevel、remark、file、isDel、creator、createTime、updater、updateTime'),
  field('contractList', 'object[]', '合同数组；每项包含id、staffId、termType、type、status、signPlaceId、postId、workHours、startTime、endTime、term、signTime、probationPeriod、file、fileName、isDel、creator、createTime、updater、updateTime；termType=2提交时删除endTime'),
  field('postTransferList', 'object[]', '职务变动数组；提交时只保留id、staffId、transferType、transferTime、before/after组织/岗位/薪级/负责人ID与名称、sourceType、processInstanceId等后端字段'),
  field('rewardPunishmentList', 'object[]', '奖惩数组；每项包含id、staffId、occurDate、method、content、amount、reason、remark等字段，amount规范为0至99999999.99、最多两位小数的字符串或null'),
]

const detailOutput: AiContract['output'] = {
  shape: 'object', fields: [...staffFields, ...listFields], empty: '详情不是对象或缺少有效id会抛错；不能把空对象当作可编辑表单。',
}
const listOutput: AiContract['output'] = {
  shape: '{ list: object[], total: number }', fields: [field('list', 'object[]', '当前页内部员工列表行'), field('total', 'number', '符合筛选的总记录数，不是当前页长度'), ...staffFields.map(item => ({ ...item, path: `list[].${item.path}` }))], empty: 'list=[]且total=0表示当前筛选无记录；权限、网络或响应形状错误会抛出。',
}
const fileOutput: AiContract['output'] = {
  shape: '{ fileName: string, contentType: string, byteLength: number, base64: string }', fields: [field('fileName', 'string', '下载文件名；优先采用服务端Content-Disposition，否则使用Portal页面默认名'), field('contentType', 'string', '响应Content-Type或默认Excel MIME'), field('byteLength', 'number', '文件字节数'), field('base64', 'string', '文件二进制的标准Base64；调用方负责保存或继续传输')], empty: '空文件会抛错。',
}
const voidOutput: AiContract['output'] = { shape: 'undefined', fields: [field('$', 'undefined', '请求成功没有业务返回值；仍需按步骤回查')], empty: '成功空回执不能代替持久化证据。' }
const previewOutput: AiContract['output'] = { shape: '{ fileName: string, contentType: string, byteLength: number }', fields: [field('fileName', 'string', '待上传文件名'), field('contentType', 'string', 'Portal认可的MIME'), field('byteLength', 'number', '文件字节数')], empty: '空文件或非法Base64会抛错。' }
const historyFields: AiField[] = [idField('id', '变更记录主键'), idField('staffId', '员工主键'), textField('staffName', '员工姓名'), idField('staffCode', '员工编号'), textField('changeTypeDesc', '变更类型描述'), field('changeFieldCount', 'integer | null', '变更字段数', { nullable: true, nullMeaning: '后端未返回' }), textField('changeTime', '变更时间'), textField('operatorName', '操作人')]
const historyOutput: AiContract['output'] = { shape: '{ list: object[], total: number }', fields: [field('list', 'object[]', '当前页变更记录'), field('total', 'number', '总记录数'), ...historyFields.map(item => ({ ...item, path: `list[].${item.path}` }))], empty: 'list=[]且total=0表示无历史记录。' }
const historyDetailOutput: AiContract['output'] = { shape: 'object', fields: [...historyFields, field('changeItems', 'object[]', '逐字段变更项；每项包含dataType、dataTypeLabel、changeAction、changeActionLabel、subRecordId、fieldName、oldValue、newValue、changeDesc')], empty: '详情不是对象或缺少changeItems数组会抛错。' }

const evidence: AiContract['evidence'] = [
  { source: 'app/portal/menus/hr.js、app/portal/views/dashboard/hr/staff/staff-list.vue、list.vue、[mode]/[id].vue、components/create-multiple.vue @ bbcfc35154', kind: 'reference', note: '逐页证明菜单权限、module-type=11、查询字段、状态筛选、删除条件、自定义导出、全量表单、嵌套列表、导入和历史入口。' },
  { source: 'HrStaffController、HrStaffInfoDTO、HrStaffSelectDTO、HrStaffServiceImpl、HrStaffChangeLogController及相关DTO @ b7a359adc9e', kind: 'reference', note: '证明内部员工主表、子表、状态删除限制、导入/导出端点、变更历史和后端字段。' },
  { source: 'src/capabilities/hr-internal-staff.ts 与 test/hr-internal-staff.test.ts', kind: 'implementation', note: '证明SDK实际请求、表单投影、负例、文件协议和响应校验；不替代真实测试环境写回查。' },
]

const definitionsById = (id: string): NonNullable<ReturnType<typeof definitions.get>>['id'] => id
const contracts: Record<string, AiContract> = {}
const commonBoundaries = [
  '页面路径是/dashboard/staff/staff-list/list，权限码是/dashboard/staff/staff-list，使用platform实例并按Portal页面发送module-type=11；调用方不要自行拼接权限或module-type。',
  '列表普通exportURL没有绑定可达按钮，SDK不发布普通export；页面真正可达的是按列和组织提交的POST /org/staff/customExports。',
  '列表复选框和行删除只允许status===2的离职员工；后端DELETE也拒绝非离职员工。删除是否短信保护由全局敏感配置决定，不能绕过。',
  '职务变动组织、岗位和用户候选的页面请求没有作为无头全量选项接口发布；员工ID及相关组织/岗位/负责人ID和名称应来自当前详情或调用方已确认的数据，避免无关键字拉取几千名人员。',
]
const commonFailures = ['Portal表单规则、嵌套字段校验、敏感配置、短信校验、权限、组织数据范围、手机号重复、后端业务校验、网络或响应形状错误原样抛出；空结果不解释成权限失败。']
const base = (value: Omit<AiContract, 'whenToUse' | 'boundaries' | 'prerequisites' | 'failures' | 'evidence' | 'gaps'>): AiContract => ({
  ...value, whenToUse: '操作Portal「内部员工」页面及其页面内可达的员工资料、导入、导出和变更历史动作。', boundaries: commonBoundaries,
  prerequisites: ['使用当前用户会话token、当前租户和内部员工页面权限；员工ID、组织ID和列ID必须来自当前租户可见数据或用户明确提供。'], failures: commonFailures, evidence,
  gaps: ['已完成Portal/Java逐页静态核对和离线请求断言；尚未在真实测试环境执行本页浏览器读请求，也未执行真实新建/编辑/导入/敏感删除的prepare→submit→回查闭环。'],
})
const add = (id: string, value: AiContract): void => {
  if (!definitions.has(id)) throw new Error(`Internal staff contract has no definition: ${id}`)
  contracts[id] = value
}
const input = (id: string): Record<string, AiParameter> => Object.fromEntries((definitions.get(id)?.params ?? []).map(spec => [spec.name, param(spec.description ?? spec.name, 'Portal页面对应输入控件或前一步能力结果', { required: spec.required, type: spec.kind === 'number' ? 'number' : spec.kind === 'date' ? 'string' : 'string | object' })]))

add('hr-internal-staff-list', base({ purpose: '按Portal列表的姓名、员工编号、岗位、状态、组织、手机号和自定义SQL条件读取内部员工分页。', effect: 'read', inputs: { ...input(definitionsById('hr-internal-staff-list')) }, output: listOutput, consume: ['按total继续分页；保留list[].id、status和organization作为编辑、删除和权限范围依据。sqlParam由Java安全处理，SDK不改写成另一种过滤语法。'], steps: [{ role: 'optional', when: '用户选择编辑', capabilityId: 'hr-internal-staff-get', mapping: { id: 'result.list[].id' }, instruction: '先读取完整详情，不要只用列表行覆盖全量PUT。' }], completion: '返回一页和total；读取成功不等于具有写权限。', idempotency: null }))
add('hr-internal-staff-get', base({ purpose: '读取一个内部员工的完整主表、经历、合同、职务变动和奖惩详情。', effect: 'read', inputs: { id: param('内部员工主键。', 'hr-internal-staff-list.list[].id', { required: true, type: 'string | number' }) }, output: detailOutput, consume: ['保存完整对象作为prepareUpdate.current；staffDuties和otherPosts是后端逗号分隔值，准备阶段会恢复为表单数组后再按Portal规则拼回。'], steps: [{ role: 'optional', when: '用户确认编辑', capabilityId: 'hr-internal-staff-prepare-update', mapping: { current: 'result.$' }, instruction: '只覆盖用户明确修改的表单字段。' }], completion: '获得可用于编辑准备的完整员工详情。', idempotency: null }))
const formParam = param('Portal内部员工完整表单。主表必填字段包括name、idType、idCard、sex、birthday、staffDuties、nation、organization、post、salaryLevel、salaryStructure、employmentType、status、staffStatus、entryTime、entrySeniority、cardIssuingBank、bankAccount、insureArea、mobile、address、residenceAddress、emergencyContact、emergencyMobile、education、academicDegree、isFullTime、university、speciality；status=2时downtimePay也必填。', '用户明确提供的员工资料；嵌套字段语义见output.list[].workList等', { required: true, type: 'object', constraints: ['日期使用YYYY-MM-DD HH:mm:ss；idCard只能数字和字母；所有Portal全空格校验必须通过。'] })
const draftOutput = (meaning: string): AiContract['output'] => ({ shape: '{ draft: object }', fields: [field('draft', 'object', meaning), ...staffFields.map(item => ({ ...item, path: `draft.${item.path}` })), ...listFields.map(item => ({ ...item, path: `draft.${item.path}` }))], empty: '缺失必填字段、错误日期、非法证件号、非法奖惩金额或嵌套规则不通过时不生成草稿。' })
add('hr-internal-staff-prepare-create', base({ purpose: '离线复刻Portal新建表单校验，生成尚未提交的完整新建草稿。', effect: 'prepare', inputs: { form: formParam }, output: draftOutput('POST /org/staff的新建请求体；未把UI的_key带入子表，staffDuties和otherPosts已拼成逗号分隔字符串'), consume: ['确认所有主表必填字段、status=2时的downtimePay、嵌套教育经历school/speciality、奖惩method/content/occurDate和金额规则通过；取消时丢弃draft。'], steps: [{ role: 'required', when: '用户确认保存', capabilityId: 'hr-internal-staff-create', mapping: { draft: 'result.draft' }, instruction: '只提交准备结果；成功返回ID后用list/get回查。' }, { role: 'cancel', when: '用户取消新建', instruction: '丢弃draft，不发POST。' }], completion: '得到完整、可提交的新建草稿。', idempotency: null }))
add('hr-internal-staff-create', base({ purpose: '提交一个通过Portal表单校验的内部员工新建草稿。', effect: 'write', inputs: { draft: param('prepareCreate返回的新建草稿，不能只传差异字段。', 'hr-internal-staff-prepare-create.draft', { required: true, type: 'object' }) }, output: { shape: '{ id: string | number }', fields: [idField('id', '后端POST返回的新员工主键')], empty: '响应缺少有效ID会抛错；超时不能据此重建。' }, consume: ['发送POST /org/staff；Portal的transformUndefinedToNull效果已在能力层递归归一为null；termType=2的合同删除endTime；不把postTransferList默认空数组发送。'], steps: [{ role: 'required', when: 'POST完成或超时', capabilityId: 'hr-internal-staff-get', mapping: { id: 'result.id' }, instruction: '按返回ID回查详情，再按姓名/组织/员工编号回查列表确认写入和后端生成字段。' }], completion: '返回ID且详情/列表回查逐字段确认新员工出现。', idempotency: '后端无requestId；超时先按ID、姓名和手机号回查，确认不存在后才允许明确重试。' }))
add('hr-internal-staff-prepare-update', base({ purpose: '基于最新详情和用户明确修改，生成Portal全量PUT草稿。', effect: 'prepare', inputs: { current: param('最新get详情，必须包含id和全量子表。', 'hr-internal-staff-get', { required: true, type: 'object' }), changes: param('只覆盖Portal编辑字段；未修改字段保留current。postTransferList只有明确出现在changes中才作为全量子表发送。', '用户明确编辑意图', { required: false, nullable: true, type: 'object' }) }, output: { shape: '{ draft: object, previous: object }', fields: [field('draft', 'object', 'PUT /org/staff完整请求体'), field('previous', 'object', '提交前完整请求体；取消时只丢弃draft'), ...staffFields.map(item => ({ ...item, path: `draft.${item.path}` })), ...listFields.map(item => ({ ...item, path: `draft.${item.path}` }))], empty: 'current缺少id或主表/嵌套规则不通过时抛错。' }, consume: ['changes不允许扩展到页面未编辑的后端字段；postTransferList遵循Portal的null=不覆盖、空数组=清空、非空数组=替换语义。'], steps: [{ role: 'required', when: '用户确认保存', capabilityId: 'hr-internal-staff-update', mapping: { draft: 'result.draft' }, instruction: '只提交draft；成功后按同一ID回查完整详情。' }, { role: 'cancel', when: '用户取消', instruction: '丢弃draft，不发PUT。' }], completion: '得到尚未写入的完整PUT草稿。', idempotency: null }))
add('hr-internal-staff-update', base({ purpose: '提交一个通过Portal编辑规则的内部员工全量更新草稿。', effect: 'write', inputs: { draft: param('prepareUpdate返回的完整PUT草稿，必须包含id和所有页面必填字段。', 'hr-internal-staff-prepare-update.draft', { required: true, type: 'object' }) }, output: voidOutput, consume: ['发送PUT /org/staff；服务端会执行手机号重复检查、子表覆盖和状态变更。成功或超时后必须get回查，不可只看空回执。'], steps: [{ role: 'required', when: 'PUT完成或超时', capabilityId: 'hr-internal-staff-get', mapping: { id: 'args.draft' }, instruction: '从draft.id取同一员工ID，逐字段核对主表和受影响子表；超时先回查，不盲目重复PUT。' }], completion: '请求未抛错且详情回查确认目标字段一致。', idempotency: '后端无requestId；覆盖写超时先回查。' }))
add('hr-internal-staff-prepare-remove', base({ purpose: '校验待删除内部员工ID、Portal离职状态限制，并读取全局敏感操作配置。', effect: 'prepare', inputs: { ids: param('待删除ID数组；页面行删除为单个ID。', 'hr-internal-staff-list.list[].id', { required: true, type: 'array' }), records: param('可选列表行快照；提供时逐项要求status=2。', '当前列表行', { required: false, type: 'object[]' }) }, output: { shape: '{ ids: array, verificationRequired: boolean, phone: string | null }', fields: [field('ids', 'array', '去重后的待删除ID'), field('verificationRequired', 'boolean', '是否必须短信验证'), textField('phone', '敏感配置手机号；仅用于发送验证码')], empty: '空数组、非法ID或非离职记录会抛错。' }, consume: ['verificationRequired=true时先sendDeleteCode；取消时不发送短信也不删除。'], steps: [{ role: 'required', when: '确认删除且需要短信', capabilityId: 'hr-internal-staff-send-delete-code', mapping: { ids: 'result.ids', records: 'args.records' }, instruction: '使用敏感配置手机号发送验证码。' }, { role: 'optional', when: '确认删除且无需短信', capabilityId: 'hr-internal-staff-remove', mapping: { ids: 'result.ids', records: 'args.records' }, instruction: '直接删除后回查列表。' }, { role: 'cancel', when: '用户取消', instruction: '不调用后续删除能力。' }], completion: '得到可继续短信或删除的准备结果。', idempotency: null }))
add('hr-internal-staff-send-delete-code', base({ purpose: '在全局敏感操作开启时向配置手机号发送内部员工删除验证码。', effect: 'write', inputs: { ids: param('待删除ID数组。', 'hr-internal-staff-prepare-remove.ids', { required: true, type: 'array' }), records: param('可选列表行快照。', 'hr-internal-staff-list', { required: false, type: 'object[]' }) }, output: { shape: '{ smsRequestId: string }', fields: [field('smsRequestId', 'string', '本次短信校验requestId；不是删除幂等键')], empty: '缺少requestId会抛错且不自动重发。' }, consume: ['模板ID固定17709；验证码只由真人输入，不记录或猜测。'], steps: [{ role: 'required', when: '收到验证码后确认删除', capabilityId: 'hr-internal-staff-remove', mapping: { ids: 'args.ids', records: 'args.records', smsRequestId: 'result.smsRequestId' }, instruction: '将用户提供的code交给remove。' }], completion: '返回短信校验requestId。', idempotency: '短信发送无幂等键；结果不确定时先确认短信和requestId，不自动重发。' }))
add('hr-internal-staff-remove', base({ purpose: '按Portal敏感操作与离职状态规则逻辑删除内部员工。', effect: 'write', inputs: { ids: param('待删除ID数组。', 'hr-internal-staff-prepare-remove.ids', { required: true, type: 'array' }), records: param('可选列表行快照。', '当前列表行', { required: false, type: 'object[]' }), smsRequestId: param('敏感保护开启时的短信requestId。', 'hr-internal-staff-send-delete-code.smsRequestId', { required: false, type: 'string' }), code: param('手机号持有人提供的短信验证码。', '用户输入', { required: false, type: 'string' }) }, output: voidOutput, consume: ['SDK重新读取敏感配置；需要时先校验短信，再以ID数组DELETE /org/staff。成功/超时后回查列表确认目标ID不可见。'], steps: [{ role: 'required', when: 'DELETE完成或超时', capabilityId: 'hr-internal-staff-list', instruction: '按同一筛选和ID回查；未确认前不要重复删除。' }], completion: '列表回查确认所有目标ID不再可见。', idempotency: '逻辑删除无requestId；超时先回查。' }))

add('hr-internal-staff-custom-info', base({ purpose: '读取Portal内部员工页面的自定义查询列、导出列和当前列配置。', effect: 'read', inputs: {}, output: { shape: 'object', fields: [field('tableName', 'string', '固定hr_staff'), field('customColumnsInfo', 'object[]', '页面列定义'), field('customExportColumns', 'object[]', '可选导出列'), field('customQueryColumns', 'object[]', '可选查询列')], empty: '响应不是对象会抛错。' }, consume: ['将列定义中的ID传给customExport；不要将普通exportURL当作页面可达动作。'], steps: [], completion: '获得当前内部员工页面自定义列元数据。', idempotency: null }))
add('hr-internal-staff-custom-export', base({ purpose: '按Portal列配置和组织选择导出内部员工Excel。', effect: 'read', inputs: { columnIds: param('自定义导出列ID数组，必须非空。', 'hr-internal-staff-custom-info.customExportColumns或页面列控制器', { required: true, type: 'string[]' }), organizationIds: param('组织ID数组；Portal无选择时发送空数组。', '页面组织列控制器', { required: false, type: 'array', omitted: '发送[]' }) }, output: fileOutput, consume: ['保存base64文件；导出成功是文件回执，不代表后续导入或写操作。'], steps: [], completion: '得到非空Excel文件。', idempotency: null }))
add('hr-internal-staff-prepare-import', base({ purpose: '校验Portal员工导入控件接受的xlsx文件，生成上传预览。', effect: 'prepare', inputs: { file: param('fileName、base64、可选contentType。必须.xlsx且MIME为application/vnd.openxmlformats-officedocument.spreadsheetml.sheet。', '页面员工批量导入控件', { required: true, type: 'object' }) }, output: previewOutput, consume: ['预览通过才可调用importPrecheck；取消时不上传。'], steps: [{ role: 'required', when: '用户确认预检查', capabilityId: 'hr-internal-staff-import-precheck', mapping: { file: 'args.file' }, instruction: '先读取冲突字符串数组；有冲突需用户确认后再import。' }, { role: 'cancel', when: '用户取消', instruction: '不上传文件。' }], completion: '文件格式和内容编码通过本地校验。', idempotency: null }))
add('hr-internal-staff-import-precheck', base({ purpose: '调用Portal员工导入预检查，读取冲突/警告字符串。', effect: 'write', inputs: { file: param('prepareImport接受的xlsx文件。', 'hr-internal-staff-prepare-import.file', { required: true, type: 'object' }) }, output: { shape: 'string[]', fields: [field('$', 'string[]', '冲突或预检查提示；空数组表示没有预检查提示')], empty: '[]不表示已经导入；仍需用户确认后调用import。' }, consume: ['响应数组非空时展示给用户并等待明确确认；不自动越过确认。'], steps: [{ role: 'required', when: '用户确认导入', capabilityId: 'hr-internal-staff-import', mapping: { file: 'args.file' }, instruction: '预检查通过或用户明确确认提示后才提交导入。' }], completion: '得到Portal预检查字符串数组。', idempotency: '预检查没有幂等键；超时只可重新预检查同一文件或放弃，不得把预检查回执当作导入成功，也不要直接盲目重传import。' }))
add('hr-internal-staff-import', base({ purpose: '提交Portal员工xlsx批量导入。', effect: 'write', inputs: { file: param('xlsx文件；字段名为file，multipart/form-data。', 'hr-internal-staff-prepare-import.file', { required: true, type: 'object' }) }, output: { shape: 'string[]', fields: [field('$', 'string[]', '导入警告字符串数组；空数组表示没有警告')], empty: '空数组表示请求正常且无警告，仍建议用list按员工编号或姓名回查。' }, consume: ['导入前必须经过precheck和用户确认；成功或超时后重新list，不以数组为空作为持久化证据。'], steps: [{ role: 'required', when: '导入完成或超时', capabilityId: 'hr-internal-staff-list', instruction: '按导入文件中的员工编号/姓名和组织逐条回查。' }], completion: '请求未抛错且列表回查确认记录和字段。', idempotency: '批量导入无requestId；超时先回查，不盲目重传。' }))
add('hr-internal-staff-download-template', base({ purpose: '按页面选择的组织下载内部员工导入模板。', effect: 'read', inputs: { orgId: param('模板所属组织ID。', 'Portal模板表单组织选择', { required: true, type: 'string | number' }) }, output: fileOutput, consume: ['先GET /org/staff/downloadTemplate?orgId获取地址，再下载地址对应二进制；调用方只保存最终文件。'], steps: [], completion: '得到非空员工导入模板。', idempotency: null }))
add('hr-internal-staff-download-contract-template', base({ purpose: '下载Portal合同导入模板。', effect: 'read', inputs: {}, output: fileOutput, consume: ['文件名默认合同导入模板.xlsx。'], steps: [], completion: '得到非空合同模板。', idempotency: null }))
add('hr-internal-staff-prepare-contract-import', base({ purpose: '校验Portal合同导入xlsx和模式。', effect: 'prepare', inputs: { file: param('xlsx文件。', '合同批量导入控件', { required: true, type: 'object' }), mode: param('1表示更新，2表示新增，省略默认为2。', 'Portal导入模式单选', { required: false, type: 'number', default: '2', constraints: ['只能是1或2'] }) }, output: previewOutput, consume: ['用户取消时不上传；确认后调用importContract。'], steps: [{ role: 'required', when: '用户确认导入合同', capabilityId: 'hr-internal-staff-import-contract', mapping: { file: 'args.file', mode: 'args.mode' }, instruction: '保持模式映射，成功后回查员工详情的contractList。' }, { role: 'cancel', when: '用户取消', instruction: '不上传。' }], completion: '得到可提交合同文件预览。', idempotency: null }))
add('hr-internal-staff-import-contract', base({ purpose: '按Portal模式上传员工合同xlsx。', effect: 'write', inputs: { file: param('xlsx文件。', 'hr-internal-staff-prepare-contract-import.file', { required: true, type: 'object' }), mode: param('1更新或2新增；默认2。', 'hr-internal-staff-prepare-contract-import.mode', { required: false, type: 'number' }) }, output: { shape: 'string', fields: [field('$', 'string', '后端“导入完成”等文本回执；不是导入记录列表')], empty: '空文本会抛错。' }, consume: ['成功或超时后以get的contractList回查，不能只读文本。'], steps: [{ role: 'required', when: '上传完成或超时', capabilityId: 'hr-internal-staff-get', instruction: '回查同一员工合同列表确认新增或更新。' }], completion: '文本回执成功且详情合同数组核对一致。', idempotency: '批量合同导入无requestId；超时先回查。' }))
add('hr-internal-staff-download-post-transfer-template', base({ purpose: '下载Portal员工职务变动批量导入模板。', effect: 'read', inputs: {}, output: fileOutput, consume: ['默认文件名员工职务变动批量导入模板.xlsx。'], steps: [], completion: '得到非空职务变动模板。', idempotency: null }))
add('hr-internal-staff-prepare-post-transfer-import', base({ purpose: '校验Portal职务变动导入文件和员工ID。', effect: 'prepare', inputs: { staffId: param('目标员工ID。', '当前详情id', { required: true, type: 'string | number' }), file: param('xlsx或xls文件。', '详情页职务变动导入控件', { required: true, type: 'object' }) }, output: previewOutput, consume: ['用户取消时不上传；确认后调用importPostTransfer。'], steps: [{ role: 'required', when: '用户确认导入', capabilityId: 'hr-internal-staff-import-post-transfer', mapping: { staffId: 'args.staffId', file: 'args.file' }, instruction: '成功后重新读取该员工详情。' }, { role: 'cancel', when: '用户取消', instruction: '不上传。' }], completion: '得到可提交的职务变动文件预览。', idempotency: null }))
add('hr-internal-staff-import-post-transfer', base({ purpose: '把xlsx/xls职务变动文件上传到指定员工。', effect: 'write', inputs: { staffId: param('目标员工ID。', 'hr-internal-staff-get.id', { required: true, type: 'string | number' }), file: param('xlsx或xls文件。', 'hr-internal-staff-prepare-post-transfer-import.file', { required: true, type: 'object' }) }, output: { shape: 'string', fields: [field('$', 'string', '后端导入成功文本回执')], empty: '空文本会抛错。' }, consume: ['成功或超时后get该员工并核对postTransferList。'], steps: [{ role: 'required', when: '上传完成或超时', capabilityId: 'hr-internal-staff-get', mapping: { id: 'args.staffId' }, instruction: '回查职务变动数组。' }], completion: '文本回执成功且详情数组确认导入效果。', idempotency: '导入无requestId；超时先回查。' }))
add('hr-internal-staff-history-list', base({ purpose: '读取当前内部员工历史入口的变更记录分页。', effect: 'read', inputs: { staffId: param('员工ID；从详情页历史按钮传入。', 'hr-internal-staff-get.id', { required: false, type: 'string | number' }), operatorName: param('操作人筛选。', '历史页操作人输入框', { required: false, type: 'string' }), startTime: param('开始时间，YYYY-MM-DD HH:mm:ss。', '历史页开始时间', { required: false, type: 'string' }), endTime: param('结束时间，YYYY-MM-DD HH:mm:ss。', '历史页结束时间', { required: false, type: 'string' }), pageNo: param('从1开始页码。', 'Portal分页', { required: false, type: 'number' }), pageSize: param('每页条数，10/20/50/100。', 'Portal分页', { required: false, type: 'number' }) }, output: historyOutput, consume: ['保留记录id作为historyDetail目标；changeFieldCount是字段数量不是列表长度。'], steps: [{ role: 'optional', when: '用户查看某条历史', capabilityId: 'hr-internal-staff-history-detail', mapping: { id: 'result.list[].id' }, instruction: '读取逐字段变更项。' }], completion: '返回当前历史筛选的一页和total。', idempotency: null }))
add('hr-internal-staff-history-detail', base({ purpose: '读取一条内部员工变更历史的逐字段详情。', effect: 'read', inputs: { id: param('变更记录ID。', 'hr-internal-staff-history-list.list[].id', { required: true, type: 'string | number' }) }, output: historyDetailOutput, consume: ['用changeItems逐项展示dataType、changeAction、fieldName、oldValue、newValue和changeDesc；oldValue/newValue是文本快照，不自动转换成当前字典名称。'], steps: [], completion: '获得一条完整变更记录及其字段变化。', idempotency: null }))

export const HR_INTERNAL_STAFF_AI_CONTRACTS = contracts
export const HR_INTERNAL_STAFF_METHOD_CONTRACTS: Record<string, AiContract> = Object.fromEntries(
  Object.entries(HR_INTERNAL_STAFF_METHODS).map(([id, method]) => [`hrInternalStaff.${method}`, { ...HR_INTERNAL_STAFF_AI_CONTRACTS[id]!, boundaries: [...HR_INTERNAL_STAFF_AI_CONTRACTS[id]!.boundaries, '直接方法使用该分组的同名方法；写操作遵守prepare→submit→回查，取消仅存在于prepare之后且不会撤销已提交请求。'] }]),
)
