import type { AiContract, AiField, AiParameter } from './ai-contract.js'
import { REPORT_DEPARTMENT_SALARY_METHODS, reportDepartmentSalaryCapabilities } from '../capabilities/report-department-salary.js'

const definitions = new Map(reportDepartmentSalaryCapabilities.map(definition => [definition.id, definition]))
const field = (path: string, type: string, meaning: string): AiField => ({ path, type, meaning, optional: true, nullable: true })
const moneyFields = ['baseSalary', 'evaluateWages', 'orgAssessmentSalary', 'orgProfitSalarySalary', 'overtimeWages', 'educationalSubsidy', 'seniorityAllowance', 'communicationsSubsidy', 'laborCosts', 'dutyPay', 'otherWages', 'heatFee', 'heat', 'rentalSubsidy', 'oneChildAllowance', 'otherBenefits', 'shouldPay', 'pension', 'jobLess', 'medical', 'personalProvidentFund', 'taxableWages', 'incomeTax', 'purchaseHouse', 'otherChargebacks', 'healthDeduction', 'totalDeductions', 'netSalary', 'bigMedical', 'bonusSalary', 'closureSalary']
const pageOutput: AiContract['output'] = { shape: '{ list: object[], total: number }', fields: [field('$', 'object', '部门工资统计分页结果'), field('list', 'object[]', '当前页记录'), field('total', 'number', '筛选结果总数'), field('list[].monthPay', 'string | null', '工资月份'), field('list[].deptPath', 'string | null', '部门全称'), field('list[].postName', 'string | null', '岗位名称'), field('list[].staffNum', 'number | string | null', '人数'), ...moneyFields.map(name => field(`list[].${name}`, 'number | string | null', `${name}金额；服务端BigDecimal按原值返回`))], empty: 'list=[]且total=0表示当前筛选无记录。' }
const fileOutput: AiContract['output'] = { shape: '{ fileName, contentType, base64, byteLength }', fields: [field('$', 'object', '导出文件内存表示'), field('fileName', 'string', '文件名'), field('contentType', 'string | null', '响应Content-Type'), field('base64', 'string', '文件内容Base64'), field('byteLength', 'number', '文件字节数')], empty: '空文件响应会抛错。' }
const gaps = ['尚未在真实测试环境执行浏览器读请求与导出；当前证据来自Portal页面、Java DTO和离线请求断言。', '组织树、岗位树和账套候选由Portal自动加载，SDK不复制全量候选；调用方需提供已核实ID。']
const queryInputs: Record<string, AiParameter> = { monthPay: { type: 'string', required: false, format: 'YYYY-MM', default: '当前月份', meaning: '工资月份', source: 'Portal月份选择器', omitted: '页面清空时发送空字符串' }, orgId: { type: 'string | number', required: false, nullable: true, meaning: '角色组织树选中的部门ID', source: 'Portal角色组织树已选节点ID', omitted: '页面清空时发送空字符串' }, postId: { type: 'string | number', required: false, nullable: true, meaning: '岗位树返回的岗位ID；页面提交字段为postId', source: 'Portal岗位树选中节点的postId', omitted: '未选岗位时发送空字符串' }, ledgerIds: { type: '(string | number)[]', required: false, default: '[]', meaning: '薪资账套ID数组；请求时连接为逗号字符串', source: 'Portal账套多选候选中的已核实ID', omitted: '空数组转换为空字符串' } }
function inputsOf (id: string): Record<string, AiParameter> { const definition = definitions.get(id); if (!definition) throw new Error(`部门工资统计契约缺少能力：${id}`); return Object.fromEntries(definition.params.map(parameter => [parameter.name, { type: parameter.kind === 'number' ? 'number' : parameter.kind === 'date' ? 'string' : 'string', required: parameter.required, meaning: parameter.description ?? parameter.name, source: 'Portal 部门工资统计页面条件或分页状态。' }])) }
function base (id: string, purpose: string, output: AiContract['output'], consume: string[]): AiContract { return { purpose, whenToUse: purpose, boundaries: ['只操作当前用户在 /dashboard/report/department-salary 权限范围内的只读报表；使用platform实例并发送module-type=14。', '岗位筛选使用页面的postId字段；金额按服务端原值消费，页面合计只针对当前页。'], effect: 'read', prerequisites: ['已用会话token和租户创建SDK；组织、岗位和账套ID需先核实。'], inputs: { ...inputsOf(id), ...queryInputs }, output, consume, steps: [], completion: '返回分页结果或非空导出文件。', failures: ['非法ID、月份、页码或页大小在请求前失败；权限、网络和后端错误原样抛出。', '坏分页或空文件响应会抛错。'], idempotency: null, evidence: [{ source: 'src/capabilities/report-department-salary.ts', kind: 'implementation', note: '锁定列表/导出字段、岗位和账套转换、权限与module-type。' }, { source: 'test/report-department-salary.test.ts', kind: 'test', note: '离线锁定查询顺序、postId/账套映射和坏响应。' }, { source: 'docs/pages/部门工资统计.md', kind: 'reference', note: '记录Portal/Java字段与真实环境边界。' }], gaps } }
const contracts: Record<string, AiContract> = { 'report-department-salary-list': base('report-department-salary-list', '查询部门工资统计。', pageOutput, ['按list展示部门、岗位、人数和各工资汇总；total只用于分页。', '工资金额属于敏感数据，按原值消费。']), 'report-department-salary-export': base('report-department-salary-export', '按部门工资统计筛选条件导出Excel。', fileOutput, ['保存为部门工资统计.xlsx；导出不发送排序和分页字段。']) }
export const REPORT_DEPARTMENT_SALARY_AI_CONTRACTS: Record<string, AiContract> = Object.fromEntries(Object.keys(REPORT_DEPARTMENT_SALARY_METHODS).map(id => [id, contracts[id]!]))
export const REPORT_DEPARTMENT_SALARY_METHOD_CONTRACTS: Record<string, AiContract> = Object.fromEntries(Object.entries(REPORT_DEPARTMENT_SALARY_METHODS).map(([id, method]) => [`reportDepartmentSalary.${method}`, REPORT_DEPARTMENT_SALARY_AI_CONTRACTS[id]!]))
