import { DATA_STORE_IPC_CHANNELS } from "../data-store/channels"

export const SYNAPSE_IPC_CHANNELS = {
  content: {
    list: "synapse:content:list",
    getContent: "synapse:content:get-content",
    getDetail: "synapse:content:get-detail",
    getHistory: "synapse:content:get-history",
    getHistoryVersion: "synapse:content:get-history-version",
    create: "synapse:content:create",
    update: "synapse:content:update",
    deleteContent: "synapse:content:delete-content",
    listDeleted: "synapse:content:list-deleted",
    restore: "synapse:content:restore",
    purge: "synapse:content:purge",
    download: "synapse:content:download",
    openDetailWindow: "synapse:content:open-detail-window",
    getEditorAdapters: "synapse:content:get-editor-adapters",
    installToEditor: "synapse:content:install-to-editor",
    peekCursorFrontmatter: "synapse:content:peek-cursor-frontmatter",
    peekClaudeCodeFrontmatter: "synapse:content:peek-claude-code-frontmatter",
    readIconImage: "synapse:content:read-icon-image",
    resolveEditorInstallTarget: "synapse:content:resolve-editor-install-target",
  },
  config: {
    exportBackup: "synapse:config:export-backup",
    get: "synapse:config:get",
    importBackup: "synapse:config:import-backup",
    resetApp: "synapse:config:reset-app",
    update: "synapse:config:update",
  },
  identity: {
    adoptExistingUserId: "synapse:identity:adopt-existing-user-id",
    generateNewId: "synapse:identity:generate-new-id",
    getLocalState: "synapse:identity:get-local-state",
  },
  userProfile: {
    getRepoState: "synapse:user-profile:get-repo-state",
    listRepoProfiles: "synapse:user-profile:list-repo-profiles",
    updateDisplayName: "synapse:user-profile:update-display-name",
  },
  log: {
    clear: "synapse:log:clear",
    export: "synapse:log:export",
    listFiles: "synapse:log:list-files",
    readAll: "synapse:log:read-all",
    readFiles: "synapse:log:read-files",
    write: "synapse:log:write",
  },
  repository: {
    checkInitializationPreview: "synapse:repository:check-initialization-preview",
    createLocalRepository: "synapse:repository:create-local-repository",
    chooseDirectory: "synapse:repository:choose-directory",
    flushPendingPushes: "synapse:repository:flush-pending-pushes",
    getPendingPushes: "synapse:repository:get-pending-pushes",
    getStates: "synapse:repository:get-states",
    initializeStructure: "synapse:repository:initialize-structure",
    pendingPushesUpdated: "synapse:repository:pending-pushes-updated",
    runMaintenance: "synapse:repository:run-maintenance",
    sync: "synapse:repository:sync",
    progress: "synapse:repository:progress",
    updated: "synapse:repository:updated",
    validateDirectory: "synapse:repository:validate-directory",
  },
  editor: {
    getGlobalDirectories: "synapse:editor:get-global-directories",
    createDirectory: "synapse:editor:create-directory",
  },
  editorScan: {
    scanAll: "synapse:editor-scan:scan-all",
    readItemContent: "synapse:editor-scan:read-item-content",
    listSkillFiles: "synapse:editor-scan:list-skill-files",
  },
  cli: {
    detect: "synapse:cli:detect",
  },
  shell: {
    showItemInFolder: "synapse:shell:show-item-in-folder",
  },
  update: {
    cancelDownload: "synapse:update:cancel-download",
    checkForUpdates: "synapse:update:check-for-updates",
    getState: "synapse:update:get-state",
    installUpdate: "synapse:update:install-update",
    openUpdatePage: "synapse:update:open-update-page",
    stateChanged: "synapse:update:state-changed",
  },
  dataStore: DATA_STORE_IPC_CHANNELS,
} as const

export type SynapseAllChannels = typeof SYNAPSE_IPC_CHANNELS
