import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import type { PortalRequest } from '../src/session/types.js'
import { resolveModuleType } from '../src/context/module-type.js'
import { createReportCostCenterSalaryCapability, REPORT_COST_CENTER_SALARY_METHODS, REPORT_COST_CENTER_SALARY_PAGE_PATH, reportCostCenterSalaryCapabilities } from '../src/capabilities/report-cost-center-salary.js'
import { REPORT_COST_CENTER_SALARY_AI_CONTRACTS as contracts, REPORT_COST_CENTER_SALARY_METHOD_CONTRACTS as methodContracts } from '../src/catalog/contracts-report-cost-center-salary.js'

type RequestConfig = Parameters<PortalRequest>[0]
function fixture (responses: unknown[] = []) { const calls: RequestConfig[] = []; const request: PortalRequest = async <T>(config: RequestConfig) => { calls.push(config); const next = responses.shift(); if (next instanceof Error) throw next; return next as T }; return { api: createReportCostCenterSalaryCapability(request), calls } }
const row = { monthPay: '2026-09', orgName: '财务', staffNum: 2, baseSalary: '100.00', benefitsTotal: '20.00', extra: 'keep' }
const fileResponse = { data: new Uint8Array([1, 2]).buffer, headers: { 'content-type': 'application/vnd.ms-excel', 'content-disposition': "attachment; filename*=UTF-8''%E6%88%90%E6%9C%AC%E4%B8%AD%E5%BF%83%E8%96%AA%E8%B5%84%E6%B1%87%E6%80%BB.xlsx" } }

describe('Portal 人力报表 → 成本中心薪资汇总页面能力', () => {
  it('锁定菜单、权限、platform实例和module-type', () => { expect(reportCostCenterSalaryCapabilities.map(item => item.id)).toEqual(Object.keys(REPORT_COST_CENTER_SALARY_METHODS)); expect(reportCostCenterSalaryCapabilities.every(item => item.pagePath === REPORT_COST_CENTER_SALARY_PAGE_PATH && item.permission === '/dashboard/report/cost-center-salary' && item.moduleType === 14 && item.httpInstance === 'platform' && !item.write)).toBe(true); expect(resolveModuleType(REPORT_COST_CENTER_SALARY_PAGE_PATH).moduleType).toBe(14) })
  it('源码、菜单、Controller和DTO对齐', () => { const portalRoot = process.env.PORTAL_REPO ?? '/Users/liyang/Documents/code/wdbc/CodeReview_Projects_Js'; const javaRoot = process.env.JAVA_REPO ?? '/Users/liyang/Documents/code/wdbc/CodeReview_Mall_Platform_Java'; const menu = readFileSync(`${portalRoot}/app/portal/menus/hr.js`, 'utf8'); const source = readFileSync(`${portalRoot}/app/portal/views/dashboard/hr/report/cost-center-salary/list.vue`, 'utf8'); const controller = readFileSync(`${javaRoot}/erp-module-hr/erp-module-hr-biz/src/main/java/com/wdbc/erp/module/hr/controller/admin/report/controller/ReportSalaryController.java`, 'utf8'); const dto = readFileSync(`${javaRoot}/erp-module-hr/erp-module-hr-biz/src/main/java/com/wdbc/erp/module/hr/controller/admin/report/dto/CostCenterSummarySelectDTO.java`, 'utf8'); expect(menu).toContain(`path: '${REPORT_COST_CENTER_SALARY_PAGE_PATH}'`); expect(source).toContain("getDataListURL: '/salary/report/costCenterSummaryPage'"); expect(source).toContain('exportCostCenterSummary'); expect(controller).toContain('@GetMapping("costCenterSummaryPage")'); expect(controller).toContain('@GetMapping("exportCostCenterSummary")'); for (const field of ['organizationId', 'monthPay', 'costCenterId', 'ledgerIds', 'pageNo', 'pageSize']) expect(dto).toContain(field) })
  it('列表/导出按页面顺序投影，账套多选连接为逗号字符串', async () => { const f = fixture([{ list: [row], total: 1 }, fileResponse]); await expect(f.api.list({ organizationId: 9, monthPay: '2026-09', costCenterId: 4, ledgerIds: [11, 12], pageNo: 2, pageSize: 50 })).resolves.toEqual({ list: [row], total: 1 }); expect(f.calls[0]).toEqual({ url: '/salary/report/costCenterSummaryPage', method: 'get', params: { order: '', orderField: '', organizationId: 9, monthPay: '2026-09', costCenterId: 4, ledgerIds: '11,12', pageNo: 2, pageSize: 50 } }); await expect(f.api.export({ organizationId: 9, monthPay: '2026-09', costCenterId: 4, ledgerIds: [11, 12] })).resolves.toMatchObject({ fileName: '成本中心薪资汇总.xlsx', byteLength: 2 }); expect(f.calls[1]).toEqual({ url: '/admin-api/salary/report/exportCostCenterSummary', method: 'get', params: { organizationId: 9, monthPay: '2026-09', costCenterId: 4, ledgerIds: '11,12' }, responseType: 'arraybuffer' }) })
  it('默认月份、坏参数和空文件会失败', async () => { const f = fixture([{ list: [], total: 0 }]); await f.api.list(); expect((f.calls[0]!.params as Record<string, unknown>).monthPay).toMatch(/^\d{4}-(0[1-9]|1[0-2])$/); await expect(f.api.list({ monthPay: '2026-13' })).rejects.toThrow('YYYY-MM'); await expect(f.api.list({ ledgerIds: [0] })).rejects.toThrow('ledgerIds'); await expect(f.api.list({ pageSize: 30 })).rejects.toThrow('10、20、50、100、200或500'); await expect(fixture([{ data: new ArrayBuffer(0), headers: {} }]).api.export()).rejects.toThrow('空文件') })
  it('AI契约覆盖页面金额字段与长候选边界', () => { expect(Object.keys(contracts)).toEqual(Object.keys(REPORT_COST_CENTER_SALARY_METHODS)); expect(Object.keys(methodContracts)).toEqual([...new Set(Object.values(REPORT_COST_CENTER_SALARY_METHODS).map(method => `reportCostCenterSalary.${method}`))]); expect(contracts['report-cost-center-salary-list']?.output.fields.some(item => item.path === 'list[].benefitsTotal')).toBe(true); expect(contracts['report-cost-center-salary-list']?.gaps?.join('\n')).toContain('成本中心') })
})
