import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import type { PortalRequest } from '../src/session/types.js'
import { resolveModuleType } from '../src/context/module-type.js'
import { createReportDepartmentSalaryCapability, REPORT_DEPARTMENT_SALARY_METHODS, REPORT_DEPARTMENT_SALARY_PAGE_PATH, reportDepartmentSalaryCapabilities } from '../src/capabilities/report-department-salary.js'
import { REPORT_DEPARTMENT_SALARY_AI_CONTRACTS as contracts, REPORT_DEPARTMENT_SALARY_METHOD_CONTRACTS as methodContracts } from '../src/catalog/contracts-report-department-salary.js'

type RequestConfig = Parameters<PortalRequest>[0]
function fixture (responses: unknown[] = []) { const calls: RequestConfig[] = []; const request: PortalRequest = async <T>(config: RequestConfig) => { calls.push(config); const next = responses.shift(); if (next instanceof Error) throw next; return next as T }; return { api: createReportDepartmentSalaryCapability(request), calls } }
const row = { monthPay: '2026-09', deptPath: '总部-财务', postName: '会计', staffNum: 2, baseSalary: '100.00', netSalary: '90.00', extra: 'keep' }
const fileResponse = { data: new Uint8Array([1, 2]).buffer, headers: { 'content-type': 'application/vnd.ms-excel', 'content-disposition': "attachment; filename*=UTF-8''%E9%83%A8%E9%97%A8%E5%B7%A5%E8%B5%84%E7%BB%9F%E8%AE%A1.xlsx" } }

describe('Portal 人力报表 → 部门工资统计页面能力', () => {
  it('锁定菜单、权限、platform实例和module-type', () => { expect(reportDepartmentSalaryCapabilities.map(item => item.id)).toEqual(Object.keys(REPORT_DEPARTMENT_SALARY_METHODS)); expect(reportDepartmentSalaryCapabilities.every(item => item.pagePath === REPORT_DEPARTMENT_SALARY_PAGE_PATH && item.permission === '/dashboard/report/department-salary' && item.moduleType === 14 && item.httpInstance === 'platform' && !item.write)).toBe(true); expect(resolveModuleType(REPORT_DEPARTMENT_SALARY_PAGE_PATH).moduleType).toBe(14) })
  it('源码和Java DTO锚定接口、岗位和账套字段', () => { const portalRoot = process.env.PORTAL_REPO ?? '/Users/liyang/Documents/code/wdbc/CodeReview_Projects_Js'; const javaRoot = process.env.JAVA_REPO ?? '/Users/liyang/Documents/code/wdbc/CodeReview_Mall_Platform_Java'; const menu = readFileSync(`${portalRoot}/app/portal/menus/hr.js`, 'utf8'); const source = readFileSync(`${portalRoot}/app/portal/views/dashboard/hr/report/department-salary/list.vue`, 'utf8'); const controller = readFileSync(`${javaRoot}/erp-module-hr/erp-module-hr-biz/src/main/java/com/wdbc/erp/module/hr/controller/admin/report/controller/ReportSalaryController.java`, 'utf8'); const dto = readFileSync(`${javaRoot}/erp-module-hr/erp-module-hr-biz/src/main/java/com/wdbc/erp/module/hr/controller/admin/report/dto/DeptSalarySummarySelectDTO.java`, 'utf8'); expect(menu).toContain(`path: '${REPORT_DEPARTMENT_SALARY_PAGE_PATH}'`); expect(source).toContain("getDataListURL: '/salary/report/deptSalarySummaryPage'"); expect(source).toContain('exportDeptSalarySummary'); expect(source).toContain("postId: data.id ? data.postId : ''"); expect(controller).toContain('@GetMapping("deptSalarySummaryPage")'); expect(controller).toContain('@GetMapping("exportDeptSalarySummary")'); for (const field of ['monthPay', 'orgId', 'postId', 'ledgerIds', 'pageNo', 'pageSize']) expect(dto).toContain(field) })
  it('列表和导出精确复现月份、岗位、账套字段顺序', async () => { const f = fixture([{ list: [row], total: 1 }, fileResponse]); await expect(f.api.list({ monthPay: '2026-09', orgId: 9, postId: 77, ledgerIds: [11, 12], pageNo: 2, pageSize: 50 })).resolves.toEqual({ list: [row], total: 1 }); expect(f.calls[0]).toEqual({ url: '/salary/report/deptSalarySummaryPage', method: 'get', params: { order: '', orderField: '', monthPay: '2026-09', orgId: 9, postId: 77, ledgerIds: '11,12', pageNo: 2, pageSize: 50 } }); await expect(f.api.export({ monthPay: '2026-09', orgId: 9, postId: 77, ledgerIds: [11, 12] })).resolves.toMatchObject({ fileName: '部门工资统计.xlsx', byteLength: 2 }); expect(f.calls[1]).toEqual({ url: '/salary/report/exportDeptSalarySummary', method: 'get', params: { monthPay: '2026-09', orgId: 9, postId: 77, ledgerIds: '11,12' }, responseType: 'arraybuffer' }) })
  it('默认月份、坏参数和空文件会失败', async () => { const f = fixture([{ list: [], total: 0 }]); await f.api.list(); expect((f.calls[0]!.params as Record<string, unknown>).monthPay).toMatch(/^\d{4}-(0[1-9]|1[0-2])$/); await expect(f.api.list({ monthPay: '2026-13' })).rejects.toThrow('YYYY-MM'); await expect(f.api.list({ postId: 0 })).rejects.toThrow('postId'); await expect(f.api.list({ ledgerIds: [0] })).rejects.toThrow('ledgerIds'); await expect(f.api.list({ pageSize: 30 })).rejects.toThrow('10、20、50、100、200或500'); await expect(fixture([{ data: new ArrayBuffer(0), headers: {} }]).api.export()).rejects.toThrow('空文件') })
  it('AI契约覆盖页面金额字段和候选边界', () => { expect(Object.keys(contracts)).toEqual(Object.keys(REPORT_DEPARTMENT_SALARY_METHODS)); expect(Object.keys(methodContracts)).toEqual([...new Set(Object.values(REPORT_DEPARTMENT_SALARY_METHODS).map(method => `reportDepartmentSalary.${method}`))]); expect(contracts['report-department-salary-list']?.output.fields.some(item => item.path === 'list[].netSalary')).toBe(true); expect(contracts['report-department-salary-list']?.boundaries.join('\n')).toContain('postId') })
})
