import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import type { PortalRequest } from '../src/session/types.js'
import { resolveModuleType } from '../src/context/module-type.js'
import { createReportDepartmentSalaryDetailCapability, REPORT_DEPARTMENT_SALARY_DETAIL_METHODS, REPORT_DEPARTMENT_SALARY_DETAIL_PAGE_PATH, reportDepartmentSalaryDetailCapabilities } from '../src/capabilities/report-department-salary-detail.js'
import { REPORT_DEPARTMENT_SALARY_DETAIL_AI_CONTRACTS as contracts, REPORT_DEPARTMENT_SALARY_DETAIL_METHOD_CONTRACTS as methodContracts } from '../src/catalog/contracts-report-department-salary-detail.js'

type RequestConfig = Parameters<PortalRequest>[0]
function fixture (responses: unknown[] = []) { const calls: RequestConfig[] = []; const request: PortalRequest = async <T>(config: RequestConfig) => { calls.push(config); const next = responses.shift(); if (next instanceof Error) throw next; return next as T }; return { api: createReportDepartmentSalaryDetailCapability(request), calls } }
const row = { name: '张三', belongAccount: '账套', monthPay: '2026-09', staffCode: 'A1', postName: '岗位', fullPath: '总部', payrollUnit: '本部', basicSalary: '100.00', actualSalary: '90.00', extra: 'keep' }
const fileResponse = { data: new Uint8Array([1, 2]).buffer, headers: { 'content-type': 'application/vnd.ms-excel', 'content-disposition': "attachment; filename*=UTF-8''%E9%83%A8%E9%97%A8%E5%B7%A5%E8%B5%84%E6%98%8E%E7%BB%86%E8%A1%A8.xlsx" } }

describe('Portal 人力报表 → 部门工资发放明细页面能力', () => {
  it('锁定菜单、权限、platform实例和module-type', () => { expect(reportDepartmentSalaryDetailCapabilities.map(item => item.id)).toEqual(Object.keys(REPORT_DEPARTMENT_SALARY_DETAIL_METHODS)); expect(reportDepartmentSalaryDetailCapabilities.every(item => item.pagePath === REPORT_DEPARTMENT_SALARY_DETAIL_PAGE_PATH && item.permission === '/dashboard/report/department-salary-detail' && item.moduleType === 14 && item.httpInstance === 'platform' && !item.write)).toBe(true); expect(resolveModuleType(REPORT_DEPARTMENT_SALARY_DETAIL_PAGE_PATH).moduleType).toBe(14) })
  it('源码和Java DTO锚定岗位映射、接口和字段', () => { const portalRoot = process.env.PORTAL_REPO ?? '/Users/liyang/Documents/code/wdbc/CodeReview_Projects_Js'; const javaRoot = process.env.JAVA_REPO ?? '/Users/liyang/Documents/code/wdbc/CodeReview_Mall_Platform_Java'; const menu = readFileSync(`${portalRoot}/app/portal/menus/hr.js`, 'utf8'); const source = readFileSync(`${portalRoot}/app/portal/views/dashboard/hr/report/department-salary-detail/list.vue`, 'utf8'); const post = readFileSync(`${portalRoot}/app/portal/components/portal/hxr/tree-select/post-responsible/index.vue`, 'utf8'); const controller = readFileSync(`${javaRoot}/erp-module-hr/erp-module-hr-biz/src/main/java/com/wdbc/erp/module/hr/controller/admin/report/controller/ReportSalaryController.java`, 'utf8'); const dto = readFileSync(`${javaRoot}/erp-module-hr/erp-module-hr-biz/src/main/java/com/wdbc/erp/module/hr/controller/admin/report/dto/DeptSalaryDetailsSelectDTO.java`, 'utf8'); expect(menu).toContain(`path: '${REPORT_DEPARTMENT_SALARY_DETAIL_PAGE_PATH}'`); expect(source).toContain("getDataListURL: '/salary/report/getDeptSalaryPage'"); expect(source).toContain('exportDeptSalary'); expect(source).toContain("postName: data.id ? data.postName : ''"); expect(post).toContain("emits('update:select', selected.postId)"); expect(controller).toContain('@GetMapping("getDeptSalaryPage")'); expect(controller).toContain('@GetMapping("exportDeptSalary")'); for (const field of ['belongAccount', 'monthPay', 'fullPath', 'postName', 'pageNo', 'pageSize']) expect(dto).toContain(field) })
  it('列表和导出精确复现postId→postName、sort空槽和表单字段顺序', async () => { const f = fixture([{ list: [row], total: 1 }, fileResponse]); await expect(f.api.list({ belongAccount: 11, monthPay: '2026-09', fullPath: 9, payrollUnit: '本部', postId: 77, name: '张', staffCode: 'A1', pageNo: 2, pageSize: 50 })).resolves.toEqual({ list: [row], total: 1 }); expect(f.calls[0]).toEqual({ url: '/salary/report/getDeptSalaryPage', method: 'get', params: { order: '', orderField: '', belongAccount: 11, monthPay: '2026-09', fullPath: 9, payrollUnit: '本部', postName: 77, sort: '', name: '张', staffCode: 'A1', pageNo: 2, pageSize: 50 } }); await expect(f.api.export({ belongAccount: 11, monthPay: '2026-09', fullPath: 9, postId: 77 })).resolves.toMatchObject({ fileName: '部门工资明细表.xlsx', byteLength: 2 }); expect(f.calls[1]).toEqual({ url: '/salary/report/exportDeptSalary', method: 'get', params: { belongAccount: 11, monthPay: '2026-09', fullPath: 9, payrollUnit: '', postName: 77, sort: '', name: '', staffCode: '' }, responseType: 'arraybuffer' }) })
  it('未选岗位发送空postName；坏参数和空文件失败', async () => { const f = fixture([{ list: [], total: 0 }]); await f.api.list({ postId: null }); expect((f.calls[0]!.params as Record<string, unknown>).postName).toBe(''); await expect(f.api.list({ monthPay: '2026-13' })).rejects.toThrow('YYYY-MM'); await expect(f.api.list({ postId: 0 })).rejects.toThrow('postId'); await expect(f.api.list({ pageSize: 30 })).rejects.toThrow('10、20、50、100、200或500'); await expect(fixture([{ data: new ArrayBuffer(0), headers: {} }]).api.export()).rejects.toThrow('空文件') })
  it('AI契约锁定岗位字段语义和敏感数据边界', () => { expect(Object.keys(contracts)).toEqual(Object.keys(REPORT_DEPARTMENT_SALARY_DETAIL_METHODS)); expect(Object.keys(methodContracts)).toEqual([...new Set(Object.values(REPORT_DEPARTMENT_SALARY_DETAIL_METHODS).map(method => `reportDepartmentSalaryDetail.${method}`))]); expect(contracts['report-department-salary-detail-list']?.output.fields.some(item => item.path === 'list[].actualSalary')).toBe(true); expect(contracts['report-department-salary-detail-list']?.boundaries.join('\n')).toContain('postId') })
})
