export const CLIENT_TELEMETRY_RETENTION_DAYS = 180
export const CLIENT_TELEMETRY_BATCH_LIMIT = 50
export const CLIENT_TELEMETRY_STATS_TOP_LIMIT = 10
export const CLIENT_TELEMETRY_FILTER_OPTION_LIMIT = 100
export const CLIENT_TELEMETRY_MAX_CLOCK_SKEW_MS = 5 * 60 * 1000
export const CLIENT_TELEMETRY_MAX_EVENT_AGE_MS = 7 * 24 * 60 * 60 * 1000
