export const RATE_LIMIT_TTL_MS = 60_000
export const DEFAULT_API_RATE_LIMIT_PER_MINUTE = 600
export const DRIVE_UPLOAD_RATE_LIMIT_PER_MINUTE = 2400
export const DOCUMENT_IMAGE_UPLOAD_RATE_LIMIT_PER_MINUTE = 60
export const UPDATE_INTENT_ISSUE_RATE_LIMIT_PER_MINUTE = 10
export const UPDATE_INTENT_VERIFY_RATE_LIMIT_PER_MINUTE = 30
