export const SYNAPSE_IPC_CHANNELS = {
  content: {
    createRule: "synapse:content:create-rule",
    createSkill: "synapse:content:create-skill",
    deleteContent: "synapse:content:delete-content",
    downloadRule: "synapse:content:download-rule",
    downloadSkill: "synapse:content:download-skill",
    getEditorAdapters: "synapse:content:get-editor-adapters",
    getRuleContent: "synapse:content:get-rule-content",
    getRuleDetail: "synapse:content:get-rule-detail",
    getRuleHistory: "synapse:content:get-rule-history",
    getRuleHistoryVersion: "synapse:content:get-rule-history-version",
    getRules: "synapse:content:get-rules",
    getSkillContent: "synapse:content:get-skill-content",
    getSkillDetail: "synapse:content:get-skill-detail",
    getSkillHistory: "synapse:content:get-skill-history",
    getSkillHistoryVersion: "synapse:content:get-skill-history-version",
    getSkills: "synapse:content:get-skills",
    installToEditor: "synapse:content:install-to-editor",
    resolveEditorInstallTarget: "synapse:content:resolve-editor-install-target",
    updateRule: "synapse:content:update-rule",
    updateSkill: "synapse:content:update-skill",
  },
  config: {
    get: "synapse:config:get",
    update: "synapse:config:update",
  },
  identity: {
    generateNewId: "synapse:identity:generate-new-id",
    getState: "synapse:identity:get-state",
    replaceUserId: "synapse:identity:replace-user-id",
    updateDisplayName: "synapse:identity:update-display-name",
  },
  log: {
    appended: "synapse:log:appended",
    export: "synapse:log:export",
    list: "synapse:log:list",
    summary: "synapse:log:summary",
    write: "synapse:log:write",
  },
  repository: {
    chooseDirectory: "synapse:repository:choose-directory",
    flushPendingPushes: "synapse:repository:flush-pending-pushes",
    getPendingPushes: "synapse:repository:get-pending-pushes",
    getStates: "synapse:repository:get-states",
    pendingPushesUpdated: "synapse:repository:pending-pushes-updated",
    runMaintenance: "synapse:repository:run-maintenance",
    sync: "synapse:repository:sync",
    progress: "synapse:repository:progress",
    updated: "synapse:repository:updated",
  },
  update: {
    checkForUpdates: "synapse:update:check-for-updates",
    getState: "synapse:update:get-state",
    stateChanged: "synapse:update:state-changed",
  },
} as const
