export const SYNAPSE_IPC_CHANNELS = {
  content: {
    list: "synapse:content:list",
    getContent: "synapse:content:get-content",
    getDetail: "synapse:content:get-detail",
    getHistory: "synapse:content:get-history",
    getHistoryVersion: "synapse:content:get-history-version",
    create: "synapse:content:create",
    update: "synapse:content:update",
    deleteContent: "synapse:content:delete-content",
    download: "synapse:content:download",
    openDetailWindow: "synapse:content:open-detail-window",
    getEditorAdapters: "synapse:content:get-editor-adapters",
    installToEditor: "synapse:content:install-to-editor",
    resolveEditorInstallTarget: "synapse:content:resolve-editor-install-target",
  },
  config: {
    exportBackup: "synapse:config:export-backup",
    get: "synapse:config:get",
    importBackup: "synapse:config:import-backup",
    update: "synapse:config:update",
  },
  identity: {
    generateNewId: "synapse:identity:generate-new-id",
    getState: "synapse:identity:get-state",
    replaceUserId: "synapse:identity:replace-user-id",
    updateDisplayName: "synapse:identity:update-display-name",
  },
  log: {
    appended: "synapse:log:appended",
    export: "synapse:log:export",
    list: "synapse:log:list",
    summary: "synapse:log:summary",
    write: "synapse:log:write",
  },
  repository: {
    chooseDirectory: "synapse:repository:choose-directory",
    flushPendingPushes: "synapse:repository:flush-pending-pushes",
    getPendingPushes: "synapse:repository:get-pending-pushes",
    getStates: "synapse:repository:get-states",
    pendingPushesUpdated: "synapse:repository:pending-pushes-updated",
    runMaintenance: "synapse:repository:run-maintenance",
    sync: "synapse:repository:sync",
    progress: "synapse:repository:progress",
    updated: "synapse:repository:updated",
  },
  update: {
    checkForUpdates: "synapse:update:check-for-updates",
    getState: "synapse:update:get-state",
    stateChanged: "synapse:update:state-changed",
  },
} as const
